text/0529-conversion-traits.md, text/0921-entry_v3.md
Also some spelling and grammar and whatnot.
=> Update RFCs in line with the implementations.

text/0164-feature-gate-slice-pats.md
=> Fix typos and update syntax in RFC 164

text/0246-const-vs-static.md
Thought I'd make some suggestions while reading the doc. Thanks; interesting stuff.
=> Fix minor typos, capitalize for consistency

text/0505-api-comment-conventions.md
=> Fix typo in RFC 505

text/1192-inclusive-ranges.md
Fixes #1537 
cc @thepowersgang 
r? @aturon or @huonw
=> finish updating RFC 1192 WRT single-ended ranges

README.md
This is mostly a paraphrase of @aturon said on IRC, so thanks for explaining this part. That said, any inaccuracies in how it was paraphrased are my fault.
Since this is clarification of the current process, this does not need to go through an RFC, AFAICT.
=> Explain that RFCs can be changed based on feedback in  Process section

text/1211-mir.md
Fixing some typos in examples.
=> Fix typos.

text/2005-match-ergonomics.md
Added notes to reflect discussion on #2005.
cc @petrochenkov Does this address your concerns from the other thread? Let me know if there's anything else you'd like to see reflected in the text.
=> Adjust match ergonomics RFC to reflect discussion results

text/2005-match-ergonomics.md
=> Clear up match ergonomics summary

0000-template.md
I think we all could be doing better in the "How do we teach this?" department :) This is an attempt to give people some more ideas on the kinds of things that could go here.
f? @aturon? Would this help?
=> Add some more prompts to the "How do we teach this?" section

text/2089-implied-bounds.md, text/2093-infer-outlives.md, text/2132-copy-closures.md, text/2133-all-the-clones.md
+ Proofread RFC 2093
+ Fixed start dates & feature names of RFCs 2089, 2093, 2132, 2133.
cc @aturon
=> Proofread RFC 2093 + Fixed start dates & feature names of RFCs 2089, 2093, 2132, 2133

text/1216-bang-type.md
Was searching some info about exclamation mark that I noticed first time recently. Found lots of answers to my questions in the RFC. Thanks for the great work!
=> typo in rfc1216

text/0738-variance.md
=> Fix typo in 0738-variance.md

text/2071-impl-trait-type-alias.md
=> RFC 2071: Fix typo, existentail -> existential

0000-template.md
=> Fix link in RFC template and stuff

text/1268-allow-overlapping-impls-on-marker-traits.md
=> RFC 1268, fix feature name

text/2476-clippy-uno.md
=> Make RFC 2476 conform to template

0000-template.md
I have to manually copy this from an old merged RFC every time; this change saves me some time.
r? @aturon
=> Simplify template for FCP-complete merging steps

text/0769-sound-generic-drop.md
=> Add a link to an RFC cross reference

text/2094-nll.md
Spell out the name for 2094-nll.md.
=> Spell out the name for 2094-nll.md

text/2592-futures.md
=> Fix broken link to blog post

text/0000-simple_unwind_annotation.md
=> SimpleUnwindAnnotation: expand motivations and alternatives; emphasize fn pointer behavior

text/2457-non-ascii-idents.md
The syntax changed and the links broke.
r? @centril
=> Update unicodeset link

text/2071-impl-trait-existential-types.md
=> Fix incorrect links in existential types document

.travis.yml, generate-book.sh
* Use latest mdbook
* Handle whitespaces in filename
* Use symlink to minimize copies
r? @pietroalbini @Mark-Simulacrum
=> Reduce CI build time

text/2965-project-error-handling.md
I seem to have accidentally messed up the merge.
=> Fix merge of #2965

0000-template.md
Found a small typo in the template.
=> template-typo

text/1211-mir.md
Very well-written RFC by the way! It was a good read :)
=> Fix typos in RFC 1211 "MIR"

text/2005-match-ergonomics.md
Fix the missing code in Example
=> Fix missing code in RFC2005

book.toml
=> [non-rfc] Add github url to this repository from the gh-page

text/0243-trait-based-exception-handling.md
This PR updates RFC 243 to use Rust code blocks rather than just plaintext ones.
=> Update RFC 243 to use Rust code blocks

.github/workflows/deploy.yml
https://github.com/actions/checkout\#whats-new
=> tools: update checkout action on CI

text/2071-impl-trait-existential-types.md
=> Fix typo in RFC2071

text/1884-unstable-sort.md
Using the Wayback machine we can still visit this site.
closes #3187
=> Fix broken link

text/3228-process-process_group.md
=> Fix tracking issue link for 3228 process_set_process_group.

text/2126-path-clarity.md
Address https://github.com/rust-lang/rust/issues/53120#issuecomment-1124065083
r? @joshtriplett
=> Mention about removal of `crate` visibility specifier

text/2592-futures.md
[Rendered](https://github.com/slanterns/rfcs/blob/patch-1/text/2592-futures.md)
=> Remove a redundant space

text/3027-infallible-promotion.md
[Rendered](https://github.com/albertlarsan68/rfcs/blob/patch-1/text/3027-infallible-promotion.md)
=> Fix a typo in RFC 3027

text/3185-static-async-fn-in-trait.md
r? @nikomatsakis 
[Rendered](https://github.com/rust-lang/rfcs/blob/spastorino-patch-2/text/3185-static-async-fn-in-trait.md)
=> async fns desugared version is async move

text/3192-dyno.md
fixed function `log_active_rules` parameter
[Rendered](https://github.com/GitNiko/rfcs/blob/patch-1/text/3192-dyno.md)
=> 3192-dyno update plugin example

triagebot.toml
cc https://github.com/rust-lang/rfcs/pull/3355#issuecomment-1531976836
r? @Mark-Simulacrum - IIRC you have to change some setting in addition to adding this file?
=> Enable triagebot for RFCs repo

text/0141-lifetime-elision.md, text/0218-empty-struct-with-braces.md, text/0463-future-proof-literal-suffixes.md, text/0501-consistent_no_prelude_attributes.md, text/0563-remove-ndebug.md, text/0771-std-iter-once.md, text/0803-type-ascription.md, text/1156-adjust-default-object-bounds.md, text/1211-mir.md, text/1419-slice-copy.md, text/1443-extended-compare-and-swap.md, text/1504-int128.md, text/1521-copy-clone-semantics.md, text/1567-long-error-codes-explanation-normalization.md, text/2116-alloc-me-maybe.md, text/2873-inline-asm.md, text/3228-process-process_group.md, text/3346-t-opsem.md
Fix start date accoding to the format of YYYY-MM-DD in 0000-template.md.
[Rendered](https://github.com/xzmeng/rfcs/blob/fix-start-date/text/0141-lifetime-elision.md)
=> Fix start date

.github/workflows/deploy.yml, book.toml
This updates mdbook to the latest version, which has had a large number of small changes since 0.4.26.
Changelog: https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#mdbook-0437
Additionally this enables the curly-quotes feature, which enables [smart punctuation](https://rust-lang.github.io/mdBook/format/markdown.html#smart-punctuation).
=> Update mdbook to 0.4.37

text/0458-send-improvements.md, text/1214-projections-lifetimes-and-wf.md, text/1252-open-options.md, text/1721-crt-static.md, text/1892-uninitialized-uninhabited.md, text/2027-object_safe_for_dispatch.md, text/2044-license-rfcs.md, text/2226-fmt-debug-hex.md, text/2535-or-patterns.md, text/2795-format-args-implicit-identifiers.md, text/2957-cargo-features2.md, text/3127-trim-paths.md, text/3308-offset_of.md
[Rendered](https://github.com/pengqiseven/rfcs/blob/master/text/0458-send-improvements.md)
=> remove repetitive words

text/0461-tls-overhaul.md, text/0494-c_str-and-c_vec-stability.md, text/1044-io-fs-2.1.md, text/1414-rvalue_static_promotion.md, text/2044-license-rfcs.md, text/3509-prelude-2024-future.md, text/3543-patchable-function-entry.md
[Rendered](https://github.com/JohnEndson/rfcs/blob/master/text/0461-tls-overhaul.md)
=> chore: fix some comments

text/1298-incremental-compilation.md, text/1398-kinds-of-allocators.md, text/2091-inline-semantic.md, text/2203-const-repeat-expr.md, text/2585-unsafe-block-in-unsafe-fn.md, text/2603-rust-symbol-name-mangling-v0.md, text/3308-offset_of.md, text/3535-constants-in-patterns.md
[Rendered](https://github.com/growfrow/rfcs/blob/master/text/1298-incremental-compilation.md)
=> chore: remove repetitive words

text/0339-statically-sized-literals.md, text/0403-cargo-build-command.md, text/1869-eprintln.md, text/1990-external-doc-attribute.md, text/2300-self-in-typedefs.md, text/2361-dbg-macro.md, text/2451-re-rebalancing-coherence.md, text/2867-isa-attribute.md, text/3389-manifest-lint.md, text/3467-unsafe-pinned.md, text/3550-new-range.md
[Rendered](https://github.com/cuishuang/rfcs/blob/master/text/0339-statically-sized-literals.md)
=> fix some comments

text/3771-demote-i686-pc-windows-gnu.md
=> Fix start date for RFC 3771

triagebot.toml
as mentioned [on zulip](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Experimental.20range-diff.20for.20force-push/near/540688241)
https://forge.rust-lang.org/triagebot/range-diff.html
=> enable range-diff triagebot feature
