rust-lang/rfcs

text/0000-c_str-and-c_vec-stability.md

Stabilize the `std::{c_str, c_vec}` modules by re-working their interfaces and
refocusing each primitive for one particular task. The three broad categories of
interoperating with C will work via:
1. If you have a Rust string/byte slice which needs to be given to C, then the
`CString` type will be used to statically guarantee that a terminating nul
character and no interior nuls exist.
2. If C hands you a string which you want to inspect, but not own, then a helper
function will assist in converting the C string to a byte slice.
3. If C hands you a string which you want to inspect and own, then a helper type
will consume ownership and will act as a `Box<[u8]>` in essence.

RFC: Stabilize std::{c_str, c_vec}

---

text/0000-Self-not-sized-by-default.md

1. Remove the `Sized` default for the implicitly declared `Self`
parameter on traits.
2. Make it "object unsafe" for a trait to inherit from `Sized`.
The primary motivation is to enable a trait object `SomeTrait` to
implement the trait `SomeTrait`. This was the design goal of enforcing
object safety, but there was a detail that was overlooked, which this
RFC aims to correct.
Secondary motivations include:
- More generality for traits, as they are applicable to DST.
- Eliminate the confusing and irregular `impl Trait for ?Sized`
syntax.
- Sidestep questions about whether the `?Sized` default is inherited
like other supertrait bounds that appear in a similar position.
This change has been implemented. Fallout within the standard library
was quite minimal, since the default only affects …

Make the implicit type parameter `Self` have no default `Sized` bound

---

text/0000-consistent_no_prelude_attributes.md

Make name and behavior of the `#![no_std]` and `#![no_implicit_prelude]` attributes
consistent by renaming the latter to `#![no_prelude]` and having it only apply to the current
module.
~~Optionally add a `#[deep(...)]` attribute for deeply applying an attribute to each module as
composable replacement for the old behavior.~~
[Rendered](https://github.com/Kimundi/rfcs/blob/consistent_no_prelude_attribute/text/0000-consistent_no_prelude_attributes.md)

Consistent no-prelude attribute

---

text/0000-no-unused-impl-parameters.md

For well-defined semantics, we must ensure that impls do not have type parameters that do not appear within the trait or self-type.
[Rendered view.](https://github.com/nikomatsakis/rfcs/blob/unused-impl-parameters/text/0000-no-unused-impl-parameters.md)

Prohibit unused type parameters in impls.

---

text/0000-require-parentheses-for-chained-comparisons.md

[Rendered](https://github.com/dgrunwald/rfcs/blob/require_parentheses_for_chained_comparisons/text/0000-require-parentheses-for-chained-comparisons.md)

RFC: require parentheses for chained comparisons

---

text/0517-io-os-reform.md

Changed os::getev to os::getenv.

Tiny typo in the Unicode section.

---

text/0000-macro-future-proofing.md

[Rendered](https://github.com/cmr/rfcs/blob/macro-future-proofing/text/0000-macro-future-proofing.md)
Implementation: https://github.com/cmr/rust/tree/macro-input-future-proofing

Macro future proofing

---

active/0000-deref-coercions.md

Add the following coercions:
* From `&T` to `&U` when `T: Deref<U>`.
* From `&mut T` to `&U` when `T: Deref<U>`.
* From `&mut T` to `&mut U` when `T: DerefMut<U>`
These coercions eliminate the need for "cross-borrowing" (things like `&**v`) and calls to `as_slice`.
[Rendered](https://github.com/aturon/rfcs/blob/deref-coercions/active/0000-deref-coercions.md)

RFC: deref coercions

---

text/0000-show-string-guidelines.md

A [recent RFC](https://github.com/rust-lang/rfcs/pull/504) split what was previously `fmt::Show` into two traits, `fmt::Show` and `fmt::String`, with format specifiers `{:?}` and `{}` respectively.
That RFC did not, however, establish complete conventions for when to implement which of the traits, nor what is expected from the output.  That's what this RFC seeks to do.
[Rendered](https://github.com/aturon/rfcs/blob/show-string-guidelines/text/0000-show-string-guidelines.md)

RFC: fmt::Show and fmt::String guidelines

---

text/0517-io-os-reform.md

This RFC amendment adds the string handling section.
[Rendered](https://github.com/rust-lang/rfcs/pull/575/files?short_path=0372b19)

Amend to RFC 517: add subsection on string handling

---

text/0517-io-os-reform.md

This RFC amendment adds material for `std::env`.
[Rendered](https://github.com/aturon/rfcs/blob/io-env/text/0517-io-os-reform.md)

Amend RFC 517: Add material on std::env

---

text/0000-define-rfc-scope.md

[Rendered](https://github.com/aatxe/rfcs/blob/master/text/0000-define-rfc-scope.md)

RFC: Amend RFC process with a defined scope.

---

text/0000-fullrange-expression.md
text/0000-rangefull-expression.md

Add the syntax `..` for `std::ops::RangeFull`.
Range expressions `a..b`, `a..` and `..b` all have dedicated syntax and produce first-class values. This means that they will be usable and useful in custom APIs, so for consistency, the fourth slicing range, `RangeFull`, could have its own syntax `..`
[Rendered Version](https://github.com/bluss/rfcs/blob/full-range-syntax/text/0000-rangefull-expression.md)

Syntax for RangeFull: `..`

---

text/0000-feature-gate-box-patterns.md

[Rendered view](https://github.com/jakub-/rfcs/blob/c539b10a99c59bb96ba4657ff9263e2074aaa637/text/0000-feature-gate-box-patterns.md)

Feature gate box patterns

---

active/0000-defaulted-type-params.md

This RFC proposes finalizing the design of defaulted type parameters with two changes:
- Using `_` to explicitly use a default
- Integrating defaults and inference
[Rendered view.](https://github.com/nikomatsakis/rfcs/blob/defaulted-type-params/active/0000-defaulted-type-params.md)

Finalize defaulted type parameters

---

active/0000-nonzeroing-dynamic-drop.md

Remove drop flags from values implementing `Drop`, and remove automatic memory zeroing associated with dropping values.
Keep dynamic drop semantics, by having each function maintain a (potentially empty) set of auto-injected boolean flags for the drop obligations for the function that need to be tracked dynamically (which we will call "dynamic drop obligations").
[(rendered)](https://github.com/pnkfelix/rfcs/blob/fsk-nzdrop-rfc-take-2/active/0000-nonzeroing-dynamic-drop.md)

Non-zeroing dynamic drops

---

text/0000-no-array-elem-moves.md

In order to prepare for an expected future implementation of
[non-zeroing dynamic drop], remove support for:
* moving individual elements into an *uninitialized* fixed-sized array, and
* moving individual elements out of fixed-sized arrays `[T, ..n]`,
(copying and borrowing such elements is still permitted).
[non-zeroing dynamic drop]: https://github.com/rust-lang/rfcs/pull/320
[(rendered)](https://github.com/pnkfelix/rfcs/blob/no-array-elem-moves/text/0000-no-array-elem-moves.md)

remove certain array elem moves for non-zeroing drop

---

text/0517-io-os-reform.md

This RFC amendment adds the file system section.
[Rendered](https://github.com/rust-lang/rfcs/pull/739/files?short_path=0372b19)

Amend RFC 517: Add material on std::fs

---

0000-template.md

Every new feature that enters the language or libs should have an associated feature name, and that should be specified in the RFC to increase traceability.

Add feature name header to RFC template

---

text/0000-privacy-respecting-fru.md

Change Functional Record Update (FRU) for struct literal expressions to respect struct privacy.
[(rendered)](https://github.com/pnkfelix/rfcs/blob/fsk-privacy-respecting-fru/text/0000-privacy-respecting-fru.md)
Spawned from https://github.com/rust-lang/rust/issues/21407#issuecomment-71102002

Privacy-respecting Functional Record Update (pr-FRU)

---

text/0000-forbid-Self-definitions.md

[Rendered](https://github.com/Kimundi/rfcs/blob/forbid_Self_definitions/text/0000-forbid-Self-definitions.md)

Forbid the identifier `Self` for definitions.

---

text/0000-be2become.md

[Rendered view](https://github.com/ranma42/rfcs/blob/be2become/text/0000-be2become.md)

Replace `be` with `become`

---

text/0000-sound-generic-drop.md

Remove `#[unsafe_destructor]` from the Rust language.  Make it safe for developers to implement `Drop` on type- and lifetime-parameterized structs and enum (i.e. "Generic Drop") by imposing new rules on code where such types occur, to ensure that the drop implementation cannot possibly read or write data via a reference of type `&'a Data` where `'a` could have possibly expired before the drop code runs.
[(rendered)](https://github.com/pnkfelix/rfcs/blob/fsk-sound-generic-drop/text/0000-sound-generic-drop.md)
Spawned from https://github.com/rust-lang/rust/issues/8861

Sound Generic Drop

---

text/0769-sound-generic-drop.md

I was re-reading the text last night and realized that `'a` was
referenced only from Condition (A.) and from the final consequence
"`'a` must strictly outlive ..."; i.e. the definition was not
well-formed, since `'a` was never defined for Condition B.
This is an attempt to fill the gap to describe the semantics that I am
aiming for in the implementation.

Fix gap in the text defining the Drop-Check rule.

---

text/0517-io-os-reform.md

This RFC amendment discusses `std::process`.
[Rendered](https://github.com/aturon/rfcs/blob/io-process/text/0517-io-os-reform.md)

Amend RFC 517: Add material on std::process

---

text/0000-rustc-attribute.md

[Rendered](https://github.com/Manishearth/rfcs/blob/rustc-attr/text/0000-rustc-attribute.md)

RFC: Feature gate unused attributes

---

text/0000-default-object-bound.md

Add a default lifetime bound for object types, so that it is no longer necessary to write things like `Box<Trait+'static>` or `&'a (Trait+'a)`. The default will be based on the context in which the object type appears. Object types that appear underneath a reference take the lifetime of the innermost reference under which they appear, and otherwise the default is `'static`.
Examples:
- `&'a &'b SomeTrait` becomes `&'a &'b (SomeTrait+'b)`
- `&'a Box<SomeTrait>` becomes `&'a Box<SomeTrait+'a>`
- `Box<SomeTrait>` becomes `Box<SomeTrait+'static>`
- `Rc<SomeTrait>` becomes `Rc<SomeTrait+'static>`
Cases where the lifetime bound is either given explicitly or can be inferred from the traits involved are naturally unaffected.
[Rendered view.](https://github.com/nikomatsakis/rfcs/blob/default-object …

Introduce a default object lifetime bound

---

text/0000-variance.md

A revised proposal for properly supporting variance in Rust's type system. 
[Rendered view.](https://github.com/nikomatsakis/rfcs/blob/variance-redux/text/0000-variance.md)

Support variance for type parameters

---

text/0000-send-improvements.md

[Rendered view](https://github.com/pythonesque/rfcs/blob/send-improvements/text/0000-send-improvements.md).
This RFC proposes extending the ```Send``` trait in some relatively small but backwards incompatible ways, to allow more safe behaviors to be exposed in Rust's type system.  In particular, this involves removing the ```'static``` bound from Send in a way that preserves thread safety.

RFC: Improve the Send trait.

---

text/0000-from-elem-with-love.md

[rendered](https://github.com/Gankro/rfcs/blob/from_elem/text/0000-from-elem-with-love.md)

Add back `Vec::from_elem`

---

text/0000-hash-simplification.md

Two alternatives are proposed for paring back the API of `std::hash` to be more
ergnomic for both consumers and implementors.
[Rendered](https://github.com/alexcrichton/rfcs/blob/hashv3/text/0000-hash-simplification.md)

RFC: Simplify `std::hash`

---

text/0000-c-str-deref.md

Change the `Deref` target of `CString` to a token type `CStr`.
Add helper functions and macros to produce `CStr` references out of static string data.
[Rendered](https://github.com/mzabaluev/rust-rfcs/blob/c-str-deref/text/0000-c-str-deref.md)

RFC: CStr, the dereferenced complement to CString

---

text/0000-no-panic-in-c-string.md

Bring `CString` in line with other library functions on the failure mode conventions.
There should be no panic lurking.
[Rendered](https://github.com/mzabaluev/rust-rfcs/blob/no-panic-in-c-string/text/0000-no-panic-in-c-string.md)

RFC: get panics out of std::ffi::CString

---

text/0517-io-os-reform.md

This RFC amendment adds the networking section.
[Rendered](https://github.com/rust-lang/rfcs/pull/807/files?short_path=0372b19#diff-0372b196bcfe91383c810c2ec4a968c5)

Amend RFC 517: Add material on std::net

---

text/0000-string-patterns.md

Stabilize all string functions working with search patterns around a new
generic API that provides a unified way to define and use those patterns.
Right now, string slices define a couple of methods for string
manipulation that work with user provided values that act as
search patterns. For example, `split()` takes an type implementing `CharEq`
to split the slice at all codepoints that match that predicate.
Among these methods, the notion of what exactly is being used as a search
pattern varies inconsistently: Many work with the generic `CharEq`,
which only looks at a single codepoint at a time; and some
work with `char` or `&str` directly, sometimes duplicating a method to
provide operations for both.
This RFC proposes a set of traits for defining such patterns, which enable efficient …

Add a generic string pattern matching API

---

text/0255-object-safety.md

Amend object safety RFC to include the complete set of rules, along with an exemption that permits individual methods to require that `Self:Sized`. 
Implemented on the following branch:
https://github.com/nikomatsakis/rust/tree/object-safe-sized-methods

Tweaks to the object-safety rules

---

text/0000-remove-ndebug.md

[Rendered View](https://github.com/Aatch/rust-rfcs/blob/remove-ndebug/text/0000-remove-ndebug.md)

Remove official ndebug variable support

---

text/0000-api-comment-conventions.md

[Rendered](https://github.com/steveklabnik/rfcs/blob/api_comment_conventions/text/0000-api-comment-conventions.md)
I'm mostly trying to codify what we already have consensus on, rather than address every possible question. I can forsee this kind of RFC getting very bogged down in a number of different details, and we can always add more things in a future RFC.

API comment conventions

---

text/0544-rename-int-uint.md

This RFC (or RFC amendment) proposes that `isize/usize` get used as the literal suffixes for the *types* `isize/usize`, in order to address the problems of the previously chosen `is/us`.
This RFC used to promote `isz/usz`, which was brought up by @rkjnsn in [this thread](http://discuss.rust-lang.org/t/use-a-more-clear-suffix-for-isize-and-usize-literals-isz-and-usz/1279).
[Rendered View](https://github.com/CloudiDust/rfcs/blob/int-to-intx/text/0544-rename-int-uint.md).
Note: the Rendered View shows the amended RFC 544, but the interesting parts are better highlighted in the [diff](https://github.com/rust-lang/rfcs/pull/573/files#diff-0).

Amend RFC 544: Use `isize/usize` as the literal suffixes for themselves

---

text/0000-allow-inherent-impls-anywhere.md

The "Revised UFCS proposal", PR #132, makes the restriction imposed by PR #155 unnecessary:
> Whenever a path like `...::a::...` resolves to a type (but not a *trait*), it is rewritten (internally) to `<...::a>::...`.
This applies to all non-trait `impl`s, and because `<T>::item` has to be handled during type-checking, that removes any need to handle `impl`s (or treat them as modules, for that matter) in resolution, eliminating
all the issues #155 was trying to solve by being overly conservative.

Revert "RFC to require `impl MyStruct` to be nearby the definition of `MyStruct`"

---

text/0231-upvar-capture-inference.md

A handful of minor grammatical and typographical fixes.

Minor fixups to 0231-upvar-capture-inference.md.

---

text/0000-drain-range.md

[Rendered](https://github.com/mahkoh/rfcs/blob/drain_range/text/0000-drain-range.md)

Replace `Vec::drain` by a method that accepts a range parameter.

---

text/0000-array-pattern-changes.md

Change array/slice patterns in the following ways:
- Make them only match on arrays (`[T, ..n]` and `[T]`), not slices (#478);
- Make subslice matching yield a value of type `[T, ..n]` or `[T]`, not `&[T]` or `&mut [T]`;
- Allow multiple mutable references to be made to different parts of the same array or slice in array patterns (resolving rust-lang/rust#8636).
[Rendered](https://github.com/P1start/rfcs/blob/array-pattern-changes/text/0000-array-pattern-changes.md)

RFC: Array pattern adjustments

---

text/0517-io-os-reform.md

Expand the section on stdin, stdout, and stderr while also adding a new section
explaining the fate of the current print-related functions.
[Rendered](https://github.com/rust-lang/rfcs/pull/899/files?short_path=0372b19#diff-0372b196bcfe91383c810c2ec4a968c5)

Amend RFC 517: Add material for stdio

---

text/0517-io-os-reform.md

The distinction between "shallow" and "deep" flush needs to be made clear in the specification.
As described in rust-lang/rust#23386, the current implementation of `into_inner` methods only writes out the buffered data.

Amend I/O RFC: clarify the behavior of into_inner

---

text/0000-type-ascription.md

Closes #354
[rendered](https://github.com/nick29581/rfcs/blob/ascription/text/0000-type-ascription.md)

Type ascription

---

text/0000-closure-return-type-syntax.md

[Rendered version.](https://github.com/nikomatsakis/rfcs/blob/closure-ret-type-syntax/text/0000-closure-return-type-syntax.md)

Tweak closure return type annotation to eliminate future limitations for type grammar

---

text/0517-io-os-reform.md

* Renames `SocketAddr` -> `InetAddr` (since there are other socket address types like unix domain socket addresses).
* Add `InetAddr::is_unspecified()` and `InetAddr::any_v*()`
* Adds some functions to `IpAddr` that proxy to the versioned ip address type.
* Add `any_*` functions to `IpAddr` and the versioned ip address types

Tweaks to std::net address types

---

text/0000-entry_v3.md

Replace Entry::get with Entry::default and Entry::default_with for better ergonomics and clearer code.
```
*map.entry(key).default(0) += 1;
```
```
// vec![] doesn't even allocate, and is only 3 ptrs big.
map.entry(key).default(vec![]).push(val);
```
```
let val = map.entry(key).default_with(|| expensive(big, data));
```
[Rendered](https://github.com/Gankro/rfcs/blob/entry_v3/text/0000-entry_v3.md)

entry API v3

---

text/0000-hyphens-considered-harmful.md
text/0403-cargo-build-command.md

Disallow hyphens in Rust crate names, but continue allowing them in Cargo packages.
[Rendered](https://github.com/lfairy/rfcs/blob/hyphens-considered-harmful/text/0000-hyphens-considered-harmful.md)

Disallow hyphens in Rust crate names

---

text/0000-move-thread-local-to-std-thread.md

Propose moving the contents of `std::thread_local::*` into `std::thread`
[Rendered](https://github.com/carllerche/rfcs/blob/master/text/0000-move-thread-local-to-std-thread.md)

Move `std::thread_local::*` into `std::thread`

---

text/0000-conversion-traits.md

This RFC proposes several new *generic conversion* traits. The
motivation is to remove the need for ad hoc conversion traits (like
`FromStr`, `AsSlice`, `ToSocketAddr`, `FromError`) whose *sole role*
is for generics bounds. Aside from cutting down on trait
proliferation, centralizing these traits also helps the ecosystem
avoid incompatible ad hoc conversion traits defined downstream from
the types they convert to or from. It also future-proofs against
eventual language features for ergonomic conversion-based overloading.
[Rendered](https://github.com/aturon/rfcs/blob/conversion-traits/text/0000-conversion-traits.md)

RFC: Generic conversion traits

---

text/0921-entry_v3.md

The names where changed from `default*` to `or_insert*`, but one occurrence was still using the old name.

Fix typo in 0921-entry_v3.md

---

text/0517-io-os-reform.md

The alleged implementation of this RFC in
<https://github.com/rust-lang/rust/pull/22015> included `try_clone` rather
than `duplicate`. This commit updates the approved RFC to match the actual
implementation.

Replace duplicate() by try_clone() in std::net.

---

text/0000-small-base-lexing.md

[Rendered](https://github.com/huonw/rfcs/blob/small-bases/text/0000-small-base-lexing.md).

RFC to lex binary and octal literals more eagerly.

---

text/0000-align-splitn-with-other-languages.md

[Rendered](https://github.com/shepmaster/rfcs/blob/align-splitn-with-other-languages/text/0000-align-splitn-with-other-languages.md)

Align the count parameter of splitn with other languages

---

text/0000-process-exit.md

Add a new function to the `std::process` module to exit the process immediately
with a specified exit code.
[Rendered](https://github.com/alexcrichton/rfcs/blob/process-exit/text/0000-process-exit.md)

RFC: Add std::process::exit

---

text/0560-integer-overflow.md

As the subject says. 
Some prior discussion: http://internals.rust-lang.org/t/on-casts-and-checked-overflow/1710/

Amend overflow RFC to alter semantics of `as`; make wrapping methods inherent methods

---

text/0000-rebalancing-coherence.md

I recently realized that our current trait system contains a [forward compatibility hazard](https://github.com/rust-lang/rust/issues/23086) concerned with *negative reasoning*. The TL;DR is that negative reasoning (that is, the compiler saying that "doing X is legal if the trait T is NOT implemented for some type U") can easily make it impossible to add impls of any traits in a backwards compatible way. The most obvious example of negative reasoning are [negative trait bounds](https://github.com/rust-lang/rfcs/pull/586), which have been proposed in a rather nicely written RFC. However, even without negative bounds, the trait system as currently implemented already has some amount of negative reasoning, in the form of the coherence system.
This RFC is fairly simple proposal that tries to …

Rebalancing coherence.

---

text/0000-const-fn.md

[Rendered](https://github.com/eddyb/rfcs/blob/const-fn/text/0000-const-fn.md)
Reference implementation is at rust-lang/rust#22816.

Const functions and inherent methods.

---

text/0000-compiler-fence-intrinsics.md

[Rendered.](https://github.com/tari/rfcs/blob/compiler-fences/text/0000-compiler-fence-intrinsics.md)

Add singlethreaded (compiler-only) fences.

---

text/0560-integer-overflow.md

refine detail about what "old behavior" of `as` is.

refine detail about what "old behavior" of `as` is.

---

text/0000-discriminant-intrinsic.md

Implement an intrinsic for extracting the discriminant from a value.
---
[Rendered](https://github.com/Aatch/rust-rfcs/blob/disr-intrinsic/text/0000-discriminant-intrinsic.md)

Implement a 'discriminant_value' intrinsic

---

active/0000-empty-structs-with-braces.md

When a struct type S has no fields (a so-called "empty struct"), allow it to be defined via either struct S; or struct S {}. Allow instances of `struct S` to be constructed and pattern-matched via either S or S {}.  Allow instances of `struct S {}` to be constructed and pattern-matched via `S {}`.
[Rendered](https://github.com/pnkfelix/rfcs/blob/empty-struct-with-braces-take-2/active/0000-empty-structs-with-braces.md)
This is a semi-revival of RFC PR #147, but hopefully well-fleshed out enough for proper consideration.

Empty struct with braces take 2

---

text/0000-std-iter-once.md

[Rendered](https://github.com/XMPPwocky/rfcs/blob/b30ad7141d43c7df0bac5ab76b1b5b0d1a735d9f/text/0000-std-iter-once.md)

Std::iter::once

---

text/0000-prelude-additions.md

Add `Default`, `IntoIterator` and `ToOwned` trait to the prelude.
[Rendered](https://github.com/aturon/rfcs/blob/prelude-additions/text/0000-prelude-additions.md)
Closes #942

RFC for pre-1.0 prelude additions

---

text/0000-rename-soft-link-to-symlink.md

[Rendered](https://github.com/lambda/rfcs/blob/rename-soft-link-to-symlink/text/0000-rename-soft-link-to-symlink.md)

RFC: split up fs::soft_link into os::unix::fs::symlink and os::windows::fs::{symlink_file, symlink_dir}

---

text/0000-str-words.md

[View](https://github.com/SimonSapin/rfcs/blob/str-words/text/0000-str-words.md).

Rename or replace `str::words` to side-step the ambiguity of “a word”.

---

text/0000-io-error-sync.md

[Rendered](https://github.com/kballard/rfcs/blob/io-error-sync/text/0000-io-error-sync.md)
A PR for this has already been written as rust-lang/rust#24133.

RFC for adding Sync to io::Error

---

text/0000-io-fs-2.1.md

Expand the scope of the `std::fs` module by enhancing existing functionality,
exposing lower level representations, and adding a few more new functions.
[Rendered](https://github.com/alexcrichton/rfcs/blob/io-fs2.1/text/0000-io-fs-2.1.md)

RFC: Expand the scope of `std::fs`

---

text/0000-duration-reform.md

[Rendered](https://github.com/wycats/rfcs/blob/duration-reform/text/0000-duration-reform.md)

Duration Reform RFC

---

text/0000-safe-mem-forget.md

Alter the signature of the `std::mem::forget` function to remove `unsafe`
Explicitly state that it is not considered unsafe behavior to not run
destructors.
[Rendered](https://github.com/alexcrichton/rfcs/blob/safe-mem-forget/text/0000-safe-mem-forget.md)

RFC: Alter mem::forget to be safe

---

text/0000-socket-timeouts.md

Add sockopt-style timeouts to `std::net` types.
[Rendered](https://github.com/aturon/rfcs/blob/socket-timeouts/text/0000-socket-timeouts.md)

RFC: Socket timeouts

---

text/0000-embrace-extend-extinguish.md

Make all collections `impl<'a, T: Copy> Extend<&'a T>`. 
This enables both `vec.extend(&[1, 2, 3])`, and `vec.extend(&hash_set_of_ints)`. This provides a more expressive replacement for `Vec::push_all` with literally no ergonomic loss, while leveraging established APIs.
[rendered](https://github.com/Gankro/rfcs/blob/embrace-extend-and-extinguish/text/0000-embrace-extend-extinguish.md)

Have collections impl Extend<&T> where T: copy

---

0000-stdout-existential-crisis.md

[Rendered](https://github.com/retep998/rfcs/blob/println/0000-stdout-existential-crisis.md)

Don't panic when stdout doesn't exist

---

0000-remove-static-assert.md

[rendered](https://github.com/steveklabnik/rfcs/blob/remove_static_assert/0000-remove-static-assert.md)

remove static_assert

---

README.md
text/0008-new-intrinsics.md

This RFC changed the design of intrinsics with the goal of eliminating
the need for creating inlined wrappers around them. In the meantime,
the critical intrinsics for which this have been a problem have all
had their wrappers removed (afaik without solving the problem this
RFC set out to solve).
In the meantime, I decided I do not like the design here that unifies
intrinsics and lang items - they are sufficiently different to warrant
different names.
The ideas here have bitrotted and when we need to solve this for real
we should start over.

Retire RFC 8 (intrinsics) without implementing it.

---

text/0000-dst-coercion.md

Custom coercions allow smart pointers to fully participate in the DST system.
In particular, they allow practical use of `Rc<T>` and `Arc<T>` where `T` is unsized.
This RFC subsumes part of [RFC 401 coercions](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md).

DST custom coercions.

---

text/0000-str-split-at.md

Introduce the method `split_at(&self, mid: usize) -> (&str, &str)` on `str`,
to divide a slice into two, just like we can with `[T]`.
[**Rendered version**](https://github.com/bluss/rfcs/blob/str-split-at/text/0000-str-split-at.md)
Adding `split_at` is a measure to provide a method from `[T]` in a version that
makes sense for `str`.
Once used to `[T]`, users might even expect that `split_at` is present on str.
```rust
/// Divide one string slice into two at an index.
///
/// The index `mid` is a byte offset from the start of the string
/// that must be on a character boundary.
///
/// Return slices `&self[..mid]` and `&self[mid..]`.
///
/// # Panics
///
/// Panics if `mid` is beyond the last character of the string,
/// or if it is not on a character boundary.
///
/// # Examples
/// ``` …

RFC: introduce `split_at(mid: usize)` on `str`

---

text/0000-result-expect.md

See also https://github.com/rust-lang/rust/pull/25359 for implementation
[Rendered](https://github.com/thepowersgang/rust-lang_rfcs/blob/result-expect/text/0000-result-expect.md)

Quick draft "Result::expect" rfc

---

text/0000-expect-intrinsic.md

[Rendered View](https://github.com/Aatch/rust-rfcs/blob/expect-intrinsic/text/0000-expect-intrinsic.md)

Add an expect intrinsic

---

text/0000-api-evolution.md

This RFC proposes a comprehensive set of guidelines for which changes to
*stable* APIs are considered breaking from a semver perspective, and which are
not.  These guidelines are intended for both the standard library and for the
crates.io ecosystem.
This does *not* mean that the standard library should be completely free to make
non-semver-breaking changes; there are sometimes still risks of ecosystem pain
that need to be taken into account. Rather, this RFC makes explicit an initial
set of changes that absolutely *cannot* be made without a semver bump.
Along the way, it also discusses some interactions with potential language
features that can help mitigate pain for non-breaking changes.
The RFC covers only API issues; other issues related to language features,
lints, type inference, …

RFC: Policy on semver and API evolution

---

text/0401-coercions.md

Clarify cast rules, especially regarding fat pointers.

---

text/0195-associated-items.md

**Edit:** While the goal of this RFC is the same, namely to provide further interpretation of the design of associated constants, the current proposal differs radically from the original PR. This PR now clarifies that associated statics are *not* added, only constants, and mentions some limitations on associated constants that require more design work to deal with.
[Rendered.](https://github.com/rust-lang/rfcs/pull/865/files?short_path=e0686e7#diff-e0686e7af71a6699c8dc01e510e51e1c)
**Original text of this post follows**
Currently, the associated items RFC only provides for associated functions, lifetimes, statics, and types. However, it was never updated to account for the const/static split. This PR makes minimal changes to address this by adding associated consts as well.
The original …

Update RFC 195 to account for RFC 246.

---

text/0000-adjust-default-object-bounds.md
text/1122-language-semver.md

Adjust the object default bound algorithm for cases like `&'x Box<Trait>` and `&'x Arc<Trait>`. The existing algorithm would default to `&'x Box<Trait+'x>`. The proposed change is to default to `&'x Box<Trait+'static>`. A new attribute, `#[legacy(default_object_bounds)]`, can be used to restore the current behavior to ease the transition.
Note: This is a **BREAKING CHANGE**. The change has [been implemented][branch] and its impact has been evaluated. It was [found to cause no root regressions][crater] on `crates.io`.
This change was initially discussed as a [pre-RFC](https://internals.rust-lang.org/t/pre-rfc-adjust-default-object-bounds/2199/). In particular there is much discussion there about the strategy towards breaking changes. Based on the reasoning in my [last comment], I'm …

Adjust default object bounds [breaking change]

---

text/0000-slice-string-symmetry.md

Add some methods that already exist on slices to strings and vice versa. Specifically, the following methods should be added:
- `str::chunks`
- `str::windows`
- `str::into_string`
- `String::into_boxed_slice`
- `<[T]>::subslice_offset`
[Rendered](https://github.com/P1start/rfcs/blob/string-slice-api-symmetry/text/0000-slice-string-symmetry.md)

Add some of `[T]`’s methods to strings and vice versa

---

text/0000-rename-connect-to-join.md

[Kawaii version](https://github.com/barosl/rust-rfcs/blob/rename-connect-to-join/text/0000-rename-connect-to-join.md)
Related Rust issue: rust-lang/rust#24645

Rename connect to join

---

text/0000-slice-tail-redesign.md

[Rendered](https://github.com/kballard/rfcs/blob/a0d4344372279b2ff1f5f025aa65338758613ad1/text/0000-slice-tail-redesign.md).
A PR for this has already been submitted as rust-lang/rust#24184.

RFC for replacing slice::tail()/init() with new methods

---

text/0000-into-raw-fd-socket-handle-traits.md

[Rendered](https://github.com/ipetkov/rfcs/blob/into-raw-trait/text/0000-into-raw-fd-socket-handle-traits.md)

RFC for creation of `IntoRaw{Fd, Socket, Handle}` trait to complement `AsRaw*`

---

text/0000-cap-lints.md

Add a new flag to the compiler, `--cap-lints`, which set the maximum possible
lint level for the entire crate (and cannot be overridden). Cargo will then pass
`--cap-lints allow` to all upstream dependencies when compiling code.
Fixes #1029.
[Rendered](https://github.com/alexcrichton/rfcs/blob/cap-lints/text/0000-cap-lints.md)

RFC: Prevent lint changes being a breaking change

---

text/0000-hir.md

Add a high-level intermediate representation (HIR) to the compiler. This is
basically a new (and additional) AST more suited for use by the compiler.
This is purely an implementation detail of the compiler. It has no effect on the
language.
Note that adding a HIR does not preclude adding a MIR or LIR in the future.

Add a HIR to the compiler

---

text/0000-swap-out-jemalloc.md

Add support to the compiler to override the default allocator, allowing a
different allocator to be used by default in Rust programs. Additionally, also
switch the default allocator for dynamic libraries and static libraries to using
the system malloc instead of jemalloc.
[rendered](https://github.com/alexcrichton/rfcs/blob/less-jemalloc/text/0000-swap-out-jemalloc.md)

RFC: Allow changing the default allocator

---

text/0000-stabilize-no_std.md

Stabilize the `#![no_std]` attribute while also improving the ergonomics of
using libcore by default. Additionally add a new `#![no_core]` attribute to opt
out of linking to libcore.
[rendered](https://github.com/alexcrichton/rfcs/blob/no_std/text/0000-stabilize-no_std.md)

RFC: Stabilize the #![no_std] attribute

---

text/0000-use-group-as.md

Allow aliasing imports when importing as a group.
```rust
use std::io::{
Error as IoError,
Read,
Write
}
```
[Rendered](https://github.com/seanmonstar/rfcs/blob/use-group-as/text/0000-use-group-as.md)
Postponed RFC #867 (See for previous discussion).
Closes #933

use_group_as RFC

---

text/0000-projections-lifetimes-and-wf.md

Type system changes to address the outlives relation with respect to projections, and to better enforce that all types are well-formed (meaning that they respect their declared bounds). The current implementation can be both unsound (rust-lang/rust#24622), inconvenient (rust-lang/rust#23442), and surprising (rust-lang/rust#21748, rust-lang/rust#25692). The changes are as follows:
- Simplify the outlives relation to be syntactically based.
- Specify improved rules for the outlives relation and projections.
- Specify more specifically where WF bounds are enforced, covering several cases missing from the implementation.
The proposed changes here have been tested and found to cause only a modest number of regressions (about two dozen root regressions were previously found on crates.io; …

[RFC] Clarify (and improve) rules for projections and well-formedness 

---

text/0550-macro-future-proofing.md

Accounts for rust-lang/rust#27000
cc @cmr

Update FOLLOW set for `ty` tokens

---

text/0000-cargo-install.md

Add a new subcommand to Cargo, `install`, which will install `[[bin]]`-based
packages onto the local system in a Cargo-specific directory.
[Rendered](https://github.com/alexcrichton/rfcs/blob/cargo-install/text/0000-cargo-install.md)

RFC: Add `cargo install`

---

text/0000-mir.md

This proposal describes a mid-level IR that I believe we should use in the compiler. This is purely an implementation detail and should not affect the language, though it may make many language extensions and analyses easier to implement; the most notable of these is non-lexical lifetimes.
[Rendered.](https://github.com/nikomatsakis/rfcs/blob/mir/text/0000-mir.md)

[RFC] Introduce a mid-level IR (MIR) in the compiler that will drive borrowck, trans

---

text/0000-line-endings.md

This RFC proposes to define a "line" as terminated by either `\n` or \r\n`. Also see <https://github.com/rust-lang/rust/pull/26743>.
[Rendered output](https://github.com/RalfJung/rfcs/blob/line-endings/text/0000-line-endings.md)

RFC: line-endings

---

text/0000-rust-lang-crates.md

This RFC proposes a policy around the crates under the rust-lang github organization that are not part of the Rust distribution (compiler or standard library). At a high level, it proposes that these crates be:
- Governed similarly to the standard library;
- Maintained at a similar level to the standard library, including platform support;
- Carefully curated for quality.
[Rendered](https://github.com/aturon/rfcs/blob/rust-lang-crates/text/0000-rust-lang-crates.md)

RFC: policy for rust-lang crates

---

text/0000-collection-recovery.md
text/0000-set-recovery.md

[Rendered](https://github.com/apasel422/rfcs/blob/collection-recovery/text/0000-set-recovery.md)

RFC: Add item recovery collection APIs

---

text/0000-stabilize-catch-panic.md

Stabilize `std::thread::catch_panic` after removing the `Send` and `'static` bounds from the closure parameter. 
[Rendered](https://github.com/alexcrichton/rfcs/blob/stabilize-catch-panic/text/0000-stabilize-catch-panic.md)

RFC: Stabilize catch_panic

---

text/0000-op-assign.md

[Rendered](https://github.com/japaric/rfcs/blob/op-assign/text/0000-op-assign.md)
[Implementation](https://github.com/rust-lang/rust/pull/23171)
cc @bjz @aturon @nikomatsakis

overloaded assignment operations `a += b`

---

text/0000-raw-pointer-comparisons.md

[Rendered](https://github.com/arielb1/rfcs/blob/raw-pointer-comparisons/text/0000-raw-pointer-comparisons.md)

Implement raw fat pointer comparisons

---

text/0000-compile-time-asserts.md

This RFC has changed course. The original intent is still noted at the bottom of this post.
If the constant evaluator encounters erronous code during the evaluation of
an expression that is not part of a true constant evaluation context a warning
must be emitted and the expression needs to be translated normally.
Currently the compiler errors in some situations like `let x = 5 << 42;` but not in others like `let x = 5 << some_function_returning_42();`
There are three levels of breaking changes (in the order of my preference and severity) that could be applied here:
1. always error when an error is detected at compile-time
2. always warn when an error is detected at compile-time and replace the code by an unconditional panic
3. always warn when an error is detected at compile-time and …

turn statically known erroneous code into a warning and continue normal code-generation

---

text/0982-dst-coercion.md

Otherwise you can't have a `Smaht<T>(*const T, PhantomData<T>)`, which is problematic for drop check, which requires this annotation if Smaht owns the referrent (Box, Rc, Vec, etc..).
See https://github.com/rust-lang/rust/issues/26905 for some discussion.
You could arguably ignore all zero-sized fields, but it's currently hard for the compiler to do so (size is largely a trans notion, to my knowledge). Also maybe you actually want a generic ZST field that has some meaning beyond PhantomData?
A potential workaround to this problem would be `Smaht(*const u8, PhantomData<T>)` but this is entering a fairly degenerate state for the semantics of raw pointers. Although we're already in a bit of a degenerate state in that all Smaht pointers desire some level of mutable access, but are forced to …

specify that CoerceUnsized should ignore PhantomData fields

---

text/0000-simd-infrastructure.md

[Rendered](https://github.com/huonw/rfcs/blob/simd/text/0000-simd-infrastructure.md).

SIMD groundwork

---

README.md
compiler_changes.md
lang_changes.md
libs_changes.md

The libs section was authored by @Gankro, see #1213 and [this discuss thread](https://internals.rust-lang.org/t/the-life-and-death-of-an-api/2087) for previous discussion.
We're currently missing guideline for the tools sub-team. I just didn't have anything to hand, hopefully we can remedy that in a followup PR.

Update the RFC process with sub-teams, amongst other things.

---

text/0560-integer-overflow.md

This is just clarifying things which were agreed on in various places but poorly specified.
[rendered draft](https://github.com/Gankro/rfcs/blob/clarify-math/text/0560-integer-overflow.md)

clarify extreme operator behaviour

---

text/0000-nonparametric-dropck.md

Revise the Drop Check (`dropck`) part of Rust's static analyses in two ways.  In the context of this RFC, these revisions are respectively named `cannot-assume-parametricity` and `unguarded-escape-hatch`.
1. `cannot-assume-parametricity` (CAP): Make `dropck` analysis stop relying on parametricity of type-parameters.
2. `unguarded-escape-hatch` (UGEH): Add an attribute (with some name starting with "unsafe") that a library designer can attach to a `drop` implementation that will allow a destructor to side-step the `dropck`'s constraints (unsafely).
[rendered draft](https://github.com/pnkfelix/rfcs/blob/nonparametric-dropck/text/0000-nonparametric-dropck.md)

Nonparametric dropck

---

text/0000-repr-packed-unsafe-ref.md

[Rendered](https://github.com/huonw/rfcs/blob/repr-packed-unsafe-ref/text/0000-repr-packed-unsafe-ref.md).
cc rust-lang/rust#27060

References into repr(packed) structs should be `unsafe`.

---

text/0000-no-wildcard-deps.md

[Rendered](https://github.com/sfackler/rfcs/blob/no-wildcard-deps/text/0000-no-wildcard-deps.md)

Forbid wildcard dependencies on crates.io

---

text/0000-placement-left-arrow.md

Rather than trying to find a clever syntax for placement-new that leverages
the `in` keyword, instead use the syntax `PLACE_EXPR <- VALUE_EXPR`.
This takes advantage of the fact that `<-` was reserved as a token via
historical accident (that for once worked out in our favor).
[rendered draft](https://github.com/pnkfelix/rfcs/blob/place-left-arrow-syntax/text/0000-placement-left-arrow.md).

Place left arrow syntax (`place <- expr`)

---

text/0911-const-fn.md

Amend #911 const-fn to allow unsafe const functions

---

text/0000-main-reexport.md

[(rendered)](https://github.com/tbu-/rust-rfcs/blob/rfc_main_reexport/text/0000-main-reexport.md)

RFC: Allow a re-export for `main`

---

text/0000-drain-range-2.md

RFC: `.drain(range)` and `.drain()`
Implement `.drain(range)` and `.drain()` respectively as appropriate on collections.
[Rendered](https://github.com/bluss/rfcs/blob/drain-range/text/0000-drain-range-2.md)

RFC: `.drain(range)` and `.drain()`

---

0000-template.md

add link definition for each of the anchored sections.
I always find myself adding these anchors (or some variant thereof) while I'm drafting an RFC.
Lets put them into the template so that people will get them by default.  (Nothing should change about the presentation; it just gives a standard pattern for people to use to embed a link to another section in their markdown.)
(Hopefully we don't need an RFC to decide whether to change the RFC template in this manner.)

add link definition for each of the anchored sections.

---

text/0911-const-fn.md

This commit just reverses the order of `unsafe const` to `const unsafe` to correctly reflect the lang team's decision. See http://github.com/rust-lang/rfcs/issues/1245#issuecomment-146999181

Edit #911 - The order `const unsafe fn` was chosen (rust-lang/rust#29107)

---

text/0000-promote-libc.md

Move the `libc` crate into the `rust-lang` organization after applying changes
such as:
* Remove the internal organization of the crate in favor of just one flat
namespace at the top of the crate.
* Set up a large number of CI builders to verify FFI bindings across many
platforms in an automatic fashion.
* Define the scope of libc in terms of bindings it will provide for each
platform.
[Rendered](https://github.com/alexcrichton/rfcs/blob/pomote-libc/text/0000-promote-libc.md)

RFC: Promote the `libc` crate from the nursery

---

text/0000-osstring-methods.md

[Rendered](https://github.com/eefriedman/rfcs/blob/osstring-simple/text/0000-osstring-methods.md)

Add some additional utility methods to OsString and OsStr

---

text/0000-incremental-compilation.md

High-level strategy for incremental compilation.
cc @rust-lang/compiler 
[Rendered](https://github.com/nikomatsakis/rfcs/blob/incremental-compilation/text/0000-incremental-compilation.md)

Incremental compilation RFC

---

text/0000-intrinsic-semantics.md

Kinda tired of intrinsics causing so much tangential discussion. This makes the current system concrete. If you feel strongly about some other way, please, *please* write an RFC for that way so **it** can be the defined semantics.
[Rendered](https://github.com/Aatch/rust-rfcs/blob/intrinsics/text/0000-intrinsic-semantics.md)

Intrinsic semantics

---

text/0000-deprecation.md

Library authors need a way of evolving their API painlessly. This is it.
[Rendered](https://github.com/llogiq/rfcs/blob/deprecate/text/0000-deprecation.md)

RFC: #[deprecated] for Everyone

---

text/1236-stabilize-catch-panic.md

Instead of a `'static` bound on the function, instead add a new marker trait,
`PanicSafe`, to encapsulate the concept of exception safety as a trait bound
which can be used to serve as a speed bump for users of `panic::recover`.

RFC: Amend `recover` with a `PanicSafe` bound

---

text/0000-global-panic-handler.md

[Rendered](https://github.com/sfackler/rfcs/blob/panic-handlers/text/0000-global-panic-handler.md)

Allow a custom panic handler

---

text/0550-macro-future-proofing.md

Massive redo of Detailed Design of RFC 550; expanded parts of spec in passing.
As noted in the Edit History addition:
* replaced detailed design with a specification-oriented presentation rather than an implementation-oriented algorithm.
* fixed some oversights in the specification that led to matchers like `$e:expr { stuff }` being accepted (which match fragments like `break { stuff }`, significantly limiting future language extensions),
* expanded the follows sets for `ty` to include `OpenDelim(Brace), Ident(where), Or` (since Rust's grammar already requires all of `|foo:TY| {}`, `fn foo() -> TY {}` and `fn foo() -> TY where {}` to work).
* expanded the follow set for `pat` to include `Or` (since Rust's grammar already requires `match (true,false) { PAT | PAT => {} }` and `|PAT| {}` to …

Amend RFC 550 with (expanded) abstract specification rather than algorithm

---

text/0000-grammar-is-canonical.md

[Rendered](https://github.com/nagisa/rfcs/blob/grammar/text/0000-grammar-is-canonical.md)

src/grammar for the canonical grammar of the Rust language

---

text/0131-target-specification.md

The RFC specifies that if RUST_TARGET_PATH is unset then the default is
/etc/rustc but this won't work on all systems (e.g. Windows) and the
Rust compiler never actually implemented this behavior so remove it from
the RFC. closes rust-lang/rust#31117
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>

target spec: remove /etc/rustc as default path

---

text/1192-inclusive-ranges.md

This PR proposes that `RangeInclusive` be an enum with `Empty`/`NonEmpty` variants instead of a struct with a `finished` field:
```rust
pub enum RangeInclusive<T> {
Empty {
at: T,
},
NonEmpty {
start: T,
end: T,
}
}
```
Rational:
1. `finished` is very iterator specific. Regardless of what happens, I think this field should be called `empty`.
2. `start`/`end` don't make sense if the range is empty. Using an enum prevents users from using the `start`/`end` of spent ranges. Basically, this makes it impossible for users to do something like `foo(my_range.take(10)); bar(my_range)` and forget to check `finished` in `bar`.
3. If we ever get more space optimizations (specifically, utf8 code point ones) `'a'...'z'` should be the same size as `'a'..'z'`.
4. Don't have to allocate the next start …

Amend 1192 (RangeInclusive) to use an enum.

---

text/0550-macro-future-proofing.md

Add `[` to the FOLLOW(ty) in macro future-proofing rules (RFC #550 )
This is to address the regression https://github.com/rust-lang/rust/issues/30923

Add `[` to the FOLLOW(ty) in macro future-proofing rules.

---

text/0000-cargo-cfg-dependencies.md

Improve the target-specific dependency experience in Cargo by leveraging the
same `#[cfg]` syntax that Rust has.
[Rendered](https://github.com/alexcrichton/rfcs/blob/cargo-cfg-dependencies/text/0000-cargo-cfg-dependencies.md)

RFC: Improve Cargo target-specific dependencies

---

text/1270-deprecation.md

Change `reason` to `note` and remove `use`.
This isn't a new RFC, just some edits to reflect reality. https://github.com/rust-lang/rust/pull/30206#issuecomment-166721809

Amend RFC 1270 to describe actual implementation

---

text/0000-process-ext-unix.md

Add two methods to the `std::os::unix::process::CommandExt` trait to provide
more control over how processes are spawned on Unix, specifically:
```rust
fn exec(&mut self) -> io::Error;
fn before_exec<F: FnOnce() + Send + Sync + 'static>(&mut self, f: F) -> &mut Self;
```
[Rendered][link]
[link]: https://github.com/alexcrichton/rfcs/blob/process-ext/text/0000-process-ext-unix.md

RFC: Add CommandExt::{exec, before_exec}

---

text/0000-restrict-constants-in-patterns.md

Feature-gate the use of constants in patterns unless those constants have simple types, like integers, booleans, and characters. The semantics of constants in general were never widely discussed and the compiler's current implementation is not broadly agreed upon (though it has many proponents). The intention of adding a feature-gate is to give us time to discuss and settle on the desired semantics in an "affirmative" way.
Because the compiler currently accepts a larger set of constants, this is a backwards incompatible change. This is justified as part of the ["underspecified language semantics" clause of RFC 1122][ls]. A [crater run] found 14 regressions on crates.io, which suggests that the impact of this change on real code would be minimal.
Note: this was also discussed on an …

Restrict constants in patterns

---

active/0000-trait-based-exception-handling.md
active/0049-bounds-on-object-and-generic-types.md

After a detour through thinking about [first-class checked exceptions](https://github.com/glaebhoerl/rust-notes/blob/268266e8fbbbfd91098d3bea784098e918b42322/my_rfcs/Exceptions.txt), I've now circled back around and convinced myself that @aturon's [original idea](https://github.com/rust-lang/rfcs/pull/204) of an `?` operator for propagating exceptions is actually brilliant and the perfect middle path. But I also want `try`..`catch`.
[CLICKME](https://github.com/glaebhoerl/rfcs/blob/trait-based-exception-handling/active/0000-trait-based-exception-handling.md)

Trait-based exception handling

---

text/0000-ide.md

This RFC describes how we intend to modify the compiler to support IDEs. The
intention is that support will be as generic as possible. A follow-up internals
post will describe how we intend to focus our energies and deploy Rust support
in actual IDEs.
There are two sets of technical changes proposed in this RFC: changes to how we
compile, and the creation of an 'oracle' tool (name of tool TBC).
Thanks to Phil Dawes, Bruno Medeiros, Vosen, eddyb, Evgeny Kurbatsky, and Dmitry Jemerov for early feedback.

Rust Language Server (IDE support)

---

text/0000-trim-std-os.md

Deprecate type aliases and structs in `std::os::$platform::raw` in favor of
trait-based accessors which return Rust types rather than the equivalent C type
aliases.

RFC: Deprecate type aliases in std::os::*::raw

---

text/0000-volatile.md

This stabilizes the `volatile_load` and `volatile_store` intrinsics as `ptr::read_volatile` and `ptr::write_volatile`.
[Rendered](https://github.com/Amanieu/rfcs/blob/volatile/text/0000-volatile.md)

Stabilize volatile read and write

---

text/0000-net2-mutators.md

[Rendered](https://github.com/sfackler/rfcs/blob/net2/text/0000-net2-mutators.md)

Move some net2 functionality into libstd

---

text/0000-extended-compare-and-swap.md

[Rendered](https://github.com/Amanieu/rfcs/blob/extended_compare_and_swap/text/0000-extended-compare-and-swap.md)

Extend atomic compare_and_swap

---

text/1461-net2-mutators.md

Issues came up in the implementation of these methods that caused us to
back off from implementing keepalive functionality for now.
r? @alexcrichton

Remove keepalive methods from net2 RFC

---

text/0000-replace-slice.md

Add a `replace_slice` method to `Vec<T>` and `String` removes a range of elements,
and replaces it in place with a given sequence of values.
The new sequence does not necessarily have the same length as the range it replaces.
[Rendered](https://github.com/SimonSapin/rfcs/blob/replace-slice/text/0000-replace-slice.md).

String/Vec::splice(RangeArgument, IntoIterator)

---

text/0000-contains-method-for-ranges.md

[Rendered.](https://github.com/Ticki/rfcs/blob/contains/text/0000-contains-method-for-ranges.md)

'Contains' method for ranges

---

text/0000-unix-socket.md

[Rendered](https://github.com/sfackler/rfcs/blob/unix-socket/text/0000-unix-socket.md)

Unix socket support in the standard library

---

text/0000-ipv6addr-octets.md

Summary: Add constructor and getter functions to `std::net::Ipv6Addr` that are oriented around octets.
[Rendered](https://github.com/AGWA-forks/rust-rfcs/blob/master/text/0000-ipv6addr-octets.md)

Add octet-oriented interface to std::net::Ipv6Addr

---

text/0000-naked-fns.md

[Rendered](https://github.com/tari/rfcs/blob/naked-fns/text/0000-naked-fns.md).

Add support for naked functions.

---

text/0000-pub-restricted.md

Expand the current `pub`/non-`pub` categorization of items with the ability to say "make this item visible *solely* to a (named) module tree."
The current `crate` is one such tree, and would be expressed via: `pub(crate) item`. Other trees can be denoted via a path employed in a `use` statement, e.g. `pub(a::b) item`, or `pub(super) item`.
[rendered](https://github.com/pnkfelix/rfcs/blob/pub-restricted/text/0000-pub-restricted.md)

pub(restricted) item

---

text/1291-promote-libc.md

The initial motivation for adding this library is to get access to
`openpty(3)` and `forkpty(3)`. These simplify opening a pseudoterminal
master / slave pair. The functions are defined on Linux, OSX, FreeBSD,
NetBSD, and OpenBSD. On OS X, they are available without linking to any
additionaly libraries; on the other platforms they require linking with
`-lutil`.
On Linux, libutil is part of glibc, and defines 6 symbols:
- forkpty
- logwtmp
- login_tty
- openpty
- login
- logout
libutil is available in the base installs of Debian-, Fedora-, and
Arch-derived distributions, as well as openSUSE and Android, though on
Android the `pty.h` header that declares the functions seems not to be
available.  Together, these cover the DistroWatch [0] top 10
distributions.
In musl libc, `openpty(3)` and …

rfc 1291: Add libutil to scope of libc crate on Linux

---

text/0000-contains-method-for-various-collections.md

Summary: add a `contains` method to `VecDeque` and `LinkedList` that checks if the collection contains a given item.
[Rendered](https://github.com/LukasKalbertodt/rfcs/blob/rfc-contains-method-for-various-collections/text/0000-contains-method-for-various-collections.md)

Add a contains method to VecDeque and LinkedList

---

text/0230-remove-runtime.md

Fix typo in 0230-remove-runtime.md

---

text/0550-macro-future-proofing.md

RFC 550 introduced follow sets for future-proofing macro definitions. They have been tweaked since then to reflect the realities of extant Rust syntax, or to bail out crates that were too-big-to-fail.
The idea (insofar as I understand it) is that the follow set for a fragment specifier `X` contains any tokens or symbols that could follow a complete `X` in current (or planned) valid Rust syntax. In particular, `FOLLOW(X)` does _not_ contain anything that could be part of `X` (silly example: `+` is not in `FOLLOW(expr)` because obviously `+` may be in the middle of an expression). A macro may not specify syntax that has an `X` followed by something not in `FOLLOW(X)`. That way, if in the future we extend Rust syntax so that `X` can encompass more things (that were previously not in the …

Amend RFC 550 with misc. follow set corrections

---

text/0000-less-unwinding.md

* Stabilize the `-Z no-landing-pads` flag under the name `-C panic=val`
* Implement a number of unstable features akin to custom allocators to swap out
implementations of panic just before a final product is generated.
* Add a `[profile.dev]` option to Cargo to disable unwinding.
[Rendered](https://github.com/alexcrichton/rfcs/blob/less-unwinding/text/0000-less-unwinding.md)

RFC: Stabilize implementing panics as aborts

---

text/0000-kinds-of-allocators.md

----
Add a standard allocator interface and support for user-defined allocators, with the following goals:
1. Allow libraries (in libstd and elsewhere) to be generic with  respect to the particular allocator, to support distinct,  stateful, per-container allocators.
2. Require clients to supply metadata (such as block size and  alignment) at the allocation and deallocation sites, to ensure hot-paths are as efficient as possible.
3. Provide high-level abstraction over the layout of an object in memory.
Regarding GC: We plan to allow future allocators to integrate themselves with a standardized reflective GC interface, but leave specification of such integration for a later RFC. (The design describes a way to add such a feature in the future while ensuring that clients do not accidentally …

Allocators, take III

---

text/0000-integer_atomics.md

Previous RFC: #1505
Relevant issues: #1125 rust-lang/rust#24564
[Relevant discussion in internals](https://internals.rust-lang.org/t/pre-rfc-extended-atomic-types/3068)
[Rendered](https://github.com/Amanieu/rfcs/blob/more_atomic_types/text/0000-integer_atomics.md)

Add more integer atomic types

---

text/0000-rdylib.md

Add a new crate type accepted by the compiler, called `rdylib`, which
corresponds to the behavior of `-C prefer-dynamic` plus `--crate-type dylib`.
[Rendered](https://github.com/alexcrichton/rfcs/blob/rdylib/text/0000-rdylib.md)

RFC: Add a new crate-type, rdylib

---

text/0000-drop-types-in-const.md

This addresses #913 and rust-lang/rust#30667
[rendered](https://github.com/thepowersgang/rust-lang_rfcs/blob/drop-types-in-const/text/0000-drop-types-in-const.md)

RFC - Allow Drop types in statics/const functions

---

text/0000-repr-pack.md

[Rendered](https://github.com/retep998/rfcs/blob/optimal-rabbit-packing/text/0000-repr-pack.md)

RFC: Add #[repr(pack = "N")]

---

text/1228-placement-left-arrow.md

https://github.com/rust-lang/rfcs/pull/1228 left a pretty bikesheddable and important question unanswered: the fixity of the proposed operator.
Associativity is a no-brainer; precedence needs to be decided on.

Amend RFC1228 with operator fixity and precedence

---

text/0000-cargo-workspace.md

Improve Cargo's story around multi-crate single-repo project management by
introducing the concept of workspaces. All packages in a workspace will share
`Cargo.lock` and an output directory for artifacts.
Cargo will infer workspaces where possible, but it will also have knobs for
explicitly controlling what crates belong to which workspace.
[Rendered](https://github.com/alexcrichton/rfcs/blob/cargo-workspace/text/0000-cargo-workspace.md)

RFC: Add workspaces to Cargo

---

text/0000-copy-clone-semantics.md

Specifying that `<T as Clone>::clone(&t)` where `T: Copy` should be equivalent to `ptr::read(&t)`.

Copy clone semantics

---

text/0000-try-from.md

[Rendered](https://github.com/sfackler/rfcs/blob/try-from/text/0000-try-from.md)

Add TryFrom and TryInto traits

---

text/1525-cargo-workspace.md

Currently, it is not clear if the 'root' is a file or directory, and so the meaning of "the `target` directory next to the root" is ambiguous.
Note that 'root crate' is not new words, it appeared in the origianl RFC text.

clarify 'root' with 'root crate' or 'root `Cargo.toml`'

---

text/0000-repr-align.md

Extend the existing `#[repr]` attribute on structs with an `align = "N"` option
to specify a custom alignment for `struct` types.
[Rendered][link]
[link]: https://github.com/alexcrichton/rfcs/blob/repr-align/text/0000-repr-align.md

RFC: Add #[repr(align = "N")]

---

text/0000-dotdot-in-patterns.md

Permit the `..` pattern fragment in more contexts.
[Rendered](https://github.com/petrochenkov/rfcs/blob/patdotdot/text/0000-dotdot-in-patterns.md)

RFC: `..` in patterns

---

text/1214-projections-lifetimes-and-wf.md

This oversight was found while working on rust-lang/rust#33138.
Tuples with an unsized field in the middle can't possibly work. Tuples with an unsized field at the end should work after we refactor `trans::adt`.

all but the last field of a tuple must be Sized

---

text/1201-naked-fns.md

The example in #1201 never got updated to reflect all of the restrictions on naked functions. This change makes the example compile on a current compiler.

Correct example in 1201

---

text/0000-macro-lifetimes.md

[Rendered](https://github.com/sgrif/rfcs/blob/sg-macro-lifetimes/text/0000-macro-lifetimes.md)

Add a `lifetime` specifier to `macro_rules!`

---

text/0000-ergonomic-format-args.md

[Rendered](https://github.com/xen0n/rfcs/blob/ergonomic-format-macro/text/0000-ergonomic-format-args.md).
This describes rust-lang/rust#33642 (minus the TODO bits of course). Hopefully the distinction of *macro arguments*, *placeholders* and *generated argument objects* is made clear...
*Note: My native language is not English, so although I've already proofread the draft please do note any English-related issues as well for minimizing confusion.*

Ergonomic format_args!

---

text/0000-default-and-expanded-rustc-errors.md
text/0000-rust-new-error-format.md

Proposed update to the Rust compiler error output format.
[rendered](https://github.com/jonathandturner/rfcs/blob/master/text/0000-default-and-expanded-rustc-errors.md) (last updated: 6/27/2016 8:30am)

Default and expanded errors for rustc

---

text/0000-attributes-with-literals.md

I'd like to allow all types of literals to appear in attributes at both top-level positions in lists and as values in k/v pairs. This would, for example, make the following syntax valid:
```rust
#[attr(ident, ident = 100, "hi", ident = "hello", ident(100))]
#[attr(100)]
#[attr("hello")]
#[repr(C, align = 4)]
#[repr(C, align(4))]
```
[Rendered](https://github.com/SergioBenitez/rfcs/blob/master/text/0000-attributes-with-literals.md)

RFC: Allow all literals in attributes

---

text/1268-allow-overlapping-impls-on-marker-traits.md

This RFC was written at a time where the specialization RFC appeared to include the lattice rule. Since the RFC was accepted without it, this RFC implies that it is superseded by specialization, but it is not.

Update the alternative section for #1268

---

text/0000-assert_ne.md

this is an rfc to add a `assert_ne` macro to compliment `assert_eq`. it exists as a crate: https://crates.io/crates/assert_ne.

propose assert_ne

---

text/0000-int128.md

Relevant issue: #521
[Rendered](https://github.com/Amanieu/rfcs/blob/int128/text/0000-int128.md)

Add support for 128-bit integers

---

text/0000-name-resolution.md

Some internal and language-level changes to name resolution.
Internally, name resolution will be split into two parts - import resolution and
name lookup. Import resolution is moved forward in time to happen in the same
phase as parsing and macro expansion. Name lookup remains where name resolution
currently takes place (that may change in the future, but is outside the scope
of this RFC). However, name lookup can be done earlier if required (importantly
it can be done during macro expansion to allow using the module system for
macros, also outside the scope of this RFC). Import resolution will use a new
algorithm.
The observable effects of this RFC (i.e., language changes) are some increased
flexibility in the name resolution rules, especially around globs and shadowing. …

Changes to name resolution

---

text/1444-union.md

Discussion in the [tracking issue for unions](https://github.com/rust-lang/rust/issues/32836) turned up a corner case not addressed by RFC1444: whether assigning to a union field that implements `Drop` should drop the previous value of the field.  Based on that discussion, document that such an assignment does drop the previous value of the field.  Also document how to work around that if needed, and add a note that the lint warning for declaring a union field with a type implementing `Drop` should explicitly document this issue in its explanation.

Clarify behviour when writing to a union field that implements Drop

---

text/0000-bang-type.md

Promote `!` to be a full-fledged type equivalent to an `enum` with no variants.
[Rendered](https://github.com/canndrew/rfcs/blob/bang_type/text/0000-bang-type.md)

Promote `!` to a type.

---

text/0000-docs-team.md
text/1683-docs-team.md

This RFC proposes creating a new subteam for docs.
[Rendered](https://github.com/steveklabnik/rfcs/blob/15e41ada1d7cbc791f99a56958f8146d6cde2696/text/0000-docs-team.md).
r? @rust-lang/core

Propose the docs team

---

text/0000-fused-iterator.md

This RFC adds a `FusedIterator` marker trait and specializes `iter::Fuse` to do
nothing when the underlying iterator already provides the `Fuse` guarantee.
See [this](https://internals.rust-lang.org/t/pre-rfc-iter-fused-trait/2278) discussion for context.
[rendered](https://github.com/Stebalien/rfcs/blob/fused/text/0000-fused-iterator.md)
[WIP PR](https://github.com/rust-lang/rust/pull/32999)
/cc @bluss, @Gankro

`FusedIterator` marker trait and `iter::Fuse` specialization

---

text/0000-atomic-access.md

This RFC adds the following methods to atomic types:
- `get_mut`
- `into_inner`
- `as_raw`
- `from_raw`
[Rendered](https://github.com/Amanieu/rfcs/blob/atomic_access/text/0000-atomic-access.md)

Add extra access methods for atomic types

---

text/0000-macros-literal-matcher.md

Add a `literal` fragment specifier for `macro_rules!` patterns that matches literal constants.

Add a `literal` fragment specifier to `macro_rules!`.

---

text/0000-adt-kinds.md

Provide a simple model describing three kinds of structs and variants and their relationships + some small language extensions following from this model.
[Rendered](https://github.com/petrochenkov/rfcs/blob/adtkinds/text/0000-adt-kinds.md)
cc https://github.com/rust-lang/rust/pull/31757#issuecomment-186398640

Clarify the relationships between various kinds of structs and variants

---

text/0000-style-rfcs.md

This RFC proposes a process for deciding detailed guidelines for code
formatting, and default settings for Rustfmt. The outcome of the process should
be an approved formatting style defined by a style guide and enforced by
Rustfmt.

RFC process for formatting style and Rustfmt defaults

---

text/0000-memory-model-strike-team.md

Incorporate a strike team dedicated to preparing rules and guidelines for writing unsafe code in Rust (commonly referred to as Rust's "memory model"), in cooperation with the lang team. The discussion will generally proceed in phases, starting with establishing high-level principles and gradually getting down to the nitty gritty details (though some back and forth is expected). The strike team will produce various intermediate documents that will be submitted as normal RFCs.

Dedicated strike team to resolve unsafe code guidelines

---

text/0000-panic-safe-slicing.md

This is #1325 with the changes discussed at the bottom of that comment chain applied.

Add panic-safe indexing methods round 2

---

text/0000-duration-checked-sub.md

This would as described in the RFC add the method `Duration::checked_sub()` and as an unresolved question if a few other, similar methods should be added.

add: duration_checked_sub RFC

---

text/0000-rustc-bug-fix-procedure.md

Defines a "best practices" procedure for making bug fixes or soundness corrections in the compiler that can cause existing code to stop compiling.
[Rendered view.](https://github.com/nikomatsakis/rfcs/blob/breaking-change-policy/text/0000-rustc-bug-fix-procedure.md)

Best practices for bug fixes in the compiler

---

text/0738-variance.md

Per https://github.com/rust-lang/rfcs/pull/738#discussion_r23849477
I'm a little unsure though since this hasn't been fixed for so long?

Fix typo in fn variance

---

text/0000-macro-naming.md

This RFC proposes making macros a first-class citizen in the Rust module system.
Both macros by example (`macro_rules` macros) and procedural macros (aka syntax
extensions) would use the same naming and modularisation scheme as other items
in Rust.
[rendered](https://github.com/nrc/rfcs/blob/macro-naming/text/0000-macro-naming.md)

Macro naming and modularisation

---

text/0000-static.md

Adding `'static` lifetimes to every reference or generics lifetime value in `static` or `const` declarations adds no value. So this PR suggests we allow to omit them. 
[Rendered](https://github.com/llogiq/rfcs/blob/static_statics/text/0000-static.md)

new RFC: static_lifetime_in_statics

---

text/0000-macros-1.1.md

Extract a very small sliver of today's procedural macro system in the compiler,
just enough to get basic features like custom derive working, to have an
eventually stable API. Ensure that these features will not pose a maintenance
burden on the compiler but also don't try to provide enough features for the
"perfect macro system" at the same time. Overall, this should be considered an
incremental step towards an official "plugins 2.0".
[Rendered](https://github.com/alexcrichton/rfcs/blob/macros-1.1/text/0000-macros-1.1.md)

RFC: Procedural macros 1.1

---

text/1581-fused-iterator.md

1. We can't remove the `done` bool without making `Fuse` invariant.
2. One drawback I failed to mention is that implementing `FusedIterator` locks implementors into obeying the `FusedIterator` spec.

Update unresolved questions and drawbacks for the FusedIterator RFC

---

text/1607-style-rfcs.md

Fixes my mistake from #1741. This also renders more obviously as a separate quotation.
r? @eddyb

Block quote the entire style guideline example.

---

text/0000-discriminant.md

The `discriminant_value` intrinsic won't be stabilized anytime soon in its current form because it leaks too much memory layout information. The wrapper proposed here returns an opaque newtype to allow for information hiding.
cc rust-lang/rust#24263 rust-lang/rust#34785 @ubsan @sfackler 
[Rendered](https://github.com/durka/rfcs/blob/patch-6/text/0000-discriminant.md)

mem::discriminant()

---

text/1696-discriminant.md

During discussion we decided to remove the Reflect bound, and I removed it from one part of the text but not another. Further discussion ensued, but we never decided to put Reflect back in.

fix typo in RFC 1696

---

text/0000-loop-break-value.md

This is the culmination of recent discussion in issue #961, minus discussion about extensions to for/while/while let (for which there is no clear solution).

loop-break-value (issue #961)

---

text/0000-dllimport.md

Make compiler aware of the association between library names adorning `extern` blocks and symbols defined within the block.  Add attributes and command line switches that leverage this association.
(based on [RFC1296](https://github.com/rust-lang/rfcs/pull/1296), minus the dllexport bits)
[Rendered](https://github.com/vadimcn/rfcs/blob/dllimport/text/0000-dllimport.md)

Use #[link(kind)] to fix imports from native libs on Windows

---

text/0000-windows-subsystem.md

[Rendered](https://github.com/Diggsey/rfcs/blob/windows-subsystem/text/0000-windows-subsystem.md)

Windows subsystem support

---

text/1665-windows-subsystem.md

Throw in some proper noun and minor typo fixes as well.

Differentiate between the different uses of "windows"

---

text/0738-variance.md

Followup based on https://github.com/rust-lang/rfcs/pull/1716#issuecomment-240280040
Sorry, I was going to add this in the first PR, but wanted feedback first - the merging was more eager than I expected!
I've left in "This is very unusual in Rust but it can happen." because I don't know if 'This' is meant to refer to a) lifetimes in function arguments, or b) the desire to make them longer.
ping @nikomatsakis

Lifetimes in arguments may be made longer

---

text/0000-north-star.md

A refinement of the Rust planning and reporting process, to establish a shared
vision of the project among contributors, to make clear the roadmap toward that
vision, and to celebrate our achievements.
The primary outcome for these changes to the process are that we will have a
consistent way to:
- Decide our project-wide goals through consensus.
- Advertise our goals as a published roadmap.
- Celebrate our achievements with an informative publicity-bomb.
[Rendered](https://github.com/brson/rfcs/blob/north-star/text/0000-north-star.md).

A process for establishing the Rust roadmap

---

text/0000-unaligned-access.md

[Rendered](https://github.com/Amanieu/rfcs/blob/unaligned/text/0000-unaligned-access.md)

Add ptr::{read,write}_unaligned

---

text/0000-document_all_features.md

[Rendered](https://github.com/chriskrycho/rfcs/blob/document_all_features/text/0000-document_all_features.md)
Note: I used `#[deprecated]` as an example in this... and I [submitted a PR to update it](https://github.com/rust-lang/rust/pull/34070) right after I submitted this PR.

RFC: Require documentation for all new features.

---

0000-template.md

You have taken your first step into a larger world (of new features—and some old ones—being documented)!
Implements the required change to the RFC template per #1636.

Add 'How We Teach This' to template, per RFC 1636.

---

text/0000-proc-macros.md

This RFC proposes an evolution of Rust's procedural macro system (aka syntax
extensions, aka compiler plugins). This RFC specifies syntax for the definition
of procedural macros, a high-level view of their implementation in the compiler,
and outlines how they interact with the compilation process.
At the highest level, macros are defined by implementing functions marked with
a `#[macro]` attribute. Macros operate on a list of tokens provided by the
compiler and return a list of tokens that the macro use is replaced by. We
provide low-level facilities for operating on these tokens. Higher level
facilities (e.g., for parsing tokens to an AST) should exist as library crates.

Procedural macros

---

text/0195-associated-items.md

Removes some text that appears to be copied from the RFC template that should not have made it in the final RFC text.

Trivial - RFC 0195 Associated Items - remove text copied from RFC template

---

text/1636-document_all_features.md

I thought I'd caught them all, but apparently NOPE.
This fix is for you, @brson. 😀

Remove last core-team reference from 1636

---

text/0000-roadmap-2017.md

This RFC proposes the *2017 Rust Roadmap*, in accordance with [RFC 1728](https://github.com/rust-lang/rfcs/pull/1728). The goal of the roadmap is to lay out a vision for where the Rust project should be in a year's time. **This year's focus is improving Rust's *productivity*, while retaining its emphasis on fast, reliable code**. At a high level, by the end of 2017:
* Rust should have a lower learning curve
* Rust should have a pleasant edit-compile-debug cycle
* Rust should provide a solid, but basic IDE experience
* Rust should provide easy access to high quality crates
* Rust should be well-equipped for writing robust, high-scale servers
* Rust should have 1.0-level crates for essential tasks
* Rust should integrate easily into large build systems
* Rust's community should provide …

RFC: Roadmap for 2017

---

text/0000-allow-self-in-where-clauses.md

[Rendered](https://github.com/sgrif/rfcs/blob/sg-self-in-where-clauses/text/0000-allow-self-in-where-clauses.md)

Allow `Self` to appear in the where clause of trait impls

---

text/0000-rvalue_static_promotion.md

Promote constexpr rvalues to values in static memory instead of stack slots, and expose those in the language by being able to directly create `'static` references to them. 
This would allow code like `let x: &'static u32 = &42` to work.
[Rendered](https://github.com/Kimundi/rfcs/blob/rvalue_static_promotion/text/0000-rvalue_static_promotion.md)
Credit for idea and impl goes to @nikomatsakis and @eddyb ;)
Closes https://github.com/rust-lang/rfcs/issues/827

Add Rvalue-static-promotion RFC

---

text/0000-movecell.md

This RFC extends the `Cell` type to work with non-`Copy` types.
[Rendered](https://github.com/Amanieu/rfcs/blob/movecell/text/0000-movecell.md)

Extend Cell to non-Copy types

---

text/0000-macros.md

Macros by example 2.0. A replacement for `macro_rules!`. This is mostly a
placeholder RFC since many of the issues affecting the new macro system are
(or will be) addressed in other RFCs. This RFC may be expanded at a later date.

Macros by example 2.0 (macro!)

---

text/1584-macros.md

L102: Nomencalture -> Nomenclature
L111: alterantive -> alternative

Corrected some spelling errors.

---

text/0000-rust-bookshelf.md

[rendered](https://github.com/steveklabnik/rfcs/blob/b616749961b61a14b3a65ee2e79618dcd00a13dc/text/0000-rust-bookshelf.md)
Create a "Rust Bookshelf" of learning resources for Rust.
* Pull the book out of tree into rust-lang/book, which holds the second edition, currently.
* Pull the nomicon and the reference out of tree and convert them to mdBook.
* Pull the cargo docs out of tree and convert them to mdBook.
* Create a new "Nightly Book" in-tree.
* Provide a path forward for more long-form documentation to be maintained by the project.
/cc @rust-lang/core, @rust-lang/docs , @brson

Rust bookshelf

---

text/0000-closure-to-fn-coercion.md
text/0401-coercions.md

[Rendered](https://github.com/archshift/rfcs/blob/closure-to-fn-coercion/text/0000-closure-to-fn-coercion.md)
Closes #1555.

RFC: Allow coercing non-capturing closures to function pointers.

---

README.md

Under the heading "What the process is" a word was duplicated assumingly by
accident:
> "The sub-team will will either close"
... the above should probably be:
> "The sub-team will either close"

Remove duplicate word from documentation

---

README.md

There was an inconsistent use of "PR" and "pull request" throughout the
document. I believe that I read an article from GitHub that they suggested
the use of "pull request" instead of "PR" for the purposes of clarity.

Change PR to pull request

---

text/0000-eprintln.md

Continuing discussion from https://internals.rust-lang.org/t/extremely-pre-rfc-eprintln/4635/7 and https://github.com/rust-lang/rust/pull/39229.

RFC: add `eprint(ln)!`

---

text/0000-unstable-sort.md

Every other systems programming language has a fast, non-allocating, unstable sort in standard library. Rust still doesn't. This is a proposal to add one to libcore.
The proposed implementation is **very fast**, faster than `std::slice::sort` and `std::sort` in C++ by a wide margin.
This topic was discussed before in the issue #790
[Rendered](https://github.com/stjepang/rfcs/blob/unstable-sort/text/0000-unstable-sort.md)

Add unstable sort to libcore

---

text/0000-manually-drop.md

[Rendered](https://github.com/nagisa/rfcs/blob/manually-drop/text/0000-manually-drop.md)

Manually Drop

---

text/0000-add-error-macro.md

[Rendered](https://github.com/sgrif/rfcs/blob/sg-add-error-macro/text/0000-add-error-macro.md)

Add a `compile_error!` macro to libstd

---

text/0560-integer-overflow.md

Compare the third bullet point (shift operations) under
- (original) https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md#arithmetic-operations-with-error-conditions
- (new) https://github.com/aidanhs/rfcs/blob/aphs-fix-integer-overflow-markdown/text/0560-integer-overflow.md#arithmetic-operations-with-error-conditions

Shuffle around text to avoid > at beginning of line (block quote)

---

README.md

I expected a week to mean 7 calendar days, but rfcbot thinks it's 10
calendar days :)
https://github.com/dikaiosune/rust-dashboard/blob/dae280e5baf2174daa2bcb8197d00201d4071bd5/src/github/nag.rs#L299-L300

Clarify what rfcbot thinks a week is

---

text/0000-portability-lint.md

There has long been a desire to expand the number of platform- and architecture-specific APIs in the standard library, and to offer subsets of the standard library for working in constrained environments. At the same time, we want to retain the property that Rust code is portable by default.
This RFC proposes a new *portability lint*, which threads the needle between these two desires. The lint piggybacks on the existing `cfg` system, so that using APIs involving `cfg` will generate a warning unless there is explicit acknowledgment of the portability implications.
The lint is intended to make the existing `std::os` module obsolete, to allow expansion (and subsetting) of the standard library, and to provide deeper checking for portability across the ecosystem. …

RFC: A portability lint

---

README.md

- Use, and indentation, of markdown lists
- Line-length wrapping
- Named links
- Replace single-quote for double-quote
- Replace smart-quote for double-quote
- Remove inappropriate apostrophes indicating possessives
- Replace underscore with asterisk for italics
- Content reorder (#sub-team-specific-guidelines)
+ Linked in (#the-rfc-life-cycle)
- Replace repo with repository

Change formatting and markdown usage consistency

---

text/0000-deprecate-anonymous-parameters.md

[Rendered](https://github.com/matklad/rfcs/blob/anon-params/text/0000-deprecate-anonymous-parameters.md)
Issue: #1351

Deprecate anonymous parameters

---

text/0002-rfc-process.md

The mozilla/rust repository is a redirect to rust-lang and rust-lang has no wiki.  The best link I could find for the core team was on www.rust-lang.org

Broken links for core team

---

text/1192-inclusive-ranges.md

Rationale overview:
1. Having the variants make trying to use a RangeInclusive unergonomic.
For example, `fn clamp(self, range: RangeInclusive<Self>)` is forced
to deal with the `Empty` case.
2. The variants don't actually provide any offsetting safety or additional
performance, since everything is pub so it's totally possible for a
"`NonEmpty`" range to contain no elements.
3. This makes it more consistent with (half-open) `Range`.
4. The extra flag/variant is not actually needed in order to make it
iterable, even using the existing Step trait.  And supposing a more
cut-down trait, generating `a, b` such that `!(a <= b)` is easier
than other fundamental requirements of safe range iterability.
Posting this here after discussion on the inclusive ranges tracking issue: …

Make RangeInclusive just a two-field struct (amend 1192)

---

text/0000-expand-impl-trait.md
text/1951-expand-impl-trait.md

This RFC proposes several steps forward for `impl Trait`:
- Settling on a particular syntax design, resolving questions around the
`some`/`any` proposal and others.
- Resolving questions around which type and lifetime parameters are considered
in scope for an `impl Trait`.
- Adding `impl Trait` to argument position (where it is understood as anonymous, bounded generics)
The first two proposals, in particular, put us into a position to stabilize the
current version of the feature in the near future.
[Rendered](https://github.com/aturon/rfcs/blob/expand-impl-trait/text/0000-expand-impl-trait.md)

RFC: Finalize syntax and parameter scoping for `impl Trait`, while expanding it to arguments

---

text/0000-try-trait.md

Introduce a trait `Try` for customizing the behavior of the `?` operator when applied to types other than `Result`.
Fixes #1718.
Rendered: https://github.com/nikomatsakis/rfcs/blob/try-trait/text/0000-try-trait.md

extend `?` to operate over other types

---

text/1624-loop-break-value.md

I'm fairly certain the desire is to not require anything unbounded.

Fix a typo about desiring unbounded lookahead.

---

text/0000-match-ergonomics.md

[Rendered.](https://github.com/cramertj/rfcs/blob/match-ergo-take-2/text/0000-match-ergonomics.md)

Match Ergonomics Using Default Binding Modes

---

text/0000-global-allocators.md

[Rendered](https://github.com/sfackler/rfcs/blob/allocators-2/text/0000-global-allocators.md)

Prepare global allocators for stabilization

---

text/0000-stabilize-drop-order.md
text/1857-stabilize-drop-order.md

[Rendered](https://github.com/aochagavia/rfcs/blob/drop/text/0000-stabilize-drop-order.md)

Stabilize drop order

---

text/0000-tiered-browser-support.md
text/1985-tiered-browser-support.md

[Rendered!](https://github.com/integer32llc/rfcs/blob/tiered-browser-support/text/0000-tiered-browser-support.md)

Tiered browser support policy for Rust's web content

---

text/0000-repr-transparent.md
text/1758-repr-transparent.md

Summary: Extend the existing `#[repr]` attribute on newtypes with a `transparent` option
specifying that the type representation is the representation of its only field.
This matters in FFI context where `struct Foo(T)` might not behave the same
as `T`.
Cc @eddyb @Manishearth 
[rendered](https://github.com/rust-lang/rfcs/pull/1758/files?short_path=01fbc76)
#

Specify #[repr(transparent)]

---

text/0000-as-cell.md
text/1789-as-cell.md

A proposal about legitimizing the cast of a `&mut T` to a `&Cell<T>`.
[Rendered](https://github.com/Kimundi/rfcs/blob/as-cell/text/0000-as-cell.md)

Conversions from `&mut T` to `&Cell<T>`

---

text/0000-experimental-coroutines.md
text/2033-experimental-coroutines.md

This is an **experimental RFC** for adding a new feature to the language,
coroutines (also commonly referred to as generators). This RFC is intended to be
relatively lightweight and bikeshed free as it will be followed by a separate
RFC in the future for stabilization of this language feature. The intention here
is to make sure everyone's on board with the *general idea* of
coroutines/generators being added to the Rust compiler and available for use on
the nightly channel.
[Rendered](https://github.com/alexcrichton/rfcs/blob/experimental-coroutines/text/0000-experimental-coroutines.md)
[What's a experimental RFC?](https://github.com/rust-lang/rfcs/pull/2033#issuecomment-309057591)

eRFC: Experimentally add coroutines to Rust

---

text/0000-cargo-prepublish.md
text/1860-manually-drop.md

This RFC proposes the concept of *prepublication dependencies* for Cargo. These dependencies augment a crate index (like crates.io) with new versions of crates that have not yet been published to the index. Dependency resolution then works *as if* those prepublished versions actually existed in the index. Prepublication dependencies thus act as a kind of "staging index".
Prepublication makes it possible to perform integration testing within a large crate graph before publishing anything to crates.io, and without requiring dependencies to be switched from the crates.io index to git branches. It can, to a degree, simulate an "atomic" change across a large number of crates and repositories, which can then actually be landed in a piecemeal, non-atomic fashion. …

RFC for prepublication dependencies

---

text/1574-more-api-documentation-conventions.md

Some fields were unintentionally left blank

Fill in some blanks in RFC 1574 header

---

text/1183-swap-out-jemalloc.md
text/1398-kinds-of-allocators.md

Add link connecting the old "swap-out-jemalloc" RFC to the new global allocator RFC.
As a drive-by, point out in the Allocator trait RFC that the actual API changed over development.

Cross refs for allocator APIs

---

text/0000-ques-in-main.md
text/1937-ques-in-main.md

[Rendered](https://github.com/zackw/rust-rfcs/blob/ques-in-main/text/0000-ques-in-main.md).
Would resolve #1176. [Pre-RFC discussion](https://internals.rust-lang.org/t/rfc-mentoring-opportunity-permit-in-main/4600).  See also #1718, #1859, and [the internals thread about main returning `!`](https://internals.rust-lang.org/t/allowing-for-main-to-be-divergent-in-embedded-environments/4717).

RFC: `?` in `main`

---

text/0000-license-rfcs.md
text/2044-license-rfcs.md

[Rendered](https://github.com/est31/rfcs/blob/master/text/0000-license-rfcs.md)
Fixes #1259

RFC to put the RFCs repo under license terms

---

text/0000-extern-types.md
text/1861-extern-types.md

Add `extern type` declarations for declaring types from external libraries which have an unknown size/layout.
[Rendered](https://github.com/canndrew/rfcs/blob/extern-types/text/0000-extern-types.md)

extern types

---

text/1440-drop-types-in-const.md

At present, #1440 does not allow `const` items to contain drop types. This leads to somewhat surprising behavior, as illustrated in the following example:
```rust
#![feature(associated_consts)]
#![feature(const_fn)]
#![feature(drop_types_in_const)]
pub struct Test(Option<Vec<()>>);
impl Test {
pub const fn new() -> Test {
Test(None)
}
}
pub const WORKS: Test = Test(None);
pub const FAILS: Test = Test::new();
fn main() { }
```
In the code above, `WORKS` typechecks while `FAILS` does not, even though they may appear to be identical to the user. The check fails because the compiler treats `Test` as an opaque type returned from `Test::new()`; because `Test` contains a `Vec`, the type may `drop`, and so the `const` item is rejected under the current RFC. This PR changes the semantics to allow …

Amend #1440: allow `const` items to contain drop types.

---

text/0000-object_safe_for_dispatch.md
text/2027-object_safe_for_dispatch.md

[Rendered](https://github.com/withoutboats/rfcs/blob/object-safe-for-dispatch/text/0000-object_safe_for_dispatch.md)

Tweak object safety rules to allow static dispatch

---

text/0000-refcell-replace.md

[Rendered](https://github.com/notriddle/rust-rfcs/blob/refcell_replace/text/0000-refcell-replace.md)

Add replace and swap functions to RefCell

---

0000-template.md

r? @aturon 
Switch to "Guide-level" and "Reference-level" explanations
As proposed by aturon <3
These sections replace the "Detailed design" and "How do we teach this?"
sections, and switch their order.
Instead of describing how we would teach a change as a result of a
proposal, the "Guide-level explanation" section will actually attempt to
teach the reader the feature, in a lightweight way.
The guide-level explanation appears first in order to help RFC writers
keep Rust users in the front of their minds, and in order to help RFC
readers understand how an RFC will affect them sooner in the RFC. This
will hopefully make the RFC process more accessible to people who are
Rust users but not compiler or language design experts.

"Guide-level" and "Reference-level" explanations to replace how we teach and detailed design sections

---

LICENSE-APACHE
LICENSE-MIT
README.md
text/2044-license-rfcs.md

Also, add LICENSE-MIT and LICENSE-APACHE files to the repo.

Add note of the RFC 2044 licensing process to README and update template

---

text/0000-unsafe-pointer-reform.md

Copy most of the static `ptr::` functions to methods on unsafe pointers themselves.
Also add a few conveniences for `ptr.offset` with unsigned integers.
```rust
// So this:
ptr::read(self.ptr.offset(idx as isize))
// Becomes this:
self.ptr.add(idx).read()
```
More conveniences should probably be added to unsafe pointers, but this proposal is basically the "minimally controversial" conveniences.
[Rendered](https://github.com/Gankro/rfcs/blob/sharpie/text/0000-unsafe-pointer-reform.md)

Unsafe Pointer Methods

---

text/0000-nursery-deprecation.md
text/1242-rust-lang-crates.md
text/1983-nursery-deprecation.md

[Rendered](https://github.com/jethrogb/rfcs/blob/nursery-deprecation/text/0000-nursery-deprecation.md)

Amend RFC 1242 to require an RFC for deprecation of crates from the nursery

---

text/0000-nested-method-calls.md
text/2025-nested-method-calls.md

Enable "nested method calls" where the outer call is an `&mut self` borrow, such as `vec.push(vec.len())` (where `vec: Vec<usize>`). This is done by extending MIR with the concept of a **two-phase borrow**; in this model, select `&mut` borrows are modified so that they begin with a "reservation" phase and can later be "activated" into a full mutable borrow. During the reservation phase, reads and shared borrows of the borrowed data are permitted (but not mutation), as long as they are confined to the reservation period. Once the mutable borrow is activated, it acts like an ordinary mutable borrow.
Two-phase borrows in this RFC are only used when desugaring method calls; this is intended as a conservative step. In the future, if desired, the scheme could be extended to other syntactic …

RFC: Enable nested method calls

---

text/0000-optional-match-vert.md
text/1925-optional-match-vert.md

This was written to provide a formal proposal to allow a leading `|` at the beginning of a `match` as was discussed in https://github.com/rust-lang/rfcs/issues/1745. In that thread, it was previously stated the language team is [in favor of this change](https://github.com/rust-lang/rfcs/issues/1745#issuecomment-282150644).
Some of the sections I don't know anything about but I tried to fill in what I knew. For such a small topic, this form seems excessive and so a lot of the text seems fairly brief to me. Also, I'm not actually sure all the examples are needed but I thought it wouldn't hurt to add them.
In brief, this is a proposal that the following `match` syntax be legal:
```rust
enum E { A, B, C, D}
use E::*;
match foo {
| A
| B => (),
| C
| D => (),
}
```
--- …

Allow an optional vert at the beginning of a match branch

---

text/0000-non-exhaustive.md
text/2008-non-exhaustive.md

This is a post-1.0 version of #757, changed to use an attribute instead of a dedicated syntax. This would allow crates to more easily mark enums as "non-exhaustive," requiring downstream crates to add a wildcard arm to matches, so that adding new variants is not a breaking change.
Additionally, this syntax is extended to structs as well.
[Rendered](https://github.com/clarcharr/rust-rfcs/blob/non_exhaustive/text/0000-non-exhaustive.md)

Future-proofing enums/structs with #[non_exhaustive] attribute

---

0000-friends_in_high_kindednesses.md
text/1598-generic_associated_types.md

I definitely realize that this feature may not be prioritized right now, and I expect that some aspects of it probably present real implementation challenges (especially partial application of type operators and extending HRTBs), but I wanted to document and discuss what seems to me like the best incremental step toward higher-kinded polymorphism in Rust.
[Rendered](https://github.com/withoutboats/rfcs/blob/associated_hkts/0000-friends_in_high_kindednesses.md)

Generic associated types (associated type constructors)

---

text/0000-is-aligned-intrinsic.md
text/2043-is-aligned-intrinsic.md

[Rendered](https://github.com/oli-obk/rfcs/blob/is_aligned/text/0000-is-aligned-intrinsic.md)
cc @dwrensha @eddyb @joshlf @nikomatsakis 
Background: https://github.com/solson/miri/issues/190 and https://github.com/rust-lang/rust/issues/42561

Add `align_offset` intrinsic and `[T]::align_to` function

---

text/0000-infer-outlives.md
text/2093-infer-outlives.md

Remove the need for explicit `T: 'x` annotations on structs. We will
infer their presence based on the fields of the struct. In short, if
the struct contains a reference (directly or indirectly) to `T` with
lifetime `'x`, then we will infer that `T: 'x` is a requirement:
```rust
struct Foo<'x, T> {
// inferred: `T: 'x`
field: &'x T
}
```
Explicit annotations remain as an option used to control trait object
lifetime defaults, and simply for backwards compatibility.
[Rendered](https://github.com/nikomatsakis/rfcs/blob/infer-outlives/text/0000-infer-outlives.md)

Infer `T: 'x` outlives requirements on structs

---

text/0000-use-nested-groups.md
text/2128-use-nested-groups.md

This is an incremental improvement to syntax of imports.
With this RFC groups inside of braces `{}` in imports can be nested
```rust
use syntax::{
tokenstream::TokenTree, // >1 segments
ext::base::{ExtCtxt, MacResult, DummyResult, MacEager}, // nested braces
};
```
and globs `*` can be placed into groups as well
```rust
use syntax::ast::{self, *}; // * in braces
```
Closes https://github.com/rust-lang/rfcs/issues/1400
Closes https://github.com/rust-lang/rfcs/issues/1290
[Rendered](https://github.com/petrochenkov/rfcs/blob/c9b1ffd209c9af90c50afac3e25e8003105db5a5/text/0000-use-nested-groups.md)

RFC: Nested groups in imports

---

text/0000-allow-if-let-irrefutables.md
text/2086-allow-if-let-irrefutables.md

This is an RFC for allowing irrefutable patterns in if-let and while-let statements
**Edit**: [Rendered](https://github.com/Nokel81/rfcs/blob/allow_irrefutable-ifwhile-let/text/0000-allow-if-let-irrefutables.md)

RFC: Allow Irrefutable Patterns in if-let and while-let statements

---

text/0000-all-the-clones.md
text/2133-all-the-clones.md

[rendered](https://github.com/arielb1/rfcs/blob/all-the-clones/text/0000-all-the-clones.md).
cc @eddyb @nikomatsakis @aturon

RFC - compiler-generated Clone impls for Arrays and Tuples

---

text/0000-argument-lifetimes.md
text/2115-argument-lifetimes.md

**NOTE**: Updated summary, 2017-09-05
Eliminate the need for separately binding lifetime parameters in `fn` definitions and `impl` headers, so that instead of writing:
```rust
fn two_args<'b>(arg1: &Foo, arg2: &'b Bar) -> &'b Baz
fn two_lifetimes<'a, 'b>(arg1: &'a Foo, arg2: &'b Bar) -> &'a Quux<'b>
fn nested_lifetime<'inner>(arg: &&'inner Foo) -> &'inner Bar
fn outer_lifetime<'outer>(arg: &'outer &Foo) -> &'outer Bar
```
you can write:
```rust
fn two_args(arg1: &Foo, arg2: &'b Bar) -> &'b Baz
fn two_lifetimes(arg1: &'a Foo, arg2: &'b Bar) -> &'a Quux<'b>
fn nested_lifetime(arg: &&'inner Foo) -> &'inner Bar
fn outer_lifetime(arg: &'outer &Foo) -> &'outer Bar
```
Lint against leaving off lifetime parameters in structs (like `Ref` or `Iter`), instead nudging people to use explicit lifetimes …

RFC: In-band lifetime bindings

---

text/0000-path-clarity.md
text/2126-path-clarity.md

This is the latest RFC in the ongoing saga around Rust's module system. **For those of you who have stopped following due to fatigue** 😩: this is almost certainly the final iteration, and I'd like to ask you **one last time** to take a fresh look -- almost all of the text here is new. ❤️ 
Relative to earlier discussion, this proposal is **drastically more conservative**. It does not include any changes to `mod` (i.e., it does not propose to determine module structure from the file system). It does not require epochs.
The lang team does still want to explore the possibility of determining modules from the file system, but plans to do that through an *experimental* RFC -- i.e., to seek just for consensus that we can land a prototype implementation to gather more data and experience; a full …

RFC: Clarify and streamline paths and visibility

---

text/0000-dyn-trait-syntax.md
text/2113-dyn-trait-syntax.md

Introduce a new `dyn Trait` syntax for trait objects using a contextual `dyn` keyword, and deprecate "bare trait" syntax for trait objects. In a future checkpoint, `dyn` will become a proper keyword and bare trait syntax will be removed.
[Rendered](https://github.com/Ixrec/rfcs/blob/dyn-trait-syntax/text/2113-dyn-trait-syntax.md)
The previous RFC on this topic is: https://github.com/rust-lang/rfcs/pull/1603
The RFC that describes checkpoints is: https://github.com/rust-lang/rfcs/pull/2052

`dyn Trait` Syntax for Trait Objects: Take 2

---

text/0000-public-private-dependencies.md
text/1977-public-private-dependencies.md

This RFC introduces the concept of a public/private separation of crate dependencies to aid the ecosystem to explicitly deal with dependencies that themselves become part of the public API of a crate.
This is work in progress.
[Rendered](https://github.com/mitsuhiko/rfcs/blob/public-private-dependencies/text/0000-public-private-dependencies.md)

RFC for Public/Private Dependencies

---

text/0000-impl-trait-type-alias.md
text/2071-impl-trait-type-alias.md

Add the ability to create named existential types and support impl Trait in let, const, and static declarations.
```rust
// existential types
existential type Adder: Fn(usize) -> usize;
fn adder(a: usize) -> Adder {
|b| a + b
}
// existential type in associated type position:
struct MyType;
impl Iterator for MyType {
existential type Item: Debug;
fn next(&mut self) -> Option<Self::Item> {
Some("Another item!")
}
}
// `impl Trait` in `let`, `const`, and `static`:
const ADD_ONE: impl Fn(usize) -> usize = |x| x + 1;
static MAYBE_PRINT: Option<impl Fn(usize)> = Some(|x| println!("{}", x));
fn my_func() {
let iter: impl Iterator<Item = i32> = (0..5).map(|x| x * 5);
...
}
```
[Rendered](https://github.com/cramertj/rfcs/blob/impl-trait-alias/text/0000-impl-trait-type-alias.md)

Named existentials and impl Trait variable declarations

---

text/0000-change-doc-default-urls.md

[rendered](https://github.com/steveklabnik/rfcs/blob/default-url-of-docs/text/0000-change-doc-default-urls.md)
doc.rust-lang.org should redirect to the latest stable release's documentation, not duplicate `/stable`.
/cc @rust-lang/docs

Change the default URL of doc.rust-lang.org

---

text/0000-tool-attributes.md

This RFC proposes a temporary solution to the problem of letting tools use
attributes. We outline a (partial) long-term solution and propose a step towards
that solution for tools which are part of the Rust distribution.

Attributes for tools, 2.0

---

text/0000-external-doc-attribute.md

This RFC proposes an addition to be able to pull in documentation for items from
an external source at compile time, rather than requiring them to be in the
source code itself.
[Rendered](https://github.com/mgattozzi/rfcs/blob/external-doc-attribute/text/0000-external-doc-attribute.md)

Add external doc attribute to rustc

---

text/0000-generic-assert.md

[Pre-RFC](https://internals.rust-lang.org/t/pre-rfc-assert-macros-simplified/5280/9)
[Rendered](https://github.com/ishitatsuyuki/rfcs/blob/generic-assert/text/0000-generic-assert.md)

Add generic_assert

---

text/0000-target-feature.md

This is an RFC for `cfg!(target_feature)` and `#[target_feature]`.
[Rendered](https://github.com/gnzlbg/rfcs/blob/target_feature/text/0000-target-feature.md)

RFC: target_feature

---

text/1990-external-doc-attribute.md

For context: https://github.com/rust-lang/rfcs/pull/1990#issuecomment-332700266

Fix link typo in 1990-external-doc-attribute.md

---

text/0000-variadic.md
text/2137-variadic.md

Support defining C-compatible variadic functions in Rust, via new intrinsics.
Rust currently supports declaring external variadic functions and calling them
from unsafe code, but does not support writing such functions directly in Rust.
Adding such support will allow Rust to replace a larger variety of C libraries,
avoid requiring C stubs and error-prone reimplementation of platform-specific
code, improve incremental translation of C codebases to Rust, and allow
implementation of variadic callbacks.
This RFC does not propose an interface intended for native Rust code to pass
variable numbers of arguments to a native Rust function, nor an interface that
provides any kind of type safety. This proposal exists primarily to allow Rust
to provide interfaces callable from C code. …

Support defining C-compatible variadic functions in Rust

---

text/0000-option-filter.md
text/2124-option-filter.md

Add the method `Option::filter<P>(self, predicate: P) -> Option<T>` to the standard library. This method makes it possible to easily throw away a `Some` value depending on a given predicate. The call `opt.filter(p)` is equivalent to `opt.into_iter().filter(p).next()`.
```rust
assert_eq!(Some(3).filter(|_| true)), Some(3));
assert_eq!(Some(3).filter(|_| false)), None);
assert_eq!(None.filter(|_| true), None);
```
[**Rendered**](https://github.com/LukasKalbertodt/rfcs/blob/rfc-option-filter/text/0000-option-filter.md)
---
I certainly know that there are plenty of active, more important RFCs. But since this RFC only introduces **a tiny change to the standard library**, I figured I should try writing it.
Fixes #1485

RFC: Add `Option::filter` to the standard library

---

text/1607-style-rfcs.md

The previous rendering had half the page trapped in an unterminated code block ([old version rendered](https://github.com/rust-lang/rfcs/blob/f4b8b61a414298ba0f76d9b786d58ccdc34a44bb/text/1607-style-rfcs.md), [new version rendered](https://github.com/andersk/rust-rfcs/blob/68bba1594c20aeaed9a02b8196061254b0e85434/text/1607-style-rfcs.md)).

text/1607-style-rfcs.md: Markdown formatting fix

---

text/0505-api-comment-conventions.md

RFC 1574 amended RFC 505. This change adds a note to the beginning of RFC 505, noting the amendment and linking to RFC 1574 and the combined version of the conventions contained in Appendix A of RFC 1574.

Add note to RFC 505 that it has been amended by RFC 1574

---

text/2141-alternative-registries.md

This fixes a couple of typos and updates things to match the current implementation.
See rust-lang/cargo#4836 and rust-lang/cargo#4880.
cc @withoutboats @carols10cents @alexcrichton

Update RFC 2141

---

text/1758-repr-transparent.md

The RFC made contradictory statements on whether repr(align(N)) can be combined with repr(transparent). [Discussion on the tracking issue][discuss] did not find a good reason to support it, so this commit makes the RFC internally consistent by prohibiting align(N) on transparent structs.
[discuss]: https://github.com/rust-lang/rust/issues/43036#issuecomment-352172909

Amend RFC 1758 (repr(transparent)) w.r.t. repr(align)

---

text/0000-inline-semantic.md
text/2019-inline-semantic.md

Current (Implicit caller location)
* [Rendered](https://github.com/kennytm/rfcs/blob/inline-semantic/text/0000-inline-semantic.md)
* [Proof of concept](https://github.com/rust-lang/rust/compare/master...kennytm:caller-info-4)
Enable accurate caller location reporting during panic in `{Option, Result}::{unwrap, expect}` with
the following changes:
1. Support the `#[blame_caller]` function attribute, which guarantees a function has access to the
caller information.
2. Add an intrinsic function `caller_location()` (safe wrapper: `Location::caller()`) to retrieve
the caller's source location.
----
Legacy (Semantic inlining):
* [Rendered](https://github.com/kennytm/rfcs/blob/c126489/text/0000-inline-semantic.md)
* [Proof of concept](https://github.com/rust-lang/rust/compare/master...kennytm:inl …

RFC: Implicit caller location (third try to the unwrap/expect line info problem)

---

text/0000-build-systems.md
text/2136-build-systems.md

This **experimental RFC** lays out a high-level plan for improving Cargo's ability to integrate with other build systems and environments. As an experimental RFC, it opens the door to landing [unstable features] in Cargo to try out ideas, but *not* to stabilizing those features, which will require follow-up RFCs. It proposes a variety of features which, in total, permit a wide spectrum of integration cases -- from customizing a single aspect of Cargo to letting an external build system run almost the entire show.
[unstable features]: https://github.com/rust-lang/cargo/pull/4433/
[Rendered](https://github.com/aturon/rfcs/blob/build-systems/text/0000-build-systems.md)

eRFC: Cargo build system integration

---

text/0000-alloc-me-maybe.md
text/2116-alloc-me-maybe.md

Add minimal support for fallible allocations to the standard collection APIs. This is done in two ways:
* For users with unwinding, an `oom=panic` configuration is added to make global allocators panic on oom.
* For users without unwinding, a `try_reserve() -> Result<(), CollectionAllocErr>` method is added.
The former is sufficient to unwinding users, but the latter is insufficient for the others (although it is a decent 80/20 solution). Completing the no-unwinding story is left for future work.
[Rendered](https://github.com/Gankro/rfcs/blob/if-at-first-you-dont-alloc/text/0000-alloc-me-maybe.md)

fallible collection allocation 1.0

---

text/0000-type-privacy.md
text/2145-type-privacy.md

Type privacy rules are documented.
Private-in-public errors are relaxed and turned into lints.
[Rendered](https://github.com/petrochenkov/rfcs/blob/9901089b2467b0813456479ba03642e9f0ac0912/text/0000-type-privacy.md)

RFC: Type privacy and private-in-public lints

---

text/0000-unsized-rvalues.md
text/1909-unsized-rvalues.md

This is the replacement to RFC #1808. I will write the "guaranteed optimizations" section tomorrow.
[Rendered](https://github.com/arielb1/rfcs/blob/unsized-rvalues/text/1909-unsized-rvalues.md)
[Summary comment](https://github.com/rust-lang/rfcs/pull/1909#issuecomment-327565150) from Sept 6, 2017
cc @nikomatsakis @eddyb @llogiq @whitequark @briansmith

Unsized Rvalues

---

text/1860-manually-drop.md
text/1990-external-doc-attribute.md

Currently the page is empty http://rust-lang.github.io/rfcs/1990-external-doc-attribute.html because the license header contains a blank line.

Workaround google/pulldown-cmark#124 which has broken #1860 and #1990

---

text/0000-allow-trivial-where-clause-constraints.md
text/2056-allow-trivial-where-clause-constraints.md

[Rendered](https://github.com/sgrif/rfcs/blob/sg-allow-trivial-where-clause-constraints/text/0000-allow-trivial-where-clause-constraints.md)

Allow trivial constraints to appear in where clauses

---

text/0000-if-while-or-patterns.md
text/2175-if-while-or-patterns.md

[Rendered.](https://github.com/Centril/rfcs/blob/rfc/if-while-or-patterns/text/0000-if-while-or-patterns.md)
Enables the use of or-patterns in `if let` and `while let` constructs as in:
```rust
if let A(x) | B(x) | ... = expr {
do_stuff_with(x);
}
while let A(x) | B(x) | ... = expr {
do_stuff_with(x);
}
```
+ @scottmcm, fixing typos, and helping me with the RFC in general.

RFC: or-patterns in if / while let expressions

---

text/0000-impl-only-use.md
text/2166-impl-only-use.md

This RFC gives Rust the syntax:
```rust
use foo::FooTrait as _;
```
Here, `_` means that we want to import the `FooTrait` trait’s impls but
not the trait symbol directly, because we might declare the same symbol
in the module issuing the `use`.
---
[Rendered](https://github.com/phaazon/rfcs/blob/impl-only-use/text/0000-impl-only-use.md)

impl-only-use

---

README.md

Currently issues get often used as feature requests, where they basically get ignored because nobody is watching the issues.
I'd like to propose we stop allowing issues as feature requests and severely restrict the issues on this repo to tracking issues
and general housekeeping.
We instead encourage feature requests to become discussions on the internals forum.

Issues are not feature requests

---

text/0000-stable-simd.md
text/2325-stable-simd.md

The purpose of this RFC is to provide a framework for SIMD to be used on stable
Rust. It proposes stabilizing x86-specific vendor intrinsics, but includes the
scaffolding for other platforms as well as a future portable SIMD design (to be
fleshed out in another RFC).
[Rendered](https://github.com/alexcrichton/rfcs/blob/simd/text/0000-stable-simd.md)

Stable SIMD in Rust

---

text/0000-fmt-debug-hex.md
text/2226-fmt-debug-hex.rs

Add support for formatting integers as hexadecimal with the `fmt::Debug` trait,
including when they occur within larger types.
```rust
println!("{:02X?}", b"AZaz\0")
```
```
[41, 5A, 61, 7A, 00]
```
[Rendered](https://github.com/SimonSapin/rfcs/blob/fmt-debug-hex/text/0000-fmt-debug-hex.md)

Hexadecimal integers with fmt::Debug, including within larger types

---

text/0000-macro-at-most-once-rep.md
text/2298-macro-at-most-once-rep.md

[Rendered](https://github.com/mark-i-m/rfcs/blob/macro-at-most-once-rep/text/0000-macro-at-most-once-rep.md)
[Discussion](https://internals.rust-lang.org/t/pre-rfc-at-most-one-repetition-macro-patterns/6557/16)
EDIT: Implementation in rust-lang/rust#47752

RFC: `?` repetition in macro rules

---

text/0000-label-break-value.md

[Rendered](https://github.com/ciphergoth/rfcs/blob/label-break-value/text/0000-label-break-value.md)
Allow a break not only out of `loop`, but of labelled blocks with no loop. Like `loop`, this break can carry a value.
See also  [Pre-RFC](https://internals.rust-lang.org/t/pre-rfc-early-exit-from-any-block/5372) discussion.
[Status as of 2018-01-18](https://github.com/rust-lang/rfcs/pull/2046#issuecomment-358794318).

RFC: label-break-value

---

0000-template.md
text/0000-prior-art.md
text/2333-prior-art.md

Adds a *Prior art* section to the RFC template where RFC authors may discuss the experience of other programming languages and their communities with respect to what is being proposed. This section may also discuss theoretical work such as papers.
My thanks to @ashleygwilliams for reviewing.
I'd also like to thank @nagisa for the neat section naming and
@scottmcm for giving me great critique which improved the RFC a lot.

Meta-RFC: Prior art

---

text/0000-roadmap-2018.md
text/2314-roadmap-2018.md

This RFC sets the *Rust 2018 Roadmap*, in accordance with [RFC 1728](https://github.com/rust-lang/rfcs/pull/1728). This year's goals are:
- Ship an epoch release: Rust 2018.
- Build resources for intermediate Rustaceans.
- Connect and empower Rust’s global community.
- Grow Rust’s teams and new leaders within them.
In pursuing these goals, we will focus particularly on four target domains for Rust:
- Web services.
- WebAssembly.
- CLI apps.
- Embedded devices.
*A hearty thank you to the 100-some people who wrote blog posts to help drive this process!*
[Rendered](https://github.com/aturon/rfcs/blob/roadmap-2018/text/0000-roadmap-2018.md)

RFC: Rust 2018 Roadmap

---

text/0000-const-locals.md
text/2341-const-locals.md

After https://github.com/rust-lang/rust/pull/46882 adding `let` bindings and destructuring to const fn and blocks in constants is just the removal of a few checks. We want this some day in the future anyway. I don't see any reason not to do this.
I propose we do this without adding an intermediate unstable `feature` and just go with it, but if there are any concerns raised about let bindings or destructuring, we could first add a feature for it.
cc @eddyb 
r? @nikomatsakis 
[Rendered](https://github.com/oli-obk/rfcs/blob/const_locals/text/0000-const-locals.md)

Allow locals and destructuring in const fn

---

text/1946-intra-rustdoc-links.md

In https://github.com/rust-lang/rust/pull/47046, we realized that the proposed disambiguation syntax is not valid CommonMark, and changed it to `[struct@Foo]`, etc.
Additionally, we feel that you should be allowed to use un-disambiguated paths to refer to values as long as there isn't a clash.
cc @QuietMisdreavus @killercup

Update the disambiguation handling in RFC 1946 (intra-rustdoc-links) to match impl concerns

---

text/0000-euclidean-modulo.md
text/2169-euclidean-modulo.md

Proposal to add Euclidean modulo & division functionality for integers and floating-point numbers, to address common issues with taking remainders involving negative numbers.
Internals discussion [here](https://internals.rust-lang.org/t/mathematical-modulo-operator/5952).
[Rendered.](https://github.com/varkor/rfcs/blob/euclidean-modulo/text/0000-euclidean-modulo.md)

Euclidean modulo

---

text/0000-concrete-nonzero-types.md
text/2307-concrete-nonzero-types.md

Add `std::num::NonZeroU32` and eleven other concrete types (one for each primitive integer type) to replace and deprecate `core::nonzero::NonZero<T>`. (Non-zero/non-null raw pointers are available through [`std::ptr::NonNull<U>`](https://doc.rust-lang.org/nightly/std/ptr/struct.NonNull.html).)
[Formatted view](https://github.com/SimonSapin/rfcs/blob/concrete-nonzero/text/0000-concrete-nonzero-types.md)

RFC: Add std::num::NonZeroU32 and friends, deprecate core::nonzero

---

text/0000-const-control-flow.md
text/2342-const-control-flow.md

[Rendered](https://github.com/oli-obk/rfcs/blob/const-control-flow/text/0000-const-control-flow.md)

Allow `if` and `match` in constants

---

text/0000-const-repeat-expr.md
text/2203-const-repeat-expr.md

[Rendered.](https://github.com/Centril/rfcs/blob/rfc/const-repeat-expr/text/0000-const-repeat-expr.md)
Relaxes the rules for repeat expressions, `[x; N]` such that `x` may also be `const`, in addition to `typeof(x): Copy`. The result of `[x; N]` where `x` is `const` is itself also `const`.

RFC: Constants in array repeat expressions

---

text/1951-expand-impl-trait.md

I believe this `Whatever` was accidentally left out.

Fix pseudocode typo in RFC 1951

---

0000-template.md

In `0000-template.md`, in the section "Prior Art", IMO "exist" is the correct form of the verb in the first bullet point.

Typo: Change exists to exist in template.md#prior-art

---

text/2333-prior-art.md

Follows up on #2372 and fixes the typo in RFC #2333

Typo 2: Change exists to exist in template.md#prior-art [prior art RFC]

---

text/0000-type-alias-enum-variants.md
text/2338-type-alias-enum-variants.md

This RFC proposes to allow access to enum variants through type aliases. This enables better abstraction/information hiding by encapsulating enums in aliases without having to create another enum type and requiring the conversion from and into the "alias" enum.
* [Rendered](https://github.com/djc/rfcs/blob/type-alias-enum-variants/text/0000-type-alias-enum-variants.md)
* [Pre-RFC on internals](https://internals.rust-lang.org/t/pre-rfc-enum-variants-through-type-aliases/6433)
* [Prior implementation attempt](https://github.com/rust-lang/rust/pull/31179)

Type alias enum variants

---

text/0000-os-str-pattern.md
text/2295-os-str-pattern.md

Supersedes the "Pattern API" part of RFC #1309.
* [Rendered](https://github.com/kennytm/rfcs/blob/os-str-pattern/text/0000-os-str-pattern.md)
* Incomplete proof-of-concept: [`omgwtf8`](https://github.com/kennytm/omgwtf8)
cc #900. 
cc @Kimundi (#528 "Pattern API 1.0")
cc @SimonSapin (WTF-8)

RFC: Extend Pattern API to OsStr

---

text/0000-unnamed-fields.md
text/2102-unnamed-fields.md

[Rendered](https://github.com/joshtriplett/rfcs/blob/unnamed-fields/text/0000-unnamed-fields.md)
Allow unnamed fields of union and struct type, contained within structs and unions, respectively; the fields they contain appear directly within the containing structure, with the use of union and struct determining which fields have non-overlapping storage (making them usable at the same time). This allows grouping and laying out fields in arbitrary ways, to match C data structures used in FFI. The C11 standard allows this, and C compilers have allowed it for decades as an extension. This proposal allows Rust to represent such types using the same names as the C structures, without interposing artificial field names that will confuse users of well-established interfaces from existing …

Unnamed fields of struct and union type

---

text/0809-box-and-in-for-stdlib.md
text/1228-placement-left-arrow.md

r? @nikomatsakis 
See https://github.com/rust-lang/rust/issues/27779#issuecomment-378416911 for reference.

Unapprove placement RFCs

---

text/2342-const-control-flow.md

As mentioned in https://github.com/rust-lang/rfcs/pull/2342#discussion_r181550902

Fix a typo

---

text/0213-defaulted-type-params.md

It previously pointed to one closed as a duplicate

Fix tracking issue in defaulted type params RFC

---

text/2349-pin.md

This double-negation ("not implement `!Unpin`") looks like a typo. `PinBox` is useful for immovable types (which do not implement `Unpin`), right?

Fix typo in 2349-pin.md

---

text/1951-expand-impl-trait.md

Fix typo in RFC 1951: expanded_impl_trait

---

text/2349-pin.md

Fix the formatting at the top of `2349-pin.md`.

RFC 2349: Conform to header format

---

0000-bury-description.md

[Rendered](https://github.com/pornel/rfcs/blob/master/0000-bury-description.md)
[Thread on internals](https://internals.rust-lang.org/t/pre-rfc-bury-error-description/6314)

Bury Error::description()

---

text/0000-try-expr.md
text/2388-try-expr.md

This RFC reserves `try` as a keyword in edition 2018 for expressions of the form `try { .. }`.
To @scottmcm, @Manishearth, for discussions and to everyone who participated in the [internals thread](https://internals.rust-lang.org/t/bikeshed-rename-catch-blocks-to-fallible-blocks/7121)
**Edit**: If you're looking for the FCP proposal, GitHub is currently hiding it, so click https://github.com/rust-lang/rfcs/pull/2388#issuecomment-381059548

RFC: Reserve `try` for `try { .. }` block expressions

---

text/0000-used.md
text/2386-used.md

RFC to stabilize the experimental `#[used]` feature added in rust-lang/rust#39987.
This feature has been in the compiler for a bit over a year; it's being widely used in embedded /
no-std context; and it has had no bugs filled against it (other than rust-lang/rust#41628 which was
filled shortly after the feature was added).
Tracking issue: rust-lang/rust#40289.
The embedded WG would like to see this feature stabilized in time for the edition release as it appears often in core components of the embedded ecosystem; it's not a blocker for the edition release though as it can be worked around.
[Rendered](https://github.com/japaric/rfcs/blob/used/text/0000-used.md)
cc @aturon

RFC: #[used] static variables

---

text/0000-unreservations-2018.md
text/2421-unreservations-2018.md

We unreserve:
+ `pure`
+ ~`unsized`~
+ `sizeof`
+ `alignof`
+ `offsetof`
+ ~`priv`~
If you have a particular objection **and** use case for some keyword this RFC wants to unreserve, please speak up and leave a comment.

RFC: Keyword unreservations (pure, sizeof, alignof, offsetof)

---

text/0430-finalizing-naming-conventions.md

<s>Because it looks like a camel with a single hump in the middle: 🐪</s>

Clarify we mean UpperCamelCase, not lowerCamelCase

---

text/1105-api-evolution.md

In some cases, it is possible to use unstable features on the Stable release channel. For example:
* In expressions, only the final components of a `foo::bar::baz` path is checked for stability: https://github.com/rust-lang/rust/issues/15702. (See for example https://github.com/rust-lang/rust/pull/49896#issuecomment-381292836.)
* By creating a crate named `test` or with some other name of a standard library crate, is it possible to override what is called by some compiler-generated code. Things break when the signature of those calls later change: https://github.com/rust-lang/rust/issues/49942
* Using the bootstrap flag
This PR proposes that the semantic versioning / stability promise normally associated to the Stable release channel specifically do *not* extend to such cases. Finding a …

Unstable features accidentally usable on the Stable release chanel are still unstable

---

.travis.yml

We don't use jekyll, however it is enabled by default for `gh-pages`, which causes [directories with a leading '_' to  not be served](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/). This, in turn, causes the `/_FontAwesome/*` paths generated by `mdbook` to 404.
r? @rust-lang/docs

[mdbook] Disable jekyll

---

text/2115-argument-lifetimes.md

As noted [here](https://github.com/rust-lang/rfcs/pull/2115/commits/c20ea6db254feac3536de7ae8a13bfdee2b07b42#r135393851) two of the function signatures missed the update from backreferences to in-band declaration.

Fix inconsistency in in-band-lifetimes RFC

---

text/2071-impl-trait-type-alias.md

It's unclear to me whether explicitly defined `existential type ... = ...;` is allowed, and even if they are it would be redundant to define with an `impl trait`.
CC @withoutboats

Fix apparent typo in RFC 2071

---

text/0000-do-not-recommend.md
text/2397-do-not-recommend.md

[Rendered](https://github.com/sgrif/rfcs/blob/sg-do-not-recommend/text/0000-do-not-recommend.md)

Introduce `#[do_not_recommend]` to control errors for trait impls

---

text/0000-option-replace.md
text/2296-option-replace.md

Add the method `Option::replace` to the core library. This method makes possible to easily replace the value of an option to some value (`Some(value)`).
[Rendered](https://github.com/Kerollmops/rfcs-1/blob/master/text/0000-option-replace.md)
```rust
let mut x = Some(2);
let old = x.replace(5);
assert_eq!(x, Some(5));
assert_eq!(old, Some(2));
let mut x = None;
let old = x.replace(3);
assert_eq!(x, Some(3));
assert_eq!(old, None);
```

RFC: Add `Option::replace` to the core library

---

text/0000-const-looping.md
text/2344-const-looping.md

[Rendered](https://github.com/oli-obk/rfcs/blob/const_looping/text/0000-const-looping.md)

Allow `loop` in constant evaluation

---

text/0430-finalizing-naming-conventions.md

See rust-lang/rust#46907
Note: This is already implement and in stable (without RFC). It just updates the text to avoid confusion and to make this better known.
Found this while editing #2457.

Update RFC 0430 to allow underscores between numbers in CamelCase names

---

text/2325-stable-simd.md

The Cretonne project is now renamed to Cranelift. Update the names in
the SIMD RFC and add links to the project page.

Rename Cretonne to Cranelift.

---

text/0000-associated-type-bounds.md
text/2289-associated-type-bounds.md

-------------------
Introduce the bound form `MyTrait<AssociatedType: Bounds>`, permitted anywhere a bound of the form `MyTrait<AssociatedType = T>` would be allowed. The bound `T: Trait<AssociatedType: Bounds>` desugars to the bounds `T: Trait` and `<T as Trait>::AssociatedType: Bounds`.
An example:
```rust
fn print_all<T: Iterator<Item: Display>>(printables: T) {
for p in printables {
println!("{}", p);
}
}
```
-------------------
This RFC was co-authored with @joshtriplett whom it was my pleasure to work with.

RFC: Associated type bounds of form `MyTrait<AssociatedType: Bounds>`

---

text/1860-manually-drop.md

This reflects https://github.com/rust-lang/rust/pull/52711. I have no idea what the correct process is here.

update ManuallyDrop RFC to reflect how the implementation now looks

---

text/0000-is-sorted.md
text/2351-is-sorted.md

Add the methods `is_sorted`, `is_sorted_by` and `is_sorted_by_key` to `[T]` and `Iterator`.
[**Rendered**](https://github.com/LukasKalbertodt/rfcs/blob/rfc-add-is-sorted/text/0000-is-sorted.md)
---
CC https://github.com/rust-lang/rust/issues/44370
EDIT: I posted [a comment](https://github.com/rust-lang/rfcs/pull/2351#issuecomment-380724938) summarizing the discussion so far.

RFC: Add `is_sorted` to the standard library

---

text/0000-capture-disjoint-fields.md
text/2229-capture-disjoint-fields.md

TL;DR: Closures will capture individual fields and not the whole struct when possible.
This RFC proposes that closure capturing should be minimal rather than maximal.
Specifically, existing rules regarding borrowing and moving disjoint fields
should be applied to capturing. If implemented, the following code examples
would become valid:
```rust
let _a = &mut foo.a;
|| &mut foo.b; // Error! cannot borrow `foo`
```
```rust
let _a = &mut foo.a;
move || foo.b; // Error! cannot move `foo`
```
Resolves rust-lang/rust#19004
[Rendered](https://github.com/samsartor/rust-rfcs/blob/master/text/0000-capture-disjoint-fields.md)

Closures Capture Disjoint Fields

---

text/0000-if-let-chains.md
text/2497-if-let-chains.md

Extends `if let` and `while let`-expressions with chaining, allowing you to combine multiple `let`s and `bool`-typed conditions together naturally. After implementing this RFC, you'll be able to write, among other things:
```rust
fn param_env<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>, def_id: DefId) -> ParamEnv<'tcx> {
if let Some(Def::Existential(_)) = tcx.describe_def(def_id)
&& let Some(node_id) = tcx.hir.as_local_node_id(def_id)
&& let hir::map::NodeItem(item) = tcx.hir.get(node_id)
&& let hir::ItemExistential(ref exist_ty) = item.node
&& let Some(parent) = exist_ty.impl_trait_fn
{
return param_env(tcx, parent);
}
...
}
```
The main aim of this RFC is to decide that this is a problem worth solving as well as discussing a few available options. **Most importantly, we want to make `let PAT …

eRFC: if- and while-let-chains, take 2

---

text/0000-c_void-reunification.md

Unify `std::os::raw::c_void` and `libc::c_void` by making them both re-exports of a definition in libcore.
[HTML view](https://github.com/SimonSapin/rfcs/blob/%E7%84%A1/text/0000-c_void-reunification.md)

Unify std::os::raw::c_void and libc::c_void via libcore

---

text/2175-if-while-or-patterns.md

This PR fixes RFC 2175 to also:
+ include leading `|` (already in `match` expressions)
+ include `for` loops (where the or-pattern must be irrefutable as in `let` bindings).
This is more or less a consistency bug-fix.
Elaboration on grammatical consistency and simplification in https://github.com/rust-lang/rfcs/pull/2530#issuecomment-416074033.

Amend RFC 2175 to support for loops and leading vert

---

text/0000-dbg-macro.md
text/2361-dbg-macro.md

This is a simpler and more opinionated counter-proposal to [RFC 2173](https://github.com/rust-lang/rfcs/pull/2173).
[HTML view](https://github.com/SimonSapin/rfcs/blob/dbg-macro/text/0000-dbg-macro.md)

Simpler alternative dbg!() macro

---

text/0000-lint-reasons.md
text/2383-lint-reasons.md

This RFC makes two additions to the lint attributes in Rust code:
- add a `reason` field to the attributes that permits custom text when rendering
- add an `expect` lint attribute that acts as `#[allow]`, but raises a lint when the lint it wants to allow is not raised.
[Rendered](https://github.com/myrrlyn/rfcs/blob/lint_reasons/text/0000-lint-reasons.md)

Lint Reasons RFC

---

text/2169-euclidean-modulo.md
text/2226-fmt-debug-hex.md
text/2230-bury-description.md
text/2314-roadmap-2018.md
text/2394-async_await.md

Raw-string URLs (e.g. `https://github.com/rust-lang/rfcs/pull/2169`) is not rendered as URLs on http://rust-lang.github.io/rfcs/.
So I converted them to markdown style URLs.
I used this script:
```bash
#!/bin/sh
sed -Ei 's$RFC PR: https://github.com/rust-lang/rfcs/pull/([0-9]+)\/?$RFC PR: [rust-lang/rfcs#\1](https://github.com/rust-lang/rfcs/pull/\1)$' text/*.md
sed -Ei 's$Rust Issue: https://github.com/rust-lang/rust/issues/([0-9]+)\/?$Rust Issue: [rust-lang/rust#\1](https://github.com/rust-lang/rust/issues/\1)$' text/*.md
```

Convert raw-string URLs to Markdown

---

text/0000-cfg_attr-multiple-attrs.md
text/2539-cfg_attr-multiple-attrs.md

🖼 [Rendered](https://github.com/Havvy/rfcs/blob/cfg_attr_multi/text/0000-cfg_attr-multiple-attrs.md)
📝Summary
`#[cfg_attr(predicate, attr1, attr2, ...)]` expands to each attribute instead of only taking one attribute.
💖 Thanks
To @Centril for a quick review of the RFC before publishing.
🗒 I'm working on implementing this right now.

#[cfg_attr] expanding to multiple attributes

---

text/0000-const-wildcard.md
text/2526-const-wildcard.md

Allow the syntax `const _: TYPE = VALUE`, analogous to `let _ = VALUE`.
[Rendered](https://github.com/joshlf/rfcs/blob/joshlf/const-wildcard/text/0000-const-wildcard.md)
Discussion on internals [here](https://internals.rust-lang.org/t/allow-const/8231).

Support underscores as constant names

---

text/2539-cfg_attr-multiple-attrs.md

`and()` is not a valid configuration predicate, but `all()` is.

cfg-attr-multi: Fix typo

---

text/0000-re-rebalancing-coherence.md
text/2451-re-rebalancing-coherence.md

RFC #1023 introduced rules that exclude impls which should clearly be
valid. It also used some ambiguous language around what is a breaking
change, that ended up being completely ignored and contradicted by #1105.
This RFC seeks to clarify what is or isn't a breaking change when it
comes to implementing an existing trait, and conservatively expands the
orphan rules to allow impls which do not violate coherence, and fit
within the original goals of #1023.
[Rendered](https://github.com/sgrif/rfcs/blob/sg-re-re-balancing-coherence/text/0000-re-rebalancing-coherence.md)

Re-Rebalancing Coherence

---

0000-template.md
text/0000-future-work.md
text/2561-future-possibilities.md

Adds a *"Future possibilities"* section to the `0000-template.md` RFC template that asks authors to elaborate on what natural extensions there might to their RFC and what future directions this may take the project into. This section asks authors to think *holistically*.
To @aturon for a fruitful discussion about the evolution of the RFC process.

Meta-RFC: Future possibilities

---

text/0000-pattern-3.md
text/2500-needle.md

* [Rendered](https://github.com/kennytm/rfcs/blob/pattern-3/text/0000-pattern-3.md)
* [Pre-RFC](https://internals.rust-lang.org/t/pre-rfc-pattern-api-v3-0/7900)
* Prototype:
* Source: https://github.com/kennytm/pattern-3
* Docs: https://docs.rs/pattern-3/

RFC: Needle API (née Pattern API)

---

text/0000-exhaustive-integer-pattern-matching.md
text/2591-exhaustive-integer-pattern-matching.md

Extend Rust's pattern matching exhaustiveness checks to cover the integer types: `u8`, `u16`, `u32`, `u64`, `u128`, `usize`, `i8`, `i16`, `i32`, `i64`, `i128`, `isize` and `char`.
[Rendered.](https://github.com/varkor/rfcs/blob/exhaustive-integer-pattern-matching/text/0000-exhaustive-integer-pattern-matching.md)
```rust
fn matcher_full(x: u8) {
match x { // ok
0 ..= 31 => { /* ... */ }
32 => { /* ... */ }
33 ..= 255 => { /* ... */ }
}
}
fn matcher_incomplete(x: u8) {
match x { //~ ERROR: non-exhaustive patterns: `32u8..=255u8` not covered
0 ..= 31 => { /* ... */ }
}
}
```
This feature has already [been implemented](https://github.com/rust-lang/rust/pull/50912) behind the feature flag `exhaustive_integer_patterns`, so this RFC is viewed as a motion to stabilise the feature. See …

Stabilise exhaustive integer pattern matching

---

text/2539-cfg_attr-multiple-attrs.md

See https://github.com/rust-lang/rfcs/pull/2539#pullrequestreview-189602548

Fix RFC 2539 text

---

text/0000-libc-struct-traits.md
text/2235-libc-struct-traits.md

[Rendered](https://github.com/Susurrus/rfcs/blob/bd7581f8b853d56c9d88f9f7430eeb3cc1b89379/text/0000-libc-struct-traits.md)
CC previous discussion holders from rust-lang/libc#302: @alexcrichton @kamalmarhubi @dimbleby

RFC: Implement Debug, Eq, PartialEq, and Hash for libc structs

---

text/1558-closure-to-fn-coercion.md

Looks like these were forgotten when the RFC was merged.

Add RFC PR and tracking issue links to RFC 1558

---

text/0000-linked-list-cursors.md
text/2570-linked-list-cursors.md

This is my first RFC, so feel free to critique :)
Many of the benefits of linked lists rely on the fact that most operations (insert, remove, split, splice etc.) can be performed in constant time once one reaches the desired element. To take advantage of this, a `Cursor` interface can be created to efficiently edit linked lists. Furthermore, unstable extensions like the `IterMut` changes will be removed.
The reference implementation is [here](https://github.com/4e554c4c/list_cursors), feel free to make implementation suggestions. :)

RFC: Linked list cursors

---

text/0000-assoc-default-groups.md
text/2532-associated-type-defaults.md

[RFC 192]: https://github.com/rust-lang/rfcs/blob/master/text/0195-associated-items.md#defaults
Resolve the design of associated type defaults, first introduced in [RFC 192], such that provided methods and other items may not assume type defaults. This applies equally to `default` with respect to specialization. Finally, `dyn Trait` will assume provided defaults and allow those to be elided.
[RFC 1210]: https://github.com/rust-lang/rfcs/pull/1210
To @aturon for their work on [RFC 192] and [RFC 1210] upon which this RFC builds.
To @kennytm, @Havvy, @ubsan, @varkor, @alexreg, and @scottmcm for reviewing the draft version of this RFC.

RFC: Associated type defaults

---

text/2175-if-while-or-patterns.md

This introduces no semantic changes to the RFC, and merely clarifies some things.
I wanted to better understand how `let x | y` was supposed to work and found the RFC rather confusing, especially since it doesn't have much of a guide-level section.
Added some examples to clarify things.
As `let x | y` isn't implemented yet this is the only place to find documentation about this proposed feature, so we should ensure it's good
r? @Centril.

Add more examples for | patterns in let in RFC 2175

---

text/0000-roadmap-2019.md
text/2657-roadmap-2019.md

This RFC proposes the *2019 Rust Roadmap*, in accordance with [RFC 1728]. The
goal of the roadmap is to lay out a vision for where the Rust project should
be in a year's time.
You can view [the rendered version here](https://github.com/steveklabnik/rfcs/blob/2019-roadmap/text/0000-roadmap-2019.md).
[RFC 1728]: https://github.com/rust-lang/rfcs/blob/26197104b7bb9a5a35db243d639aee6e46d35d75/text/1728-north-star.md
The proposal is based on the [2018 survey], our annual [call for blog posts],
direct conversations with individual Rust users, and discussions at the 2019
Rust All Hands. Thanks to everyone who helped with this effort!
[2018 survey]: https://blog.rust-lang.org/2018/11/27/Rust-survey-2018.html
[call for blog posts]: https://readrust.net/rust-2019/
In short, 2019 will be a year of …

Roadmap for 2019

---

book.toml

Before:
```html
<title>0001-private-fields - </title>
```
After:
```html
<title>0001-private-fields - The Rust RFC Book</title>
```

Give the Rust RFC Book a title

---

.travis.yml

Confirmed locally that 0.2 builds the book fine.

Bump mdbook: 0.1 -> 0.2.

---

text/1721-crt-static.md

The abbreviation is not defined and is not obvious to a newcomer without a close reading of the document.

Amend RFC 1721 to define crt

---

text/2094-nll.md

Control-flow within a function: incorrect example

---

text/2052-epochs.md
text/2103-tool-attributes.md
text/2113-dyn-trait-syntax.md
text/2115-argument-lifetimes.md
text/2126-path-clarity.md
text/2151-raw-identifiers.md
text/2314-roadmap-2018.md

Future readers interested in the design of editions shouldn't have to
know that we called them "epochs" for a time. They should be able to
find RFC 2052 by searching for "edition", and they shouldn't have to
wonder what an "epoch" is if reading another RFC.
Not changed: the filename of RFC 2052 so that links don't break, and
any usage of the word "epoch" in the "seconds since the epoch" sense.

META: Replace "epoch" with "edition"

---

text/2394-async_await.md

Since Futures are now stable, this is likely to be something folks are looking for.

Add a link to the Futures RFC from the async/await RFC

---

text/0000-transparent-unions.md
text/2645-transparent-unions.md

Let's allow `#[repr(transparent)]` on `union`s and univariant `enum`s that have exactly one non-zero-sized field (just like `struct`s).
[Rendered](https://github.com/mjbshaw/rfcs/blob/transparent_unions/text/0000-transparent-unions.md).
<sub>[Pre-RFC Discourse discussion on internals.rust-lang.org](https://internals.rust-lang.org/t/pre-rfc-transparent-unions/9441).</sub>

Transparent Unions and Enums

---

text/2540-formal-function-parameter-attributes.md
text/2565-formal-function-parameter-attributes.md

This RFC proposes to add attributes in formal function parameter position.
[Rendered](https://github.com/Robbepop/rfcs/blob/master/text/2540-formal-function-parameter-attributes.md)

RFC: Attributes in formal function parameter position

---

text/0000-compiler-team-contributors.md
text/2689-compiler-team-contributors.md

Introduce an intermediate level of member for the compiler team, the **compiler team contributor**.
This proposal is part of a larger effort to introduce more structure into the compiler team's makeup. This structure should make it easier to become a part of the compiler team, by laying out a clear path to membership and by offering more official roles.
This RFC was [collaboratively drafted on the compiler-team repository](https://github.com/rust-lang/compiler-team/pull/52).
[Rendered text.](https://github.com/nikomatsakis/rfcs/blob/compiler-team-regulars/text/0000-compiler-team-contributors.md)

introduce "compiler-team contributors"

---

text/0000-named-custom-cargo-profiles.md
text/2678-named-custom-cargo-profiles.md

* [Rendered](https://github.com/da-x/rfcs/blob/named-custom-cargo-profiles/text/0000-named-custom-cargo-profiles.md)
The proposed change to Cargo is to add the ability to specify user-defined profiles in addition to the four predefined profiles, `dev`, `release`, `test`, and `bench`. It is also desired in this scope to reduce confusion regarding where final outputs reside, and increase the flexbility to specify the user-defined profile attributes.
* [Pre-RFC discussion](https://internals.rust-lang.org/t/pre-rfc-cargo-custom-named-profiles/9538)
* [A very early reference implementation (for 0.33)](https://github.com/da-x/cargo/tree/custom-profile-0.33.0).
* [Strawman pre-RFC: Custom profiles - tools and infrastructure / cargo - Rust …

Named custom cargo profiles

---

text/2532-associated-type-defaults.md

The second commit here requires extra attention because it changes the semantics of the sentence quite heavily. I do believe it's correct though.
There's another weird sentence in the "Interaction with existential types" section:
> This means that the nominal type identity is hidden from certain contexts and only Bar is extensionally known about the type wherefore only the operations of Bar is afforded. 
I left that alone since I couldn't make sense of it, but if someone would post a correction I can include that in this PR. It might also be correct and just PL-Theory-Speak, but it's still very hard to read :)

Fix typos in RFC 2532

---

text/0000-dotdot-patterns.md
text/2707-dotdot-patterns.md

Make `..` a pattern rather than a syntactic fragment of some other patterns.
Follow up to https://github.com/rust-lang/rfcs/pull/2359.
Edit: [Rendered](https://github.com/petrochenkov/rfcs/blob/ddpat/text/0000-dotdot-patterns.md)

Mini-RFC: Make `..` a pattern syntactically

---

text/0000-subslice-pattern-syntax.md
text/2359-subslice-pattern-syntax.md

~~Use an obvious syntax for subslices in slice patterns - `..` and `..PAT`.  
If syntactic ambiguities arise in the future, always disambiguate in favor of subslice patterns.~~
Use syntax `..` for "wildcard" sub-slice patterns and `IDENT @ ..` for binding subslice pattern to a name.
[Rendered](https://github.com/petrochenkov/rfcs/blob/subsl/text/0000-subslice-pattern-syntax.md)

RFC: Finalize syntax for slice patterns with subslices

---

text/0000-debug-map-key-value.md
text/2696-debug-map-key-value.md

[Rendered](https://github.com/KodrAus/rfcs/blob/debug_map_entry/text/0000-debug-map-key-value.md)
Add two new methods to `std::fmt::DebugMap` for writing the key and value part of a map entry separately:
```rust
impl<'a, 'b: 'a> DebugMap<'a, 'b> {
pub fn key(&mut self, key: &dyn Debug) -> &mut Self;
pub fn value(&mut self, value: &dyn Debug) -> &mut Self;
}
```

Add key and value methods to DebugMap

---

README.md

As discussed with @scottmcm.
The diff is just `+lack of` when you ignore the re-wrap.

Improve wording in the README

---

text/1291-promote-libc.md

The RFC has an apparent typo that I cleaned up.

Fix typo in 1291-promote-libc.md

---

text/0000-impl-trait-type-aliases.md
text/2515-impl-trait-type-aliases.md

Allow `impl Trait` to be used in type aliases and associated traits, resolving the open question in [RFC 2071](https://github.com/rust-lang/rfcs/pull/2071) as to the concrete syntax for `existential type`. This makes it possible to write type aliases of the form:
```rust
type Adder = impl Fn(usize) -> usize;
// equivalent to: `existential type Adder: Fn(usize) -> usize;`
```
[Rendered.](https://github.com/varkor/rfcs/blob/impl-trait-type-aliases/text/0000-impl-trait-type-aliases.md)
Thanks to @rpjohnst and @Centril for their ideas, discussion and feedback.

Permit impl Trait in type aliases

---

text/0000-simd-ffi.md
text/2574-simd-ffi.md

This RFC allows using architecture-specific vector types like `core::arch::x86_64::__m128` in C FFI.
[Rendered](https://github.com/gnzlbg/rfcs/blob/simd_ffi/text/0000-simd-ffi.md).

RFC: SIMD vectors in FFI

---

text/2394-async_await.md

Elude means to evade or escape from. Allude means to make indirect reference.
https://grammarist.com/usage/allude-elude/

Typo in RFC 2394

---

text/0000-simple_unwind_annotation.md

cc @BatmanAoD 
Per discussion in #2753, this switches the RFC to describe an ABI string-based approach, rather than an attribute-based approach.

Switch from annotation approach to new ABI string approach

---

text/2582-raw-reference-mir-operator.md

This came up during discussion but I forgot to add it to the RFC.

raw ref: mention why the more obvious syntax does not work

---

text/0000-cfg-path-version.md
text/1105-api-evolution.md
text/1122-language-semver.md
text/2523-cfg-path-version.md

Permit users to `#[cfg(..)]` on whether:
+ they have a certain minimum Rust version (`#[cfg(version(1.27))]`).
+ a certain external path is accessible (`#[cfg(accessible(::std::mem::ManuallyDrop))]`).
To @eddyb, @rpjohnst, @kennytm, @aturon, and @rkruppe for discussing the feature with me.
To @Mark-Simulacrum, @MajorBreakfast, @alexreg, @alercah, and @joshtriplett for reviewing the draft version of this RFC.

RFC: #[cfg(accessible(..) / version(..))]

---

text/0000-min-rust-version.md
text/2495-min-rust-version.md

This RFC adds an ability to specify Minimum Supported Rust Version (MSRV) in `Cargo.toml` using  `rust` field:
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"
rust = "1.35"
```
[Rendered](https://github.com/newpavlov/rfcs/blob/msrv/text/0000-min-rust-version.md)
[Internals discussion](https://internals.rust-lang.org/t/pre-pre-rfc-reviving-minimum-rust-version/7783)
Edit: FCP proposal https://github.com/rust-lang/rfcs/pull/2495#issuecomment-532853518

RFC: Minimum Supported Rust Version

---

text/1210-impl-specialization.md

Suggest to fix a few errors/typos:
1. Erronously named type ```R``` renamed to ```Rhs```
2. Name some anonymous parameters (as later they are deprecated by RFC#1685)

Fix some errors in type and parameter names

---

text/0000-demote-apple-32bit.md

This RFC proposes demoting the following targets to Tier 3:
* **`i686-apple-darwin` (from Tier 1)**
* `armv7-apple-ios` (from Tier 2)
* `armv7s-apple-ios` (from Tier 2)
* `i386-apple-ios` (from Tier 2)
[Rendered](https://github.com/pietroalbini/rfcs/blob/demote-apple-32bit/text/0000-demote-apple-32bit.md)

Demote Apple 32bit targets to Tier 3

---

text/2457-non-ascii-idents.md

cc https://github.com/rust-lang/rust/issues/55467#issuecomment-569484220

Non-ASCII identifiers: NFC normalization is performed by lexer, not parser

---

text/0000-project-safe-transmute.md

[rendered](https://github.com/rust-lang/rfcs/blob/b8f60e0360793eac4839f589532a6e35d6efdd4c/text/0000-project-safe-transmute.md)
This RFC is based on a similar RFC: #2797.

Announcing the Safe-Transmute Project Group

---

text/0000-format-args-implicit-identifiers.md

[Rendered](https://github.com/davidhewitt/rfcs/blob/format-args-implicit-identifiers/text/0000-format-args-implicit-identifiers.md)
Proposes the ability to pass **implicit named arguments** to formatting macros, for example:
let person = "Charlie";
print!("Hello, {person}!");    // implicit named argument `person`
A follow up to internals discussion https://internals.rust-lang.org/t/println-use-named-arguments-from-scope/10633 and WIP PR https://github.com/rust-lang/rust/pull/65338

Propose implicit named arguments for formatting macros

---

text/2394-async_await.md

This RFC isn't fully implemented, but tracking bug is closed. 
This PR adds a tracking bug I found for part of the RFC that is not implemented.
There may be other open tracking bugs. This PR is intended to be an improvement,
may not be a complete fix for issue:  https://github.com/rust-lang/rust/issues/66909

Add tracking issue for #!feature(async_closure)]

---

text/2570-linked-list-cursors.md

In [the thread for RFC 2570](https://github.com/rust-lang/rfcs/pull/2570), @Amanieu [made a comment about better method names](https://github.com/rust-lang/rfcs/pull/2570#issuecomment-436608939) which everyone seemed to largely agree with. However, somehow it was forgotten to adjust the RFC. This PR fixes that. See the commit messages for more details.
There are some discussions about the exact API left. These can happen in the tracking issue. However, this change is probably a clear improvement over the current RFC. The RFC is also currently [being implemented](https://github.com/rust-lang/rust/pull/68123). CC @crlf0710

Fix linked list cursor names

---

text/0000-target-feature-1.1.md

[Rendered](https://github.com/gnzlbg/rfcs/blob/tf11/text/0000-target-feature-1.1.md)

target_feature 1.1

---

text/0000-roadmap-2020.md

[summary]: #summary
Lays out the Rust roadmap for 2020 in pursuit of our mission
to empower everyone to build reliable and efficient software.
The roadmap takes the form of the following goals for the project:
* Prepare for a possible Rust 2021 Edition
* Followthrough on in-progress designs and efforts
* Improve project functioning and governance:
* Improve visibility into the state of initiatives and design efforts
* Increase mentoring, leadership, and organizational bandwidth
* Make design discussions more productive and less exhausting
The roadmap this year is different in structure than prior years.  In
particular, we have avoided setting precise goals, in favor of
describing more general mandates and themes.
We chose to take this approach for a few reasons:
* The roadmap RFC doesn't …

Rust 2020 roadmap

---

style-guide/README.md

See https://github.com/rust-dev-tools/fmt-rfcs/pull/148
The guide makes reference to `//* ... */` comments and `//*!` comments. This appears to have been in error per: https://doc.rust-lang.org/reference/comments.html

fix error regarding block comments

---

text/0000-llvm-asm.md
text/2843-llvm-asm.md

This is the first RFC from the inline asm project group!
[Rendered](https://github.com/Amanieu/rfcs/blob/llvm-asm/text/0000-llvm-asm.md)

Add llvm_asm! and deprecate asm!

---

text/2603-rust-symbol-name-mangling-v0.md

When #2603 was implemented, we decided on these names (https://github.com/rust-lang/rust/pull/57967#issuecomment-463596992):
* `legacy`, for the pre-#2603 mangling based on the Itanium C++ one
* `v0`, for the #2603 mangling
That differs from the RFC, so I've renamed away the "v2" in the RFC title (https://github.com/rust-lang/rfcs/pull/2603#event-3127804967) and the tracking issue (https://github.com/rust-lang/rust/issues/60705#event-3127801831), and that leaves the file itself.
cc @rust-lang/compiler

Replace #2603's (Rust Symbol Mangling) "v2" with "v0".

---

text/0000-cargo-report-future-incompat.md

[rendered](https://github.com/pnkfelix/rfcs/blob/cargo-report-future-incompat/text/0000-cargo-report-future-incompat.md)
Summary: Cargo should alert developers to upstream dependencies that trigger future-incompatibility warnings. Cargo should list such dependencies even when these warnings have been suppressed (e.g. via `--cap-lints` or `#[allow(..)]` attributes.)
Cargo could additionally provide feedback for tactics a maintainer of the downstream crate could use to address the problem (the details of such tactics is not specified nor mandated by this RFC).
[Pre-RFC internals thread](https://internals.rust-lang.org/t/pre-rfc-cargo-report-future-incompat/11005/25)

Cargo report future-incompat

---

text/2700-associated-constants-on-ints.md

In RFC 2700, links associated with `std::*::UMAX` point to `UMIN` documentation pages. This PR fixes the links.

RFC 2700: Fix links to std::*::MAX

---

text/0000-project-asm.md

[Rendered](https://github.com/Amanieu/rfcs/blob/project-asm/text/0000-project-asm.md)

Introduce the ASM project group

---

text/0000-unsafe-block-in-unsafe-fn.md

No longer treat the body of an `unsafe fn` as being an `unsafe` block.  To avoid a breaking change, this is a warning now and may become an error in a future edition.
[Rendered](https://github.com/RalfJung/rfcs/blob/unsafe-block-in-unsafe-fn/text/0000-unsafe-block-in-unsafe-fn.md)
The RFC has been adjusted to be a lint; [see here](https://github.com/rust-lang/rfcs/pull/2585#issuecomment-605663111) for the comment announcing that change and the following discussion.
Cc @rust-lang/wg-unsafe-code-guidelines

RFC for unsafe blocks in unsafe fn

---

text/0000-compiler-major-change-process.md

Introduce the **major change process** for the compiler team. This process has the following goals:
* to advertise major changes and give the team a chance to weigh in;
* to help scale the amount of work being done to reviewing bandwidth by choosing a reviewer in advance;
* to avoid a lot of process overhead.
The intent here is that if you have a plan to make some "major change" to the compiler, you will start with this process. It may either simply be approved, but if the change proves more controversial or complex, we may escalate towards design meetings, longer write-ups, or full RFCs before reaching a final decision.
This process does not apply to adding new language features, but it can be used for minor features such as adding new `-C` flags to the compiler. …

major change proposal process for compiler team

---

README.md

Not sure if the line I'm adding is 100% correct or not and if we should be adding this here but pretty sure this information should be somewhere in the README. Otherwise, reader only see that number shouldn't be assigned by them and left to wonder about where it comes from and when. :)

Document when and how a number is assigned to RFC file

---

text/0000-isa-attribute.md

This RFC proposes a new function attribute, `#[instruction_set(...)]`.  The minimal initial implementation will provide `#[instruction_set(a32)]` and `#[instruction_set(t32)]` on ARM targets, corresponding respectively to disabling and enabling the LLVM feature `thumb-mode` for the annotated function.

RFC: Add a new `#[instruction_set(...)]` attribute for supporting per-function instruction set changes

---

text/0000-c-unwind-abi.md

This RFC was drafted by the [FFI Unwind project group](https://github.com/rust-lang/project-ffi-unwind).
[Rendered](https://github.com/BatmanAoD/rfcs/blob/PG-FFIUnwind-c-unwind-abi/text/0000-c-unwind-abi.md)

RFC: 'C-unwind' ABI

---

text/0000-inline-const.md

[Rendered](https://github.com/ecstatic-morse/rfcs/blob/inline-const/text/0000-inline-const.md)
TL; DR: Allows users to request compile-time evaluation without requiring promotion or a named `const`.
```rust
fn foo() -> &'static i32 {
&const { 
let x = 4i32;
x.pow(5)
}
}
fn main() {
match *x {
0 ..= const { u32::MAX / 2 } => println!("low"),
const { u32::MAX / 2 + 1 } ..= u32::MAX => println!("high"),
}
}
```
This idea has been in the ether for a while now as a way to [reduce dependence on promotion](https://github.com/rust-lang/rust/pull/70042#issuecomment-612221597) for evaluating simple expressions at compile-time. It was discussed most recently on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.22Why.20use.20.60const.60.20over.20.60let.60.3F.22).
Credit to …

Inline `const` expressions and patterns

---

text/1946-intra-rustdoc-links.md

- Mention the behavior for cross-crate re-exports
- Mention the behavior for linking to private items
- Require that disambiguators match, even if they're in the same namespace
- For the extension on associated items, require that traits be in scope to link to their associated items
- ~~Add a possible `Deref` extension~~ Removed, this is not implemented, and it's not clear if it will be implemented.
The only behavior change from the original RFC is that disambiguators must now match (see also https://github.com/rust-lang/rust/issues/74851 and https://github.com/rust-lang/rust/pull/75079). All other changes are either clarifications or possible extensions.
r? @Manishearth

Update the intra-doc link RFC to match the implementation

---

text/2912-rust-analyzer.md

I came across across these when reading the RFC.

Fix typo in 2912-rust-analyzer.md

---

text/0000-rustdoc-json.md

[Rendered](https://github.com/p1n3appl3/rfcs/blob/rustdoc-json/text/0000-rustdoc-json.md)
This RFC is an extension of [one from 2018](https://github.com/QuietMisdreavus/rfcs/blob/rustdoc-json/text/0000-rustdoc-json.md) started by @QuietMisdreavus. I've been working on an implementation with mentorship from @tmandry and @betamos and some of the necessary refactoring [has already been done](https://github.com/rust-lang/rust/pull/73767) in coordination with @GuillaumeGomez.
I'm still working on the reference level docs (pardon the TODOs) but I'd love feedback on the proposed design and unresolved questions.

eRFC: Add JSON backend to Rustdoc

---

text/0000-stdsimd.md
text/2977-stdsimd.md

Establishes a new project group under libs for the production and stabilization of a `core::simd` and `std::simd` module. Based on the work of @hsivonen.
[Rendered](https://github.com/KodrAus/rfcs/blob/simd-pg/text/0000-stdsimd.md)
cc @BurntSushi @hsivonen @Lokathor

[RFC]: Portable SIMD Libs Project Group

---

text/2873-inline-asm.md

`nostack` is specified further on in the RFC.
cc @Amanieu

Fix ABNF in RFC 2873

---

text/2582-raw-reference-mir-operator.md

The code as given wouldn't even compile.

RFC 2582: fix implicit auto-deref of raw pointers

---

text/0000-promote-aarch64-unknown-linux-gnu-to-tier1.md

This commit contains an RFC proposal to promote the aarch64-unknown-linux-gnu Rust target to Tier-1.
[Rendered](https://github.com/raw-bin/rfcs/blob/promote-aarch64-unknown-linux-gnu-to-tier-1/text/0000-promote-aarch64-unknown-linux-gnu-to-tier1.md)

RFC: Promote aarch64-unknown-linux-gnu to a Tier-1 Rust target

---

text/2603-rust-symbol-name-mangling-v0.md

This was suggested by @pnkfelix in https://github.com/rust-lang/rfcs/pull/2603#discussion_r279670424, and @michaelwoerister seemed to agree to it, but it didn't make it into the RFC before merging.
I also removed the `0-9` -> `A-J` rewriting of Punycode's base-36 encoding, as it only existed to avoid having identifiers start with decimal digits, which would now work.
cc @rust-lang/compiler Do we have a procedure for amending RFCs?

Amend RFC2603 to allow mangled identifiers to start with a digit.

---

text/0000-destructuring-assignment.md

This RFC is co-authored with @fanzier.
We allow destructuring on assignment, as in `let` declarations. For instance, the following are now
accepted:
```rust
(a, (b.x.y, c)) = (0, (1, 2));
(x, y, .., z) = (1.0, 2.0, 3.0, 4.0, 5.0);
[_, f, *baz()] = foo();
[g, _, h, ..] = ['a', 'w', 'e', 's', 'o', 'm', 'e', '!'];
Struct { x: a, y: b } = bar();
Struct { x, y } = Struct { x: 5, y: 6 };
```
This brings assignment in line with `let` declaration, in which destructuring is permitted. This
will simplify and improve idiomatic code involving mutability.
A working prototype may be found at rust-lang/rust#71156.
[Rendered.](https://github.com/varkor/rfcs/blob/destructuring-assignment/text/0000-destructuring-assignment.md)
Thanks to @joshtriplett for providing feedback on the RFC.
Closes #372.

Destructuring assignment

---

text/0000-read-buf.md

[Rendered](https://github.com/sfackler/rfcs/blob/read-buf/text/0000-read-buf.md)

RFC: Reading into uninitialized buffers

---

text/2145-type-privacy.md

Change `pub Trait` to `pub trait Trait`

Fix syntax in RFC 2145

---

text/2345-const-panic.md

The panic error message now has an argument for the format.

Update example in RFC 2345 to have format argument

---

text/2141-alternative-registries.md

The cargo configuration toml key is `[registries.my-registry]`, so the corresponding env key is `CARGO_REGISTRIES_MY_REGISTRY`.

fix incorrect cargo environment variable in 2141

---

text/0000-cargo-features2.md
text/2957-cargo-features2.md

This RFC proposes to stabilize Cargo's new feature resolver, and the new command-line behavior for feature flags.
[Rendered](https://github.com/ehuss/rfcs/blob/cargo-features2/text/0000-cargo-features2.md)

Stabilize Cargo's new feature resolver

---

text/0000-infallible-promotion.md
text/3027-infallible-promotion.md

This is the RFC-follow-up to https://github.com/rust-lang/lang-team/issues/58.
[Rendered](https://github.com/RalfJung/rfcs/blob/infallible-promotion/text/0000-infallible-promotion.md)

Infallible promotion

---

text/0000-cfg-target-abi.md
text/2992-cfg-target-abi.md

This proposes a new `cfg`: `target_abi`, which specifies certain aspects of the target's [Application Binary Interface (ABI)](https://en.wikipedia.org/wiki/Application_binary_interface). This also adds a `CARGO_CFG_TARGET_ABI` environment variable for parity with other `CARGO_CFG_TARGET_*` variables.
[Rendered](https://github.com/nvzqz/rust-rfcs/blob/cfg-target-abi/text/0000-cfg-target-abi.md)

RFC: Add `target_abi` configuration

---

text/0000-panic-plan.md

[Rendered](https://github.com/fusion-engineering-forks/rfcs/blob/panic/text/0000-panic-plan.md)

RFC: Plan to make core and std's panic identical.

---

text/3037-roadmap-2021.md

The focus of this year is on project health, specifically as it relates to Rust's governance structure.
* Establishing charters for teams in the Rust project
* Provide for unified process and vocabulary across the project
* Creating a single place for tracking a list of ongoing projects
The core team will drive these efforts in coordination with all Rust teams and working groups. As the Rust teams have grown over the years, there is increasingly less cross-chatter that naturally happens due to shared membership of teams, and this RFC aims to improve our written documentation to provide for a smoother on boarding process for new team members, as well as improving the ability of current team members to evaluate who to consult on new ideas or projects. …

Rust 2021 Roadmap

---

text/2203-const-repeat-expr.md

The tracking issue for 2203 was closed; see https://github.com/rust-lang/rust/issues/49147#issuecomment-775282720

Mark 2203 as mostly superceeded by 2920

---

text/1445-restrict-constants-in-patterns.md

This fixes the link to <https://internals.rust-lang.org/t/how-to-handle-pattern-matching-on-constants/2846> in RFC 1445

Fix link in RFC 1445

---

text/2920-inline-const.md

There is a typo in the link of RFC 1414.

Fix the link of RFC 1414 in RFC 2920

---

text/0505-api-comment-conventions.md
text/1574-more-api-documentation-conventions.md

All documentation I could find uses `tests` instead of `test` for an inline module containing `#[test]` functions:
* [The Book](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)
* [Rust by Example](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html)

Use more common 'tests' module name over 'test' in examples

---

text/0000-native-link-modifiers.md

Provide some generic syntax (similar to target features) for linking modifiers used for native libraries.
Provide some specific modifiers to control bundling behavior, whole-archive and the library name mangling.

Linking modifiers for native libraries

---

text/0000-deprecate-authors-field.md
text/0000-optional-authors-field.md

This RFC proposes to make the `package.authors` field of `Cargo.toml` optional. This RFC also proposes preventing Cargo from auto-filling it, allowing crates to be published to crates.io without the field being present, and avoiding displaying its contents on the crates.io and docs.rs UI.
[Rendered](https://github.com/pietroalbini/rfcs/blob/deprecate-authors-field/text/0000-optional-authors-field.md)

Make the authors field optional

---

text/0000-macro-metavar-expr.md

Add new syntax to declarative macros to give their authors easy access to additional metadata about macro metavariables, such as the index, length, or count of macro repetitions.
This RFC has been drafted as part of the lang-team [declarative macro repetition counts](https://github.com/rust-lang/lang-team/issues/57) project.
[Rendered](https://github.com/markbt/rfcs/blob/macro_metavar_expr/text/0000-macro-metavar-expr.md)

RFC: Declarative macro metavariable expressions

---

text/0000-try-trait-v2.md
text/3058-try-trait-v2.md

Replace [RFC #1859, `try_trait`](https://rust-lang.github.io/rfcs/1859-try-trait.html), with a new design for the currently-unstable [`Try` trait](https://doc.rust-lang.org/nightly/std/ops/trait.Try.html) and desugaring for the `?` operator.
[🖼️ **Rendered** 🖼️](https://github.com/scottmcm/rfcs/blob/do-or-do-not/text/0000-try-trait-v2.md#summary)
**Update 2021-02-07**: This was almost completely rewritten.  If you're looking to read the discussion, you might want to jump to https://github.com/rust-lang/rfcs/pull/3058#issuecomment-774755749 for the comments that are about the current version of the text.
I've also made a proof-of-concept implementation: https://github.com/scottmcm/rust/pull/2/files
Thanks to everyone who discussed this problem space in [the original RFC …

try_trait_v2: A new design for the ? desugaring

---

text/3016-const-ub.md

It looks like "anything else" is what was meant here.

Fix minor typo in const-ub RFC

---

README.md

Almost all of the teams that use RFCs are now on Zulip.

Change readme link for chat service.

---

text/0000-edition-2021.md

This RFC describes the plan for the 2021 Edition. It supercedes [RFC 2052]. The proposed 2021 Edition is intentionally more limited than the 2018 Edition. Rather than representing a major marketing push, the 2021 Edition represents a chance for us to introduce changes that would otherwise be backwards incompatible. It is meant to be marketed in many ways as something closer to "just another release".
[Rendered](https://github.com/nikomatsakis/rfcs/blob/edition-2021-or-bust/text/0000-edition-2021.md)
Key points include:
* Editions are used to introduce changes into the language that would otherwise have the potential to break existing code, such as the introduction of a new keyword.
* Editions are never allowed to split the ecosystem. We only permit changes that still allow crates in …

RFC: 2021 Edition

---

text/2603-rust-symbol-name-mangling-v0.md

* Remove type from constant placeholders (removed in rust-lang/rust#77554).
* Add encoding of bool values, char values, and negative integer values (added in rust-lang/rust#77452, rust-lang/rust#77554).
* Make `<binder>` optional in `<fn-sig>` and `<dyn-bounds>` productions (since the initial implementation).
* Use `<namespace>` for namespace production, instead of a mix of `<ns>` and `<namespace>`.
* Use `=` to define `<fn-sig>` rule.
Fixes #3112.

Update mangling scheme syntax

---

text/0000-type-changing-struct-update-syntax.md

Extend struct update syntax (a.k.a. functional record update (FRU)) to support instances of the same struct that have different types due to generic type or lifetime parameters.
[Rendered](https://github.com/jturner314/rust-rfcs/blob/type-changing-struct-update-syntax/text/0000-type-changing-struct-update-syntax.md).
See also #1975 and rust-lang/rust#47741.

Type-changing struct update syntax

---

text/2094-nll.md

This changes the NLL RFC to point to the correct tracking issue.

Fix NLL tracking issue

---

text/0000-io-safety.md

[Pre-RFC on IRLO](https://internals.rust-lang.org/t/pre-rfc-i-o-safety/14585)
Raw OS handles such as `RawFd` and `RawHandle` have hazards similar to raw pointers; they may be bogus or may dangle, leading to broken encapsulation boundaries and code whose behavior is impossible to bound in general.
Introduce a concept of *I/O safety*, and introduce a new set of types and traits, led by `OwnedFd` and `BorrowedFd`, to support it.
[Edited to reflect changes to the RFC].
[Rendered](https://github.com/sunfishcode/rfcs/blob/main/text/0000-io-safety.md)

RFC: I/O Safety

---

text/3128-io-safety.md

This RFC contained some links that referred to Rust symbols but lacked a
Markdown link reference definition, so they were just parsed as normal
text.
Test Plan:
In the rendered document, the character `[` now only appears as part of
the phrase `&[u8]`.
wchargin-branch: io-safety-link-refs

io-safety: add missing link reference definitions

---

text/0000-let-else.md

Introduce a new `let PATTERN: TYPE = EXPRESSION else DIVERGING_BLOCK;` construct (informally called a
**let-else statement**), the counterpart of if-let expressions.
If the pattern match from the assigned expression succeeds, its bindings are introduced *into the
surrounding scope*. If it does not succeed, it must diverge (return `!`, e.g. return or break).
Technically speaking, let-else statements are refutable `let` statements.
The expression has some restrictions, notably it may not be an `ExpressionWithBlock` or `LazyBooleanExpression`.
This RFC is a modernization of a [2015 RFC (pull request 1303)][old-rfc] for an almost identical feature.
[**Rendered**](https://github.com/Fishrock123/rfcs/blob/let-else/text/0000-let-else.md)
[old-rfc]: https://github.com/rust-lang/rfcs/pull/1303 …

RFC: let-else statements

---

text/0089-loadable-lints.md
text/0236-error-conventions.md
text/0240-unsafe-api-location.md
text/2497-if-let-chains.md

As mentioned in rust-lang/rust#87357, this repo has no `.mailmap`. Is there a reason for this?

Update all references to my name

---

text/0000-derive-enum-default.md

[Pre-RFC on IRLO](https://internals.rust-lang.org/t/pre-rfc-derive-default-on-enums-with-a-default-attribute/14440?u=jhpratt)
TLDR allow this:
```rust
#[derive(Default)]
enum Option<T> {
#[default]
None,
Some(T),
}
```
[Rendered](https://github.com/jhpratt/rfcs/blob/derive-enum-default/text/0000-derive-enum-default.md)

`#[derive(Default)]` on enums with a `#[default]` attribute

---

text/0000-byte-concat.md

[Rendered](https://github.com/estebank/rfcs/blob/byte-concat/text/0000-byte-concat.md)

RFC: Introduce `concat_bytes!()` to join `[u8]` and byte `str` analogous to `concat!` for `str`

---

text/0000-cargo-weak-namespaced-features.md
text/3143-cargo-weak-namespaced-features.md

This proposes to stabilize the weak-dep-features and namespaced-features.
[**Rendered**](https://github.com/ehuss/rfcs/blob/cargo-weak-namespaced-features/text/0000-cargo-weak-namespaced-features.md)

Stabilize Cargo's weak-dep-features and namespaced-features.

---

text/0809-box-and-in-for-stdlib.md
text/1228-placement-left-arrow.md
text/2500-needle.md

This is according to the decision within https://github.com/rust-lang/rust/pull/76901#issuecomment-880169952
Currently it is pending on the ongoing fcp, which will finish tomorrow.

Withdraw RFC 2500 approval & use consistent wording.

---

text/1214-projections-lifetimes-and-wf.md

The date is based on the PR date, and seems useful and convenient if the RFC is opened in the book and the reader wants to know roughly when it was written.

Add start date to RFC 1214

---

text/0528-string-patterns.md

The feature name for `string-patterns` (which is `pattern`) was missing and the tracking issue listed was closed in favor of another. This PR adds the feature name and updates the tracking issue to match [unstable-book/library-features/pattern](https://doc.rust-lang.org/unstable-book/library-features/pattern.html).

Updated string-patterns feature name and tracking issue

---

text/3123-rustdoc-scrape-examples.md

[Rendered](https://github.com/willcrichton/rfcs/blob/master/text/3123-rustdoc-scrape-examples.md)

Scrape code examples from `examples/` directory for Rustdoc

---

text/0000-rust-crate-ownership.md
text/3119-crate-ownership.md

The Rust project publishes a lot of crates, and it's not always clear what their guarantees are. This aims to start an endeavor to categorize these crates and introduce a policy for consistently messaging their raison d'être and guarantees.
This policy doesn't directly affect crates published by the wider ecosystem, however the results of such categorization will likely be very useful to the ecosystem for knowing what should and shouldn't be depended on.
:memo: [Rendered](https://github.com/Manishearth/rfcs/blob/crate-ownership/text/0000-rust-crate-ownership.md) :memo:

Rust-lang crate ownership policy

---

text/0000-supertrait-item-shadowing.md

Change item resolution for generics and trait objects so that a trait bound does not bring its supertraits' items into scope if the subtrait defines an item with this name itself.
This makes it possible to write the following, which is currently rejected by the compiler due to ambiguity:
```rust
trait Super {
fn foo(&self);
}
trait Sub: Super {
fn foo(&self);
}
fn generic_fn<S: Sub>(x: S) {
x.foo();
}
```

RFC: Supertrait item shadowing

---

0000-template.md
text/3119-rust-crate-ownership.md

It appears that some of the changes that were meant to go to RFC 3119
ended up in the RFC template instead.

Fix fallout from #3119 merge.

---

.github/workflows/deploy.yml
book.toml

This significantly shrinks the pre-compressed search index:
$ du -h searchindex-old.js searchindex-new.js
26M	searchindex-old.js
19M	searchindex-new.js
And shrinks the search index even after it's gzipped:
$ du -h searchindex-old.js.gz searchindex-new.js.gz
4.5M	searchindex-old.js.gz
3.3M	searchindex-new.js.gz
This change requires a newer version of mdBook, with https://github.com/rust-lang/mdBook/pull/1637
Before:
After:

Do not include headers in search index

---

text/0000-cargo-multi-dep-artifacts.md
text/3028-cargo-binary-dependencies.md
text/3176-cargo-multi-dep-artifacts.md

[Rendered](https://github.com/joshtriplett/rfcs/blob/multidep/text/3176-cargo-multi-dep-artifacts.md)
Allow Cargo packages to depend on the same crate multiple times with different dependency names, to support artifact dependencies for multiple targets.
[RFC 3028](https://github.com/rust-lang/rfcs/blob/HEAD/text/3028-cargo-binary-dependencies.md) specified "artifact dependencies", allowing crates to depend on a compiled binary provided by another crate, for a specified target.
Some crates need to depend on binaries for multiple targets; for instance, a virtual machine that supports running multiple targets may need firmware for each target platform. Sometimes these binaries may come from different crates, but sometimes these binaries may come from the same crate compiled for different …

Multiple artifact deps on the same crate with different names, for different targets

---

text/0000-cargo-cli-crate-type.md
text/3180-cargo-cli-crate-type.md

Add the ability to provide `--crate-type <crate-type>` as an argument to `cargo build`. This would have the same affect of adding `crate-type` in the `Cargo.toml`, while taking higher priority than any value specified there.
[Rendered](https://github.com/seanmonstar/rfcs/blob/cargo-crate-type-cli/text/0000-cargo-cli-crate-type.md)

Cargo `--crate-type` CLI Argument

---

text/0000-float-next-up-down.md
text/3173-float-next-up-down.md

This RFC adds two argumentless methods to `f32`/`f64`, `next_up` and `next_down`. These functions are specified in the IEEE 754 standard, and provide the capability to enumerate floating point values in order.
[Rendered](https://github.com/orlp/rfcs/blob/float-next-up-down/text/0000-float-next-up-down.md).
There's also already an associated implementation pull request (https://github.com/rust-lang/rust/pull/88728), should this RFC pass or be deemed unnecessary.

Add RFC float-next-up-down.

---

text/0000-static-async-fn-in-trait.md
text/3185-static-async-fn-in-trait.md

This is an RFC to support `async fn` in traits that can be called via static dispatch. These will desugar to an anonymous associated type.
[Rendered](https://github.com/tmandry/rfcs/blob/static-async-fn-in-trait/text/3185-static-async-fn-in-trait.md)
This RFC was authored as part of the [async fundamentals initiative](https://rust-lang.github.io/async-fundamentals-initiative/index.html).

Static async fn in traits

---

text/0000-thread-local-cell-methods.md
text/3184-thread-local-cell-methods.md

[Rendered](https://github.com/m-ou-se/rfcs/blob/thread-local-cell-methods/text/0000-thread-local-cell-methods.md)
This is a relatively small RFC. But I figured it'd be nice to discuss the API and alternatives here where it gets a bit more attention. (And without getting distracted by the implementation details of `.set()`.)

Thread local Cell methods.

---

text/2996-async-iterator.md

[RENDERED](https://github.com/yoshuawuyts/rfcs/blob/async-iterator/text/2996-async-iterator.md)
_[Tracking Issue](https://github.com/rust-lang/rust/issues/79024)_
This PR updates `RFC 2996: Async Stream` to use "async iterator" terminology instead. This was brought up on the [`async_stream` tracking issue](https://github.com/rust-lang/rust/issues/79024#issuecomment-816868752) by @joshtriplett, capturing a conversation that happened on Zulip. The proposal has since seen quite a bit of support both from the ecosystem and async foundations working group.
Additionally there is also strong precedence in other languages for using an "iterator"/"async iterator" naming scheme:
- JavaScript: [`Symbol.Iterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/ …

Amend RFC 2996 to replace `Stream` with  `AsyncIterator`

---

text/3107-derive-default-enum.md

The actual feature name used in the compiler is `derive_default_enum`. This changes the RFC to mirror that and additionally removes a leftover word from drafting (that is grammatically incorrect and could be confusing).

Change feature name, fix grammatical error

---

generate-book.sh

FIXES #3214:
* Omit using "ln -r" for symbolic link creation
* Create symbolic links with old style expression
* Creates relative links

FIXES #3214 generate-books.sh: ln --relative not supported on macOS

---

text/2115-argument-lifetimes.md

This leaves all the original text unaltered, just provides a helpful note to the reader, like has been done in other things like 2203.

Add a note to 2115 about un-accepting in-band

---

text/0000-scoped-threads.md
text/3151-scoped-threads.md

The successor to https://github.com/rust-lang/rfcs/pull/2647 .
Add scoped threads to the standard library that allow spawning threads that borrow variables from the parent thread.
```rust
let var = String::from("foo");
thread::scope(|s| {
s.spawn(|_| println!("borrowed from thread #1: {}", var));
s.spawn(|_| println!("borrowed from thread #2: {}", var));
});
```
[Rendered](https://github.com/bstrie/rfcs/blob/scoped-threads-draft-2021-06-09/text/0000-scoped-threads.md)

Scoped threads in the standard library, take 2

---

text/2580-ptr-meta.md

Changes a typo in the RFC from "wether" to "whether"

Minor typo fix "wether" -> "whether"

---

text/3137-let-else.md

Currently the link is interpreted as https://github.com/rust-lang/rfcs/blob/master/text/prior-art or https://rust-lang.github.io/rfcs/prior-art. This changes it to the right location.

Fix link for prior-art in RFC3137

---

text/0000-dyno.md
text/3192-dyno.md

[Rendered](https://github.com/nrc/rfcs/blob/dyno/text/0000-dyno.md)
---
This RFC proposes adding a `provide_any` module to the core library. The module provides a generic API for objects to provide type-based access to data. (In contrast to the [`any` module](https://doc.rust-lang.org/nightly/std/any/index.html) which provides type-driven downcasting, the proposed module integrates downcasting into data access to provide a safer and more ergonomic API).

Add provide_any module to core

---

text/1884-unstable-sort.md

These pages have gone 404, but seem worth preserving. Linked to archive.org instead.
Apparently I'm not the first one to notice this disappearance: https://www.reddit.com/r/rust/comments/senamw/what_happened_to_stjepang/

Fix broken links in RFC 1884

---

text/0000-cfg-target.md

This is taking over #2991 by adding the missing part requested by @joshtriplett [here](https://github.com/rust-lang/rfcs/pull/2991#issuecomment-861712521).
[rendered](https://github.com/GuillaumeGomez/rfcs/blob/cfg-target/text/0000-cfg-target.md)

RFC: Add `target` configuration 

---

text/0000-closure-lifetime-binder.md

[Rendered](https://github.com/Aaron1011/rfcs/blob/higher-ranked-closure/text/0000-closure-lifetime-binder.md)
Allow declaring closures using the `for<'a>` syntax:
```rust
let closure = for<'a> |val: &'a u8| println!("Val: {:?}", val);
closure(&25);
```
This guarantees that the closure will use a higher-ranked lifetime, regardless of how the closure is used in the rest of the function.
This went through a pre-RFC at https://internals.rust-lang.org/t/pre-rfc-allow-for-a-syntax-with-closures-for-explicit-higher-ranked-lifetimes/15888. Thank you to everyone who provided feedback!

Allow using `for<'a>` syntax when declaring closures

---

text/0000-types-team.md

This RFC introduces the "type system team" or "types team". This team formally is a subteam of both the lang and compiler team. It's primary tasks are to define and maintain the design and implementation of Rust's type checker, trait solver, and borrow checker.
[Rendered RFC](https://github.com/jackh726/rfcs/blob/types-team/text/0000-types-team.md)
This RFC was authored in large part by @nikomatsakis and other mentions of the *current* traits working group (and future types team).
Prior discussion can be found on zulip, [here](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/making.20a.20team.20for.20traits.2C.20polonius.2C.20etc/near/273563728) and [here](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/types.20team.20RFC/near/276106305).

Create a types team

---

text/3228-process-process_group.md

Add a `process_group` method to `std::os::unix::process::CommandExt` that
allows setting the process group id (i.e. calling `setpgid`) in the child, thus
enabling users to set process groups while leveraging the `posix_spawn` fast
path.

RFC: Add a `process_group` method to UNIX `CommandExt`

---

text/3239-cfg-target.md

As requested in https://github.com/rust-lang/rust/pull/96909#issuecomment-1148979831

Mention de-approval of `cfg(target = "...")`

---

text/0195-associated-items.md

Related to [Fixed the associated syntax error in the associated type Trait Headers](https://github.com/rust-lang/rfcs/issues/3281#issuecomment-1185326642)
Closes #3281

Fixed the associated syntax error in the associated type Trait Headers

---

text/0000-compiler-team-rolling-leads.md

The Rust Compiler Team has used a co-leadership model since late 2019. This RFC codifies the expectations the team has for its leads and the time and effort we expect to be necessary to meet those expectations. It also specifies a
succession plan, via which a team member can rotate through junior and senior
leadership positions.
Note: this RFC is adapted from a longer [document](https://hackmd.io/2dnAg2SNS5CbRkljqLHaeg?view) by pnkfelix. That draft was the subject of compiler team steering meeting ([compiler-team#506][]) and has also been circulated amongst project leadership. In other words: No surprises here.
[compiler-team#506]: https://github.com/rust-lang/compiler-team/issues/506
Rendered text: https://github.com/pnkfelix/rfcs/blob/compiler-team-rolling-leads/text/0000-compiler-team-r …

Rolling co-lead roles for T-compiler

---

text/0000-source_replacement_ambiguity.md

When Cargo is performing an API operation (`yank`/`login`/`publish`/etc.) to a source-replaced `crates-io`, require the user to pass `--registry <NAME>` to specify exactly which registry to use. Additionally, ensure that the token for `crates-io` is never sent to a replacement registry.
[Rendered](https://github.com/arlosi/rfcs/blob/sr/text/0000-source_replacement_ambiguity.md)

RFC: resolve crates.io source replacement ambiguity

---

text/3245-refined-impls.md

This RFC generalizes the [`safe_unsafe_trait_methods` RFC][safe_unsafe], allowing implementations of traits to add type information about the API of their methods and constants which then become part of the API for that type. Specifically, lifetimes and where clauses are allowed to extend beyond what the trait provides.
[safe_unsafe]: https://rust-lang.github.io/rfcs/2316-safe-unsafe-trait-methods.html
[Rendered RFC](https://github.com/tmandry/rfcs/blob/refined-impls/text/3245-refined-impls.md)
This RFC was authored as part of the [async fundamentals initiative](https://rust-lang.github.io/async-fundamentals-initiative/index.html).

Refined trait implementations

---

text/2514-union-initialization-and-drop.md

It's minor, but also a surprisingly confusing typo if you're new to this feature.

Fix order of operations typo in RFC 2514

---

text/2906-cargo-workspace-deduplicate.md

https://github.com/rust-lang/cargo/pull/10564 changed the metadata inheritance source from `workspace` to `workspace.package`
[Rendered](https://github.com/messense/rfcs/blob/patch-1/text/2906-cargo-workspace-deduplicate.md)

Add a note about the design change of RFC 2906 in implementation

---

README.md

I always have to search for the RFC book, usually with a search engine.
I now realize it is also set as homepage for this GitHub repository, but GH hides the homepage link in the sidebar so it is really easy to miss. The "Active RFC List" is several times more visible, but when I want to look for existing ratified RFCs it does not help...

prominent link to RFC book

---

text/0243-trait-based-exception-handling.md

This fixes the code blocks that broke in my previous commit and adds a note about RFC 2046 `label-break-value`

Fix RFC 243 code blocks and add note

---

0000-template.md

Add some points to encourage RFCs to discuss how a proposal impacts the
ease of reading, understanding, and maintaining Rust code, not just the
ease of writing it.
Inspired by many recent discussions on proposed language features.
cc @rust-lang/lang

0000-template.md: Encourage discussion of maintenance

---

text/0000-crates-io-token-scopes.md
text/2947-crates-io-token-scopes.md

This RFC proposes implementing scopes for crates.io tokens, allowing users to choose which endpoints the token is allowed to call and which crates it's allowed to affect.
[Rendered](https://github.com/pietroalbini/rfcs/blob/crates-io-token-scopes/text/0000-crates-io-token-scopes.md)

crates.io token scopes

---

.github/workflows/deploy.yml
book.toml

Most example code in RFCs is not written with executability in mind, so having the "Run" button available by default on all RFCs seems a bit misleading. This now disables the playground for the whole book (which also removes the "hidden" code mdbook inserts). It thus only leaves the copy button.

Disable the playground run button by default for code blocks

---

text/0000-lang-team-advisors.md

Create a new subteam of the lang team entitled **Lang Team Advisors**:
* Advisors are people whose feedback and judgment is highly valued by the lang team.
* Advisors are notified when the lang team makes FCP decisions; while they don't need to approve explicitly, they may raise blocking objections.
* Advisors are not generally expected or required to attend meetings, unless the meeting pertains to their area of expertise.
Co-authored with @joshtriplett 
[Rendered](https://github.com/nikomatsakis/rfcs/blob/lang-team-advisors/text/0000-lang-team-advisors.md)

Add lang-team advisors team

---

text/3323-restrictions.md

(aka sealed traits and read-only fields, sort of)
[Rendered](https://github.com/jhpratt/rfcs/blob/restrictions/text/3323-restrictions.md)

Restrictions

---

text/1857-stabilize-drop-order.md

Website is not accessible on the GitHub.io domain. So change to the current domain.
[Rendered](https://github.com/Jeroendevr/rfcs/blob/patch-1/text/1857-stabilize-drop-order.md)

Update link to blog post

---

text/3348-c-str-literal.md

[Rendered](https://github.com/m-ou-se/rfcs/blob/c-str-literal/text/3348-c-str-literal.md)

RFC: `c"…"` string literals

---

text/0000-offset_of.md
text/3308-offset_of.md

I started this a jillion years ago, and have been meaning to clean it up and submit it for a long time. The intention is to remove most (ideally all) need for hardcoding offsets, computing offsets manually, or using `{memoffset,bytemuck}::offset_of!`.
CC @JakobDegen, @saethlin (since they provided some amount of input on this during RustConf)
[Rendered](https://github.com/thomcc/rfcs/blob/offsetof/text/0000-offset_of.md)

Add `core::mem::offset_of!` RFC

---

.gitattributes

This follows the precedent of similar repos such as [`swift-evolution`](https://github.com/apple/swift-evolution/) and makes Markdown show up as the primary language in GitHub's language bar:

Mark Markdown files as linguist-detectable

---

text/3346-t-opsem.md

This RFC proposes creating T-opsem, a subteam of T-lang that replaces WG-unsafe-code-guidelines and will be the long term owner of questions around undefined behavior, memory models, etc.
There was discussion about this [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/on.20operational.20semantics).
[Rendered](https://github.com/JakobDegen/rust-rfcs/blob/opsem/text/3346-t-opsem.md)

Create an Operational Semantics Team

---

text/2789-sparse-index.md

While GitHub supports implicit URL linkification, mdBook (which is used for <https://rust-lang.github.io/rfcs/2789-sparse-index.html#prior-art>) does not.
[Rendered](https://github.com/rust-lang/rfcs/blob/notriddle/2789-rubygems-link/text/2789-sparse-index.md)

Make rubygems URL a commonmark autolink

---

text/2789-sparse-index.md

when I refer to the sparse index rfc, I found the tracking issue item has the right link ,  but the error link message, this PR fix it.
[Rendered](https://github.com/wangkirin/rfcs/blob/patch-1/text/2789-sparse-index.md)

fix link message typo in rfc-2789

---

text/1721-crt-static.md

This fixes the example of statically linking to msvcrt on Windows to actually work on Windows.
Fixes #3096.

Fix RFC 1721

---

text/0000-standard-lazy-types.md
text/2788-standard-lazy-types.md

Add support for lazy initialized values to standard library, effectively superseding the popular `lazy_static` crate.
```rust
use std::sync::Lazy;
// `BACKTRACE` implements `Deref<Target = Option<String>>` 
// and is initialized on the first access
static BACKTRACE: Lazy<Option<String>> = Lazy::new(|| {
std::env::var("RUST_BACKTRACE").ok()
});
```
[Rendered](https://github.com/matklad/rfcs/blob/std-lazy/text/0000-standard-lazy-types.md)

standard lazy types

---

text/2788-standard-lazy-types.md

To better reflect the current situation.
[Rendered](https://github.com/slanterns/rfcs/blob/2788-add/text/2788-standard-lazy-types.md)

Add two newly created tracking issues to 2788-standard-lazy-types

---

text/0000-result_ffi_guarantees.md
text/3391-result_ffi_guarantees.md

[Rendered](https://github.com/Lokathor/rfcs/blob/optional/text/0000-result_ffi_guarantees.md)

RFC: result_ffi_guarantees

---

text/0000-manifest-lint.md
text/3389-manifest-lint.md

This proposal is trying to make it easier managing project-specific lint overrides.
[Rendered](https://github.com/epage/rfcs/blob/lints/text/3389-manifest-lint.md)

Add a `[lints]` table to `Cargo.toml`

---

text/3127-trim-path.md
text/3127-trim-paths.md

IRLO pre-RFC thread: https://internals.rust-lang.org/t/pre-rfc-cargo-profile-setting-to-sanitise-host-dependent-absolute-paths-enabled-by-default-for-release-builds/14504
Relevant GitHub issue and discussions: https://github.com/rust-lang/rust/issues/40552
[Rendered](https://github.com/cbeuw/rfcs/blob/trim-path/text/3127-trim-paths.md)

New rustc and Cargo options to allow path sanitisation by default

---

text/3127-trim-paths.md

cc @cbeuw 
[Rendered](https://github.com/Nemo157/rfcs/blob/fix-path-prefix-vs-scope/text/3127-trim-paths.md)

Fix some mentions of `--remap-path-prefix` that should be `--remap-path-scope`

---

text/0135-where.md

- Remove extra "is"
- Add missing closing angle brackets
[Rendered](https://github.com/sekunho/rfcs/blob/fix-0135-typos/text/0135-where.md)

Fix typos in RFC 0135

---

text/3216-closure-lifetime-binder.md

[Rendered](https://github.com/rust-lang/rfcs/blob/notriddle/3216-autolink/text/3216-closure-lifetime-binder.md)

Fix autolink syntax on 3216

---

text/0000-return-position-impl-trait-in-traits.md

* Permit `impl Trait` in fn return position within traits and trait impls.
* Allow `async fn` in traits and trait impls to be used interchangeably with its equivalent `impl Trait` desugaring.
* Allow trait impls to `#[refine]` an `impl Trait` return type with added bounds or a concrete type.
This RFC is a collaboration between myself and @compiler-errors, and is based on an [earlier RFC](https://github.com/rust-lang/rfcs/pull/3193) by @nikomatsakis.
The primary changes from that RFC are:
* `async fn` is now allowed to be used interchangeably with its equivalent `impl Trait` desugaring.
* `#[refine]` is now included as a way to add more information about the returned type in an impl, either by adding bounds to the `impl Trait` type, or by using a concrete type. #3245 did not exist at the …

Return position `impl Trait` in traits

---

text/3185-static-async-fn-in-trait.md

Fixes #3447.
[Rendered](https://github.com/peter-kehl/rust-lang-rfcs/blob/3185_correct_feature_name/text/3185-static-async-fn-in-trait.md)

Incorrect feature name: async_fn_in_traits -> correct: async_fn_in_trait

---

README.md

[Rendered](https://github.com/aaronfranke/rfcs/tree/fix-readme-indent#what-the-process-is)
Based on the positions of the `-` symbols, and [how it is currently rendered](https://github.com/rust-lang/rfcs#what-the-process-is), these are sub-points. However, the text was not indented properly in 2 out of 3 of the sub-points. This PR fixes the indentation of the text in the sub-points.
Also, a stray trailing space character was removed on line 6, my text editor did this automatically.

Fix indentation of sub-points in the RFC process list in the README

---

text/0000-rust-spec.md
text/3355-rust-spec.md

[Rendered](https://github.com/m-ou-se/rfcs/blob/rust-spec/text/0000-rust-spec.md)

RFC: Start working on a Rust specification

---

text/3192-dyno.md

This PR addresses the decision by the libs team not to proceed with the `Provider` trait and to merge what's left of RFC 3192 minus `Provider` (ie the `Request` aka `Demand` type) into [the WIP RFC 2895](https://github.com/rust-lang/rfcs/pull/2895).
For reference to these decisions, please see the following starting points:
* see the [May 2023 `provide_any` tracking issue](https://github.com/rust-lang/rust/issues/96024#issuecomment-1554773172) comment
* see the [July 9 2023 zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/error_generic_member_access/near/373733742)
[Rendered](https://github.com/waynr/rust-rfcs/blob/remove-rfc-3912/text/3192-dyno.md)

mark RFC-3192 (aka the 'provide_any' feature) as rejected

---

text/3392-leadership-council.md

This fixes some broken links in RFC 3392. One link used `()` instead of `[]` to refer to a link label. The others used an uppercase letter. Although GitHub's markdown viewer handles mixed case (I'm not sure how, perhaps through some javascript magic), mdBook only allows lowercase.
r? @rylev 
[Rendered](https://github.com/ehuss/rfcs/blob/3392-fix-links/text/3392-leadership-council.md)

RFC 3392: Fix some broken links

---

text/0201-error-chaining.md

Fix start date accoding to the format of `YYYY-MM-DD` in `0000-template.md`.
[Rendered](https://github.com/xzmeng/rfcs/blob/fix-start-date-format-0201/text/0201-error-chaining.md)

Fix start date format in RFC 0201

---

text/0000-t-test.md
text/3455-t-test.md

This RFC proposes creating a new sub-team for shepherding improvements to the end-user experience (wider Rust development community) for verifying their Rust code.  For example, this team would be overseeing improvements to `cargo test` (owned by T-cargo under T-devtools) and lib`test` (owned by T-libs).
[Rendered](https://github.com/epage/rfcs/blob/test/text/3455-t-test.md)

Create a Testing sub-team

---

text/0000-cfg-attribute-in-where.md
text/3399-cfg-attribute-in-where.md

Let's make it more elegant to conditionally compile trait bounds by allowing cfg-attributes directly in where clauses.
[Rendered](https://github.com/recatek/rfcs/blob/cfg-attribute-in-where/text/3399-cfg-attribute-in-where.md)

Allow cfg-attributes in where clauses

---

text/0000-cargo-check-lang-policy.md
text/3477-cargo-check-lang-policy.md

[Rendered](https://github.com/Lokathor/rfcs/blob/check-vs-build/text/0000-cargo-check-lang-policy.md)

Cargo Check T-lang Policy

---

triagebot.toml

This adds it so that Zulip messages will be posted when the corresponding labels are added.

Add Zulip notifications for cargo and crates-io

---

triagebot.toml

Implements [#t-types/types-nominated rfcs](https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/types-nominated.20rfcs).
I've just copied the relevant entry from the `triagebot.toml` in `rust-lang/rust` and tweaked it slightly: https://github.com/rust-lang/rust/blob/af685931799459879b2a8995524755a06ffb5eec/triagebot.toml#L387-L395

Notify Zulip stream on types nominations

---

triagebot.toml

Oops, `#NNN` links to `rust-lang/rust` by default, not `rust-lang/rfcs`. :facepalm:
Fix the links I added in #3499.
Sorry for the noise y'all :see_no_evil:

Fix links in `triagebot.toml`

---

text/0218-empty-struct-with-braces.md
text/0326-restrict-xXX-to-ascii.md
text/0601-replace-be-with-become.md
text/1298-incremental-compilation.md
text/1728-north-star.md
text/2396-target-feature-1.1.md
text/2436-style-guide.md
text/2476-clippy-uno.md
text/3327-lang-team-advisors.md
text/3368-diagnostic-attribute-namespace.md

Found by searching every document for one of the following formats:
```markdown
RFC PR: [rust-lang/rfcs#N](https://github.com/rust-lang/rfcs/pull/N)
RFC PR: [#N](https://github.com/rust-lang/rfcs/pull/N)
RFC PR: [N](https://github.com/rust-lang/rfcs/pull/N)
RFC PR: https://github.com/rust-lang/rfcs/pull/N
RFC PR: (https://github.com/rust-lang/rfcs/pull/N)
RFC PR #: [rust-lang/rfcs#N](https://github.com/rust-lang/rfcs/pull/N)
RFC PR #: [#N](https://github.com/rust-lang/rfcs/pull/N)
RFC PR #: [N](https://github.com/rust-lang/rfcs/pull/N)
RFC PR #: https://github.com/rust-lang/rfcs/pull/N
RFC PR #: (https://github.com/rust-lang/rfcs/pull/N)
```
`for n in $(ls text/[0-9][0-9][0-9][0-9]-*.md | sed 's,text/\(....\).*,\1,' | sort -u); do rg --files-without-match "RFC PR( #)?: …

Fix RFC numbers and pull request links

---

text/0000-remove-implicit-features.md
text/3491-remove-implicit-features.md

[Rendered](https://github.com/epage/rfcs/blob/implicit/text/3491-remove-implicit-features.md)
This would resolve issues like rust-lang/cargo#12173

RFC: Remove implicit features in a new edition

---

text/0000-mixed-utf8-literals.md
text/3349-mixed-utf8-literals.md

[Rendered](https://github.com/m-ou-se/rfcs/blob/mixed-utf8-literals/text/3349-mixed-utf8-literals.md)

RFC: Unicode and escape codes in literals

---

text/3501-edition-2024.md

This RFC is an amendment to [RFC 3085] to declare that the Rust Project intends to produce a new edition in 2024, to set up a project group to deliver the edition, and to establish a tentative cadence for future editions.
[RFC 3085]: https://rust-lang.github.io/rfcs/3085-edition-2021.html
[Rendered](https://github.com/ehuss/rfcs/blob/edition-2024/text/3501-edition-2024.md)

2024 Edition

---

text/3498-lifetime-capture-rules-2024.md

In Rust 2024 and later editions, return position `impl Trait` (RPIT) opaque types will automatically capture all in-scope type *and* lifetime parameters.  In preparation for this, new RPIT-like `impl Trait` features introduced into the Rust 2021 edition will also automatically capture all in-scope type and lifetime parameters.
[Rendered](https://github.com/traviscross/rfcs/blob/TC/lifetime-capture-rules-2024/text/3498-lifetime-capture-rules-2024.md)

Lifetime Capture Rules 2024

---

text/3463-crates-io-policy-update.md

[Rendered](https://github.com/Turbo87/rust-rfcs/blob/crates-io-policy-update/text/3463-crates-io-policy-update.md)
/cc @rust-lang/crates-io

Add "crates.io Policy Update" RFC

---

text/3463-crates-io-policy-update.md

Possible typo, as `User-Agent: reqwest/0.9.1` is used further down.
[Rendered](https://github.com/jiftoo/rfcs/blob/jiftoo-patch-1/text/3463-crates-io-policy-update.md)

request/0.9.1 -> reqwest/0.9.1

---

text/0000-public-private-dependencies.md
text/3516-public-private-dependencies.md

#1977 has languished for 6 years, mostly due to the cargo resolver design section.
This updates the RFC by
- Removing non-essential parts, particularly minimal-version resolution and pub-aware version resolution
- Updating the template
- Taking into account new designs that impact it (`cfg` dependencies, workspace inheritance, renamed dependencies, etc)
- Updates the rustc design for how it evolved in rust-lang/rust#44663
- Fully specifies cargo's behavior
Pub-aware version resolution was such a large part of the previous RFC, that we felt this needed the wider input of an RFC, rather than addressing these in stabilization FCP.
[Rendered](https://github.com/epage/rfcs/blob/pub/text/3516-public-private-dependencies.md)

RFC: Superseding public/private dependencies

---

text/3531-macro-fragment-policy.md

Recently T-lang discussed the issue of macro matcher fragment specifiers, e.g. `expr`, falling out of sync with the underlying grammar of Rust.  The consensus of the meeting was that it would be proper to set out a policy for how these divergences might be reconciled over edition boundaries.
The purpose of this RFC is to memorialize the resulting consensus.
[Rendered](https://github.com/traviscross/rfcs/blob/TC/macro-fragment-policy/text/3531-macro-fragment-policy.md)

Macro fragment specifiers edition policy

---

text/2349-pin.md

fixed a typo in the Pin RFC
[Rendered](https://github.com/1eokim/rfcs/blob/patch-1/text/2349-pin.md)

chore: fix typo in Pin README

---

text/3346-t-opsem.md

Editorial change:
The t-opsem RFC references the t-types RFC, but doesn't actually link to it. The RFC is not called "t-types" so searching for that won't even bring it up. Let's do the internet thing and put in a hyperlink. :)
[Rendered](https://github.com/RalfJung/rfcs/blob/t-opsem-link/text/3346-t-opsem.md)

t-opsem RFC: link to t-types RFC

---

generate-book.py

This PR fixes this 404 error:
… which results from clicking this link:
Alternatives considered:
- Move the "changes" files into `text/`: That would make it a bit more confusing for everyone
- Change the root `collect` invocation to run on `'.'` instead of `'text'`: That would require detecting and special-casing README.md inside `collect`. I prefer explicit enumeration of positives instead of special-casing negatives.

Make top-level special pages part of the web version of the book

---

compiler_changes.md

Lots of this is very outdated, mentioning IRC (:D) and not mentioning MCPs, which are very significant. I adjusted it to something that I feel like is roughly true today. I don't know whether it's fully accurate, but it's definitely more accurate than before.
fixes https://github.com/rust-lang/compiler-team/issues/708
cc @davidtwco @wesleywiser

Update guide on compiler RFCs

---

text/3533-combine-infra-and-release-teams.md

This RFC proposes combining the Infra and Release teams into one team. This change has very little impact outside of the removal of the Release Council representative. Release team interests will be represented by the Infra team representative.
[[Zulip Discussion]](https://rust-lang.zulipchat.com/#narrow/stream/392734-council/topic/Rough.20draft.20proposal.20merging.20Infra.20and.20Release.20teams)
[Rendered](https://github.com/rylev/rust-rfcs/blob/combine-infra-release/text/3533-combine-infra-and-release-teams.md)

Add RFC combining Infra and Release teams

---

text/1201-naked-fns.md

See the [summary comment](https://github.com/rust-lang/rust/issues/32408#issuecomment-1016931986) for details.

Mention RFC 1201 was superseded by RFC 2972

---

text/0000-libtest-json.md
text/3558-libtest-json.md

This eRFC lays out a path for [stabilizing programmatic output for libtest](https://github.com/rust-lang/rust/issues/49359).
[Rendered](https://github.com/epage/rfcs/blob/libtest-json/text/3558-libtest-json.md)
[Tracking Issue](https://github.com/rust-lang/testing-devex-team/issues/1)

eRFC: Iterate on and stabilize libtest's programmatic output

---

.github/workflows/deploy.yml

This updates the GitHub actions to their latest versions. This should remove the warnings that are displayed with the old versions. From testing on my fork, it seems to work.
checkout changelog: https://github.com/actions/checkout/blob/main/CHANGELOG.md#v410
upload-pages-artifact changes: https://github.com/actions/upload-pages-artifact/releases
deploy-pages changes: https://github.com/actions/deploy-pages/releases

Update actions versions

---

text/3558-libtest-json.md

When I merged #3558, I forgot to add the tracking issue, this PR fixes that.
[Rendered](https://github.com/Muscraft/rfcs/blob/update-3558/text/3558-libtest-json.md)

fix: Add tracking issue to #3558

---

.github/renovate.json5
.github/workflows/deploy.yml

see https://github.com/rust-lang/rfcs/pull/3566#issuecomment-1939074653
This adds a basic config file with updates throttled to once-per-month. Once this is merged the corresponding GitHub App needs to be enabled by the infra team for this repo.

Add renovatebot config file

---

text/3389-manifest-lint.md

RFC 3389 refers to a nonexistant lint called `unsafe`. However `unsafe_code` does exist.
This is slightly confusing for readers. This PR does not change the meaning of the RFC, therefore I think this is an improvement.
Edit: Apologies, GitHub had automatically put a link to the RFC as this comment. I have since added an explanation.

Fix typo: Replace `unsafe` with `unsafe_code`, because `unsafe` is not a lint.

---

text/3509-prelude-2024-future.md

This updates the text of RFC https://github.com/rust-lang/rfcs/pull/3509 with [this](https://github.com/rust-lang/rfcs/pull/3509#discussion_r1463621319) and [this](https://github.com/rust-lang/rfcs/pull/3509#discussion_r1463631711) suggestion from review. Thanks!
[Rendered](https://github.com/yoshuawuyts/rfcs/blob/update-future-prelude-rfc/text/3509-prelude-2024-future.md)

update future prelude RFC with feedback from review

---

text/3537-msrv-resolver.md

[Rendered](https://github.com/epage/rfcs/blob/msrv/text/3537-msrv-resolver.md)
[FCP](https://github.com/rust-lang/rfcs/pull/3537#issuecomment-1899285501)
---
*taken from a [post](https://github.com/rust-lang/rfcs/pull/3537#issuecomment-1889675810)*
If the proposed resolver solution is still not to your liking, I would recommend focusing the discussion on (in priority order)
1. Whether there are disagreements on the [core principles](https://github.com/epage/rfcs/blob/msrv/text/3537-msrv-resolver.md#workflows)
2. If agreement above, whether there is disagreement with the [evaluation of the workflows based on the above principles](https://github.com/epage/rfcs/blob/msrv/text/3537-msrv-resolver.md#latest-rust-with-no-msrv)
3. If agreement above, whether there is disagreement with the …

RFC: Make Cargo respect minimum supported Rust version (MSRV) when selecting dependencies

---

text/3243-packages-as-optional-namespaces.md

oopsie
@oli-obk 
[Rendered](https://github.com/rust-lang/rfcs/blob/Manishearth-patch-1/text/3243-packages-as-optional-namespaces.md)

Fix date on RFC 3243

---

text/2963-rustdoc-json.md

Updates type name in the JSON to correctly reflect the code snippet.
[Rendered](https://github.com/HigherOrderLogic/rust-rfcs/blob/master/text/2963-rustdoc-json.md)

Correct rustdoc JSON example

---

text/3498-lifetime-capture-rules-2024.md

In RFC 3498 "Lifetime Capture Rules 2024" we specify that lifetime parameters from `for<..>` binders are captured under the rules.
Currently opaque types in Rust do not support capturing these.  In early drafts of the document, we had called the missing feature "higher ranked lifetime bounds on nested opaque types".  However, we had then noticed that the relevant error message in `rustc` called these "higher kinded" instead:
> error: higher kinded lifetime bounds on nested opaque types are not supported yet
We changed later drafts to follow that language.  But that language was wrong.  These are definitely "higher ranked" lifetime bounds, not "higher kinded" ones, whatever that might mean.  We've now fixed the error message emitted by `rustc` in:
- …

Fix "higher kinded" -> "higher ranked" in RFC 3498

---

text/3543-patchable-function-entry.md

This RFC proposes to add support for the `patchable-function-entry` family of flags and attributes from `clang` and `gcc` in order to support instrumentation and patching as done in the Linux kernel.
I have a [candidate implementation](https://github.com/maurer/rust/tree/patchable-function-entries) and a [MCP](https://github.com/rust-lang/compiler-team/issues/704) to cover just the compiler flag.
[Rendered](https://github.com/maurer/rust-rfcs/blob/patchable-function-entry/text/3543-patchable-function-entry.md)

RFC: patchable-function-entry

---

text/3559-rust-has-provenance.md

I know we usually don't edit accepted RFCs, but this one is a pretty useful resource and collection of links right now (and it's been accepted very recently) so it seems worth the effort.
[Rendered](https://github.com/RalfJung/rfcs/blob/provenance-upd/text/3559-rust-has-provenance.md)

provenance RFC: add link to alternative LLVM proposal

---

text/0235-collections-conventions.md
text/0517-io-os-reform.md
text/1636-document_all_features.md
text/2103-tool-attributes.md

[Rendered](https://github.com/toofooboo/rfcs/blob/master/text/0235-collections-conventions.md)

text: fix typos in comments

---

text/0000-frontmatter.md
text/3503-frontmatter.md

[Rendered](https://github.com/epage/rfcs/blob/frontmatter/text/3503-frontmatter.md)
This is for the T-lang side of #3502
Example:
````rust
#!/usr/bin/env cargo
---
[dependencies]
clap = { version = "4.2", features = ["derive"] }
---
use clap::Parser;
#[derive(Parser, Debug)]
#[clap(version)]
struct Args {
#[clap(short, long, help = "Path to config")]
config: Option<std::path::PathBuf>,
}
fn main() {
let args = Args::parse();
println!("{:?}", args);
}
````
[FCP](https://github.com/rust-lang/rfcs/pull/3503#issuecomment-1930765966)

RFC: Syntax for embedding cargo-script manifests

---

text/3595-move-crates-io-team-under-dev-tools.md

This RFC proposes moving the Crates.io Team under the Dev Tools Team. This change has very little impact outside of the removal of the Crates.io Council representative. Crates.io Team interests will be represented by the Dev Tools team representative.
[Rendered](https://github.com/carols10cents/rfcs/blob/move-crates-io-under-dev-tools/text/3595-move-crates-io-team-under-dev-tools.md)

Move the Crates.io Team under the Dev Tools team

---

text/3606-temporary-lifetimes-in-tail-expressions.md

This is one of the results of the [temporary lifetimes effort](https://rust-lang.zulipchat.com/#narrow/stream/403629-t-lang.2Ftemporary-lifetimes-2024) by @nikomatsakis @dingxiangfei2009 and me.
Originally, we were working on a much larger RFC with several changes, but decided to not block small things on big things.
This part is quite small, but requires an edition change.
[Rendered](https://github.com/m-ou-se/rfcs/blob/tailtemp/text/3606-temporary-lifetimes-in-tail-expressions.md)

RFC: Drop temporaries in tail expressions before local variables

---

text/3593-unprefixed-guarded-strings.md
text/3593-unprefixed_guarded_strings.md

Beginning with the 2024 edition, reserve the syntax `#"foo"#`, as a way of future-proofing against future language changes.
[Rendered](https://github.com/pitaj/rfcs/blob/unprefixed-strings/text/3593-unprefixed_guarded_strings.md)
Note: much of the text of this RFC is directly adapted from #3101. Thank you to @bstrie and all other contributors there for paving the path.

RFC: Reserve unprefixed guarded string literals in Edition 2024

---

text/0000-unsafe-attributes.md
text/3325-unsafe-attributes.md

Consider some attributes 'unsafe', so that they must only be used like this:
```rust
#[unsafe(no_mangle)]
```
[Rendered](https://github.com/RalfJung/rfcs/blob/unsafe-attributes/text/3325-unsafe-attributes.md)
[Prior discussion on IRLO](https://internals.rust-lang.org/t/pre-rfc-unsafe-attributes/17462)

unsafe attributes

---

text/0000-cargo-script.md
text/3502-cargo-script.md

[Rendered](https://github.com/epage/rfcs/blob/script/text/3502-cargo-script.md)
[FCP](https://github.com/rust-lang/rfcs/pull/3502#issuecomment-2072925354)
eRFC rust-lang/rfcs#3424 was previously approved without any direction on syntax or behavior having been decided.  This RFC is to finalize the decisions made through the implementation to prepare the way for stabilization as we work through the remaining tasks in rust-lang/cargo#12207
#3503 covers the T-lang side of this conversation
Example:
````rust
#!/usr/bin/env cargo
---
[dependencies]
clap = { version = "4.2", features = ["derive"] }
---
use clap::Parser;
#[derive(Parser, Debug)]
#[clap(version)]
struct Args {
#[clap(short, long, help = "Path to config")]
config: Option<std::path::PathBuf>,
}
fn main() {
let args = Args::parse(); …
```

RFC: cargo-script

---

text/0000-unsafe-extern-blocks.md
text/3484-unsafe-extern-blocks.md

[Rendered](https://github.com/Lokathor/rfcs/blob/unsafe-extern-blocks/text/3484-unsafe-extern-blocks.md)
Tracking:
- https://github.com/rust-lang/rust/issues/123743
---
Continuation of https://github.com/rust-lang/rfcs/pull/3439, very sorry for the mix up, but when I went to make https://github.com/rust-lang/rfcs/pull/3477 I deleted my `rfcs` repo fork and re-forked. I had forgotten that there was an open PR at the time.

Unsafe Extern Blocks

---

text/3550-new-range.md

Change the range operators `a..b`, `a..`, and `a..=b` to resolve to new types `ops::range::Range`, `ops::range::RangeFrom`, and `ops::range::RangeInclusive` in Edition 2024. These new types will not implement `Iterator`, instead implementing `Copy` and `IntoIterator`.
Closes #2848
[Pre-RFC discussion on IRLO](https://internals.rust-lang.org/t/pre-rfc-fixing-range-by-2027/19936)
[🖥️ Rendered](https://github.com/pitaj/rfcs/blob/new-range/text/3550-new-range.md)
[Analysis of impact on crates in the wild](https://hackmd.io/@uhs6rVdLTSS0gnie4q0fqA/ryjYJW2pa)
Tracking:
- https://github.com/rust-lang/rust/issues/123741

RFC: New range types for Edition 2024

---

text/0000-maybe-dangling.md
text/3336-maybe-dangling.md

Declare that references and `Box` inside a new `MaybeDangling` type do not need to satisfy any memory-dependent validity properties (such as `dereferenceable` and `noalias`).
[Rendered](https://github.com/RalfJung/rfcs/blob/maybe-dangling/text/3336-maybe-dangling.md)
Thanks to @rust-lang/wg-unsafe-code-guidelines for a lot of helpful feedback :)

MaybeDangling

---

text/2094-nll.md

Please see the commit section.
[Rendered](https://github.com/FullyNonlinear/rfcs/blob/master/text/2094-nll.md)

text: minor typo fix in 2094-NLL

---

text/0000-remove-crate-transfer-mediation-policy.md
text/3646-remove-crate-transfer-mediation-policy.md

[Rendered](https://github.com/carols10cents/rfcs/blob/no-crate-transfer-help/text/3646-remove-crate-transfer-mediation-policy.md)

Change crates.io policy to not offer crate transfer mediation

---

text/3416-feature-metadata.md

Copied and pasted from the wrong tab
[Rendered](https://github.com/epage/rfcs/blob/tracking/text/3416-feature-metadata.md)

Fix 3416's tracking issue link

---

text/3621-derive-smart-pointer.md

Use custom smart pointers with trait objects.
[Rendered](https://github.com/Darksonn/rfcs/blob/derive-smart-pointer/text/3621-derive-smart-pointer.md)
Tracking issue: https://github.com/rust-lang/rust/issues/123430
---
Co-authored by @Darksonn and @Veykril 
Thank you to @compiler-errors for [the original idea](https://rust-lang.zulipchat.com/#narrow/stream/410673-t-lang.2Fmeetings/topic/RfL.20meeting.202024-02-21/near/422701742)

RFC: #[derive(SmartPointer)]

---

text/3627-match-ergonomics-2024.md

[Rendered](https://github.com/Jules-Bertholet/rfcs/blob/match-ergonomics-2024/text/3627-match-ergonomics-2024.md)
Changes to match ergonomics for the 2024 edition.
@rustbot label T-lang A-patterns A-edition-2024
Tracking:
- https://github.com/rust-lang/rust/issues/123076

Match ergonomics 2024

---

text/0000-promote-aarch64-apple-darwin-to-tier-1.md

[Rendered](https://github.com/shepmaster/rfcs/blob/aarch64-apple-darwin-tier-1/text/0000-promote-aarch64-apple-darwin-to-tier-1.md)

Promote aarch64-apple-darwin to Tier 1

---

text/3324-dyn-upcasting.md

This is probably meant to say "compiler".
[Rendered](https://github.com/13x1/rfcs/blob/patch-1/text/3324-dyn-upcasting.md)

Fix typo in 3324-dyn-upcasting.md

---

text/3660-crates-io-crate-deletions.md

[Rendered](https://github.com/Turbo87/rust-rfcs/blob/crates-io/crate-deletions/text/3660-crates-io-crate-deletions.md)

crates.io: Crate Deletions

---

text/0000-guard-patterns.md
text/3637-guard-patterns.md

[Rendered](https://github.com/max-niederman/rust-rfcs/blob/guard-patterns/text/3637-guard-patterns.md)

Guard Patterns

---

text/0000-rustdoc-types-maintainers.md
text/3673-rustdoc-types-maintainers.md

See https://github.com/rust-lang/rfcs/pull/3505 for the actual RFC, by @aDotInTheVoid. This PR is just for merging purposes.
[Rendered](https://github.com/aDotInTheVoid/rfcs/blob/rustdoc-types-maintainers/text/0000-rustdoc-types-maintainers.md)

RFC 3673: Move rustdoc-types crate to T-Rustdoc ownership

---

text/0000-feature-unification.md
text/3692-feature-unification.md

This adds `resolver.feature-unification` to `.cargo/config.toml` to allow workspace unfication (cargo-workspace-hack) or per-package unification (`cargo hack`).
[Rendered](https://github.com/epage/rfcs/blob/feature-unification/text/3692-feature-unification.md)

RFC: Give users control over feature unification

---

text/0000-default-field-values.md
text/3681-default-field-values.md

Allow `struct` definitions to provide default values for individual fields and
thereby allowing those to be omitted from initializers. When deriving `Default`,
the provided values will then be used. For example:
```rust
#[derive(Default)]
struct Pet {
name: Option<String>, // impl Default for Pet will use Default::default() for name
age: i128 = 42, // impl Default for Pet will use the literal 42 for age
}
```
[Rendered](https://github.com/estebank/rfcs/blob/default-fields/text/3681-default-field-values.md)
Tracking:
- https://github.com/rust-lang/rust/issues/132162

[RFC] Default field values

---

text/3681-default-field-values.md

Updating `s/missilies/missiles` in the code example that shows how defaults are `const` contexts.
[Rendered](https://github.com/obi1kenobi/rfcs/blob/patch-1/text/3681-default-field-values.md)

Fix typos in code example of RFC 3681

---

text/3681-default-field-values.md

Fixing a one-letter typo in RFC 3681.
[Rendered](https://github.com/obi1kenobi/rfcs/blob/patch-2/text/3681-default-field-values.md)

Fix minor typo in 3681-default-field-values.md

---

text/3660-crates-io-crate-deletions.md

The crates.io team decided in their meeting last week to adjust the RFC and drop the parts about version deletions. The RFC is now only focussed on deleting whole crates.
The team initially thought that using the ruleset from the npm registry was a good idea, but we didn't sufficiently consider that npm does not have the concept of "yanking" a version. npm has version deprecations, but they don't influence package resolution at all, and so they are not comparable. Since yanking a version on crates.io accomplishes a lot of the same things as deleting a version on npm, the case for version deletion on crates.io is weak. The main use case would be to delete things that were not intended to be public. But due to the nature of crates.io having various inofficial mirrors, once something is …

crates.io: Remove version deletions from the "crate deletions" RFC

---

text/3559-rust-has-provenance.md

The RFC had examples for various C compilers, but not for Rust. I often link to the RFC to start explaining provenance to people, and that case becomes more convincing by adding an example here.
[Rendered](https://github.com/RalfJung/rfcs/blob/provenance-example/text/3559-rust-has-provenance.md)

provenance RFC: add example showing the Rust compiler perform this transformation

---

text/2325-stable-simd.md

I know this is a really trivial and stupid change but I was reading it and it annoyed me.
[Rendered](https://github.com/Stoneblackdog/rfcs/blob/patch-1/text/2325-stable-simd.md)

Fix typo in 2325-stable-simd.md

---

text/3668-async-closures.md

Insignificant, but could be confusing at first glance. Hope it can be fixed.
[Rendered](https://github.com/po1onius/rfcs/blob/oversight-fix/text/3668-async-closures.md)

Fix syntax error caused by missing curly braces in example code

---

text/3722-explicit-abi.md
text/3722-explicit-extern-abis.md

[Rendered](https://github.com/m-ou-se/rfcs/blob/explicit-abi/text/3722-explicit-extern-abis.md)
Tracking:
- https://github.com/rust-lang/rust/issues/134986

[RFC] Explicit ABI in `extern`

---

triagebot.toml

This PR adds the new config related to the rendered links.
cc https://github.com/rust-lang/triagebot/pull/1868
cc @ehuss

Use rustbot config to configure rendered links

---

text/3654-return-type-notation.md

[Rendered](https://github.com/Wilfred/rfcs/blob/patch-1/text/3654-return-type-notation.md)

Update 3654-return-type-notation.md: Fix typo

---

text/0000-supertrait-item-shadowing-v2.md
text/3624-supertrait-item-shadowing-v2.md

This is an alternative to #2845 which aims to resolve the [issues](https://github.com/rust-lang/rust/issues/88967) surrounding the stabilization of `Iterator::intersperse`.
[summary]: #summary
When name resolution encounters an ambiguity between 2 trait methods, if one trait is a sub-trait of the other then select that method instead of reporting an ambiguity error.
[Rendered](https://github.com/Amanieu/rfcs/blob/item-shadowing/text/3624-supertrait-item-shadowing-v2.md)

Supertrait item shadowing v2

---

text/3771-demote-i686-pc-windows-gnu.md

[Rendered](https://github.com/Noratrieb/rfcs/blob/i686-pc-windows-gnu/text/3771-demote-i686-pc-windows-gnu.md)

RFC: Demote i686-pc-windows-gnu to Tier 2

---

text/2093-infer-outlives.md

[Rendered](https://github.com/hkBst/rfcs/blob/patch-2/text/2093-infer-outlives.md)

Fix typo in 2093-infer-outlives.md

---

text/000-rustdoc-cfgs-handling.md

[tracking issue](https://github.com/rust-lang/rust/issues/43781)
cc @rust-lang/rustdoc
[Rendered](https://github.com/GuillaumeGomez/rfcs/blob/doc-cfg/text/000-rustdoc-cfgs-handling.md)

RFC for doc_cfg, doc_cfg_auto, doc_cfg_hide and doc_cfg_show features

---

text/3631-rustdoc-cfgs-handling.md

Went too quickly in https://github.com/rust-lang/rfcs/pull/3631 and forgot to rename the RFC file...
[Rendered](https://github.com/GuillaumeGomez/rfcs/blob/rustdoc-doc-cfg-rfc/text/3631-rustdoc-cfgs-handling.md)

Rename RFC and update RFC pull request link

---

0000-template.md

The template had a very short explanation of the motivation, which probably led many people into believing that the motivation can be rather short, compared to the explanations.
But really, the motivation is extremely important and should often contain a lot of information. This makes those expectations a lot more explicit. It also explicitly asks for use cases to be listed out, which can then be referenced in the rest of the RFC to make it clearer how it solves the problem.

Elaborate on motivation in template

---

text/0000-declarative-attribute-macros.md
text/3697-declarative-attribute-macros.md

Many crates provide attribute macros. Today, this requires defining proc
macros, in a separate crate, typically with several additional dependencies
adding substantial compilation time, and typically guarded by a feature that
users need to remember to enable.
However, many common cases of attribute macros don't require any more power
than an ordinary `macro_rules!` macro. Supporting these common cases would
allow many crates to avoid defining proc macros, reduce dependencies and
compilation time, and provide these macros unconditionally without requiring a
the user to enable a feature.
I've reviewed several existing proc-macro-based attributes in the ecosystem,
and it appears that many would be able to use this feature to avoid needing
proc macros at all. …

Declarative `macro_rules!` attribute macros

---

text/3698-declarative-derive-macros.md

Many crates support deriving their traits with `derive(Trait)`. Today, this
requires defining proc macros, in a separate crate, typically with several
additional dependencies adding substantial compilation time, and typically
guarded by a feature that users need to remember to enable.
However, many common cases of derives don't require any more power than an
ordinary `macro_rules!` macro. Supporting these common cases would allow many
crates to avoid defining proc macros, reduce dependencies and compilation time,
and provide these macros unconditionally without requiring the user to enable a
feature.
I've reviewed several existing proc-macro-based derives in the ecosystem, and
it appears that many would be able to use this feature to avoid needing proc
macros at all. …

Declarative `macro_rules!` derive macros

---

text/3817-promote-aarch64-pc-windows-msvc-to-tier-1.md

[Rendered](https://github.com/dpaoliello/rfcs/blob/aarch64tier1/text/3817-promote-aarch64-pc-windows-msvc-to-tier-1.md)

RFC: Promote aarch64-pc-windows-msvc to Tier 1

---

triagebot.toml

As discussed in https://github.com/rust-lang/rfcs/pull/3865#issuecomment-3360018912, let's add us as the reviewer team for "not-rfc" changes in this repo.
r? @jieyouxu

Add automatic assignment to the internal-sites team
